// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssString$Css = require("./CssString.js");

function border(v) {
  return v;
}

function border2(style, widthOrColor) {
  var widthOrColor$1;
  if (typeof widthOrColor === "object") {
    var variant = widthOrColor.NAME;
    widthOrColor$1 = variant === "rem" || variant === "vw" || variant === "vh" || variant === "px" || variant === "pt" || variant === "pc" || variant === "mm" || variant === "ex" || variant === "em" || variant === "cm" || variant === "ch" || variant === "vmin" || variant === "vmax" || variant === "inch" ? CssString$Css.lineWidth(widthOrColor) : CssString$Css.color(widthOrColor);
  } else {
    widthOrColor$1 = widthOrColor === "thick" || widthOrColor === "medium" || widthOrColor === "thin" ? CssString$Css.lineWidth(widthOrColor) : CssString$Css.color(widthOrColor);
  }
  return style + " " + widthOrColor$1;
}

function border3(width, style, color) {
  return CssString$Css.lineWidth(width) + " " + style + " " + CssString$Css.color(color);
}

function borderColor(v) {
  if (typeof v === "object" || !(v === "inherit" || v === "unset" || v === "revert" || v === "initial")) {
    return CssString$Css.color(v);
  } else {
    return v;
  }
}

function borderColor2(tb, lr) {
  return CssString$Css.color(tb) + " " + CssString$Css.color(lr);
}

function borderColor3(top, lr, bottom) {
  return CssString$Css.color(top) + " " + CssString$Css.color(lr) + " " + CssString$Css.color(bottom);
}

function borderColor4(top, right, bottom, left) {
  return CssString$Css.color(top) + " " + CssString$Css.color(right) + " " + CssString$Css.color(bottom) + " " + CssString$Css.color(left);
}

function borderStyle(v) {
  return v;
}

function borderStyle2(tb, lr) {
  return tb + " " + lr;
}

function borderStyle3(top, lr, bottom) {
  return top + " " + lr + " " + bottom;
}

function borderStyle4(top, right, bottom, left) {
  return top + " " + right + " " + bottom + " " + left;
}

exports.border = border;
exports.border2 = border2;
exports.border3 = border3;
exports.borderColor = borderColor;
exports.borderColor2 = borderColor2;
exports.borderColor3 = borderColor3;
exports.borderColor4 = borderColor4;
exports.borderStyle = borderStyle;
exports.borderStyle2 = borderStyle2;
exports.borderStyle3 = borderStyle3;
exports.borderStyle4 = borderStyle4;
/* No side effect */
