// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssString$Ress = require("./CssString.js");

function border(width, color, style) {
  var border$1 = width !== undefined ? (
      color !== undefined ? CssString$Ress.lineWidth(width) + " " + CssString$Ress.color(color) : CssString$Ress.lineWidth(width)
    ) : (
      color !== undefined ? CssString$Ress.color(color) : undefined
    );
  if (style === "inherit" || style === "unset" || style === "revert" || style === "initial" || border$1 === undefined) {
    return style;
  } else {
    return border$1 + " " + style;
  }
}

var borderColor = CssString$Ress.color_global;

function borderColor2(tb, lr) {
  return CssString$Ress.color(tb) + " " + CssString$Ress.color(lr);
}

function borderColor3(top, lr, bottom) {
  return CssString$Ress.color(top) + " " + CssString$Ress.color(lr) + " " + CssString$Ress.color(bottom);
}

function borderColor4(top, right, bottom, left) {
  return CssString$Ress.color(top) + " " + CssString$Ress.color(right) + " " + CssString$Ress.color(bottom) + " " + CssString$Ress.color(left);
}

var borderTopColor = CssString$Ress.color_global;

var borderRightColor = CssString$Ress.color_global;

var borderBottomColor = CssString$Ress.color_global;

var borderLeftColor = CssString$Ress.color_global;

function borderStyle(v) {
  return v;
}

function borderStyle2(tb, lr) {
  return tb + " " + lr;
}

function borderStyle3(top, lr, bottom) {
  return top + " " + lr + " " + bottom;
}

function borderStyle4(top, right, bottom, left) {
  return top + " " + right + " " + bottom + " " + left;
}

function borderTopStyle(v) {
  return v;
}

function borderRightStyle(v) {
  return v;
}

function borderBottomStyle(v) {
  return v;
}

function borderLeftStyle(v) {
  return v;
}

var borderWidth = CssString$Ress.lineWidth_global;

function borderWidth2(tb, lr) {
  return CssString$Ress.lineWidth(tb) + " " + CssString$Ress.lineWidth(lr);
}

function borderWidth3(top, lr, bottom) {
  return CssString$Ress.lineWidth(top) + " " + CssString$Ress.lineWidth(lr) + " " + CssString$Ress.lineWidth(bottom);
}

function borderWidth4(top, right, bottom, left) {
  return CssString$Ress.lineWidth(top) + " " + CssString$Ress.lineWidth(right) + " " + CssString$Ress.lineWidth(bottom) + " " + CssString$Ress.lineWidth(left);
}

var borderTopWidth = CssString$Ress.lineWidth_global;

var borderRightWidth = CssString$Ress.lineWidth_global;

var borderBottomWidth = CssString$Ress.lineWidth_global;

var borderLeftWidth = CssString$Ress.lineWidth_global;

function background(color, position, size, repeat, attachment, origin, clip, imageOrColor) {
  var imageOrColor$1;
  if (typeof imageOrColor === "object") {
    imageOrColor$1 = imageOrColor;
  } else {
    if (imageOrColor === "inherit" || imageOrColor === "unset" || imageOrColor === "revert" || imageOrColor === "initial") {
      return imageOrColor;
    }
    imageOrColor$1 = imageOrColor;
  }
  return CssString$Ress.background(color, position, size, repeat, attachment, origin, clip, imageOrColor$1);
}

function background2(l1, l2) {
  return CssString$Ress.bgLayer(l1) + ", " + CssString$Ress.bgLayer(l2);
}

function background3(l1, l2, l3) {
  return CssString$Ress.bgLayer(l1) + ", " + CssString$Ress.bgLayer(l2) + ", " + CssString$Ress.bgLayer(l3);
}

function background4(l1, l2, l3, l4) {
  return CssString$Ress.bgLayer(l1) + ", " + CssString$Ress.bgLayer(l2) + ", " + CssString$Ress.bgLayer(l3) + ", " + CssString$Ress.bgLayer(l4);
}

function backgroundAttachment(v) {
  return v;
}

function backgroundAttachment2(v1, v2) {
  return v1 + ", " + v2;
}

function backgroundAttachment3(v1, v2, v3) {
  return v1 + ", " + v2 + ", " + v3;
}

function backgroundAttachment4(v1, v2, v3, v4) {
  return v1 + ", " + v2 + ", " + v3 + ", " + v4;
}

var backgroundColor = CssString$Ress.color;

var backgroundImage = CssString$Ress.bgImage;

function backgroundImage2(v1, v2) {
  return CssString$Ress.bgImage(v1) + ", " + CssString$Ress.bgImage(v2);
}

function backgroundImage3(v1, v2, v3) {
  return CssString$Ress.bgImage(v1) + ", " + CssString$Ress.bgImage(v2) + ", " + CssString$Ress.bgImage(v3);
}

function backgroundImage4(v1, v2, v3, v4) {
  return CssString$Ress.bgImage(v1) + ", " + CssString$Ress.bgImage(v2) + ", " + CssString$Ress.bgImage(v3) + ", " + CssString$Ress.bgImage(v4);
}

var backgroundPosition = CssString$Ress.position;

function backgroundPosition2(v1, v2) {
  return CssString$Ress.position(v1) + ", " + CssString$Ress.position(v2);
}

function backgroundPosition3(v1, v2, v3) {
  return CssString$Ress.position(v1) + ", " + CssString$Ress.position(v2) + ", " + CssString$Ress.position(v3);
}

function backgroundPosition4(v1, v2, v3, v4) {
  return CssString$Ress.position(v1) + ", " + CssString$Ress.position(v2) + ", " + CssString$Ress.position(v3) + ", " + CssString$Ress.position(v4);
}

function backgroundStyle(v) {
  return v;
}

function backgroundStyle2(v1, v2) {
  return v1 + ", " + v2;
}

function backgroundStyle3(v1, v2, v3) {
  return v1 + ", " + v2 + ", " + v3;
}

function backgroundStyle4(v1, v2, v3, v4) {
  return v1 + ", " + v2 + ", " + v3 + ", " + v4;
}

var margin = CssString$Ress.margin_global;

function margin2(tb, lr) {
  return CssString$Ress.margin(tb) + " " + CssString$Ress.margin(lr);
}

function margin3(top, lr, bottom) {
  return CssString$Ress.margin(top) + " " + CssString$Ress.margin(lr) + " " + CssString$Ress.margin(bottom);
}

function margin4(top, right, bottom, left) {
  return CssString$Ress.margin(top) + " " + CssString$Ress.margin(right) + " " + CssString$Ress.margin(bottom) + " " + CssString$Ress.margin(left);
}

var marginTop = CssString$Ress.margin_global;

var marginRight = CssString$Ress.margin_global;

var marginBottom = CssString$Ress.margin_global;

var marginLeft = CssString$Ress.margin_global;

var padding = CssString$Ress.padding_global;

function padding2(tb, lr) {
  return CssString$Ress.padding(tb) + " " + CssString$Ress.padding(lr);
}

function padding3(top, lr, bottom) {
  return CssString$Ress.padding(top) + " " + CssString$Ress.padding(lr) + " " + CssString$Ress.padding(bottom);
}

function padding4(top, right, bottom, left) {
  return CssString$Ress.padding(top) + " " + CssString$Ress.padding(right) + " " + CssString$Ress.padding(bottom) + " " + CssString$Ress.padding(left);
}

var paddingTop = CssString$Ress.padding_global;

var paddingRight = CssString$Ress.padding_global;

var paddingBottom = CssString$Ress.padding_global;

var paddingLeft = CssString$Ress.padding_global;

function clear(v) {
  return v;
}

var color = CssString$Ress.color_global;

function cursor(v) {
  return v;
}

function cursor1(i, k) {
  return CssString$Ress.cursorImage(i) + ", " + k;
}

function cursor2(i1, i2, k) {
  return CssString$Ress.cursorImage(i1) + ", " + CssString$Ress.cursorImage(i2) + ", " + k;
}

function cursor3(i1, i2, i3, k) {
  return CssString$Ress.cursorImage(i1) + ", " + CssString$Ress.cursorImage(i2) + ", " + CssString$Ress.cursorImage(i3) + ", " + k;
}

function cursor4(i1, i2, i3, i4, k) {
  return CssString$Ress.cursorImage(i1) + ", " + CssString$Ress.cursorImage(i2) + ", " + CssString$Ress.cursorImage(i3) + ", " + CssString$Ress.cursorImage(i4) + ", " + k;
}

exports.border = border;
exports.borderColor = borderColor;
exports.borderColor2 = borderColor2;
exports.borderColor3 = borderColor3;
exports.borderColor4 = borderColor4;
exports.borderTopColor = borderTopColor;
exports.borderRightColor = borderRightColor;
exports.borderBottomColor = borderBottomColor;
exports.borderLeftColor = borderLeftColor;
exports.borderStyle = borderStyle;
exports.borderStyle2 = borderStyle2;
exports.borderStyle3 = borderStyle3;
exports.borderStyle4 = borderStyle4;
exports.borderTopStyle = borderTopStyle;
exports.borderRightStyle = borderRightStyle;
exports.borderBottomStyle = borderBottomStyle;
exports.borderLeftStyle = borderLeftStyle;
exports.borderWidth = borderWidth;
exports.borderWidth2 = borderWidth2;
exports.borderWidth3 = borderWidth3;
exports.borderWidth4 = borderWidth4;
exports.borderTopWidth = borderTopWidth;
exports.borderRightWidth = borderRightWidth;
exports.borderBottomWidth = borderBottomWidth;
exports.borderLeftWidth = borderLeftWidth;
exports.background = background;
exports.background2 = background2;
exports.background3 = background3;
exports.background4 = background4;
exports.backgroundAttachment = backgroundAttachment;
exports.backgroundAttachment2 = backgroundAttachment2;
exports.backgroundAttachment3 = backgroundAttachment3;
exports.backgroundAttachment4 = backgroundAttachment4;
exports.backgroundColor = backgroundColor;
exports.backgroundImage = backgroundImage;
exports.backgroundImage2 = backgroundImage2;
exports.backgroundImage3 = backgroundImage3;
exports.backgroundImage4 = backgroundImage4;
exports.backgroundPosition = backgroundPosition;
exports.backgroundPosition2 = backgroundPosition2;
exports.backgroundPosition3 = backgroundPosition3;
exports.backgroundPosition4 = backgroundPosition4;
exports.backgroundStyle = backgroundStyle;
exports.backgroundStyle2 = backgroundStyle2;
exports.backgroundStyle3 = backgroundStyle3;
exports.backgroundStyle4 = backgroundStyle4;
exports.margin = margin;
exports.margin2 = margin2;
exports.margin3 = margin3;
exports.margin4 = margin4;
exports.marginTop = marginTop;
exports.marginRight = marginRight;
exports.marginBottom = marginBottom;
exports.marginLeft = marginLeft;
exports.padding = padding;
exports.padding2 = padding2;
exports.padding3 = padding3;
exports.padding4 = padding4;
exports.paddingTop = paddingTop;
exports.paddingRight = paddingRight;
exports.paddingBottom = paddingBottom;
exports.paddingLeft = paddingLeft;
exports.clear = clear;
exports.color = color;
exports.cursor = cursor;
exports.cursor1 = cursor1;
exports.cursor2 = cursor2;
exports.cursor3 = cursor3;
exports.cursor4 = cursor4;
/* No side effect */
