// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

function num(v) {
  return String(v);
}

function number(v) {
  return String(v.VAL);
}

function intg(v) {
  return String(v);
}

function integer(v) {
  return String(v.VAL);
}

function string(v) {
  return v.VAL;
}

function scalar(v) {
  var variant = v.NAME;
  if (variant === "string") {
    return v.VAL;
  } else {
    return String(v.VAL);
  }
}

function ch(l) {
  return String(l) + "ch";
}

function em(l) {
  return String(l) + "em";
}

function ex(l) {
  return String(l) + "ex";
}

function rem(l) {
  return String(l) + "rem";
}

function vh(l) {
  return String(l) + "vh";
}

function vw(l) {
  return String(l) + "vw";
}

function vmin(l) {
  return String(l) + "vmin";
}

function vmax(l) {
  return String(l) + "vmax";
}

function px(l) {
  return String(l) + "px";
}

function cm(l) {
  return String(l) + "cm";
}

function mm(l) {
  return String(l) + "mm";
}

function inch(l) {
  return String(l) + "in";
}

function pc(l) {
  return String(l) + "pc";
}

function pt(l) {
  return String(l) + "pt";
}

function length(v) {
  var variant = v.NAME;
  if (variant === "vmax") {
    return String(v.VAL) + "vmax";
  } else if (variant === "vmin") {
    return String(v.VAL) + "vmin";
  } else if (variant === "ch") {
    return String(v.VAL) + "ch";
  } else if (variant === "cm") {
    return String(v.VAL) + "cm";
  } else if (variant === "em") {
    return String(v.VAL) + "em";
  } else if (variant === "ex") {
    return String(v.VAL) + "ex";
  } else if (variant === "mm") {
    return String(v.VAL) + "mm";
  } else if (variant === "pc") {
    return String(v.VAL) + "pc";
  } else if (variant === "pt") {
    return String(v.VAL) + "pt";
  } else if (variant === "px") {
    return String(v.VAL) + "px";
  } else if (variant === "vh") {
    return String(v.VAL) + "vh";
  } else if (variant === "vw") {
    return String(v.VAL) + "vw";
  } else if (variant === "rem") {
    return String(v.VAL) + "rem";
  } else {
    return String(v.VAL) + "in";
  }
}

function pct(v) {
  return String(v) + "%";
}

function percentage(v) {
  return String(v.VAL) + "%";
}

function deg(v) {
  return String(v) + "deg";
}

function grad(v) {
  return String(v) + "grad";
}

function rad(v) {
  return String(v) + "rad";
}

function turn(v) {
  return String(v) + "turn";
}

function angle(v) {
  var variant = v.NAME;
  if (variant === "turn") {
    return String(v.VAL) + "turn";
  } else if (variant === "deg") {
    return String(v.VAL) + "deg";
  } else if (variant === "rad") {
    return String(v.VAL) + "rad";
  } else {
    return String(v.VAL) + "grad";
  }
}

function lineWidth(v) {
  if (typeof v === "object") {
    return length(v);
  } else if (v === "medium") {
    return "medium";
  } else if (v === "thick") {
    return "thick";
  } else {
    return "thin";
  }
}

function hue(v) {
  if (v.NAME === "number") {
    return String(v.VAL);
  } else {
    return angle(v);
  }
}

function alpha(v) {
  if (v.NAME === "number") {
    return String(v.VAL);
  } else {
    return percentage(v);
  }
}

function rgbValue(v) {
  if (v.NAME === "number") {
    return String(v.VAL);
  } else {
    return percentage(v);
  }
}

function hsl(v1, v2, v3) {
  return "hsl(" + hue(v1) + ", " + percentage(v2) + ", " + percentage(v3) + ")";
}

function hsla(v1, v2, v3, v4) {
  return "hsla(" + hue(v1) + ", " + percentage(v2) + ", " + percentage(v3) + ", " + alpha(v4) + ")";
}

function rgb(v1, v2, v3) {
  return "rgb(" + rgbValue(v1) + ", " + rgbValue(v2) + ", " + rgbValue(v3) + ")";
}

function rgba(v1, v2, v3, v4) {
  return "rgba(" + rgbValue(v1) + ", " + rgbValue(v2) + ", " + rgbValue(v3) + ", " + alpha(v4) + ")";
}

function rgbHex(v) {
  return "#" + v;
}

function color(v) {
  if (typeof v !== "object") {
    return v;
  }
  var variant = v.NAME;
  if (variant === "rgba") {
    var match = v.VAL;
    return rgba(match[0], match[1], match[2], match[3]);
  }
  if (variant === "hsl") {
    var match$1 = v.VAL;
    return hsl(match$1[0], match$1[1], match$1[2]);
  }
  if (variant === "rgb") {
    var match$2 = v.VAL;
    return rgb(match$2[0], match$2[1], match$2[2]);
  }
  if (variant === "rgbHex") {
    return "#" + v.VAL;
  }
  var match$3 = v.VAL;
  return hsla(match$3[0], match$3[1], match$3[2], match$3[3]);
}

function combinator(v, cb) {
  var variant = v.NAME;
  if (variant === "concat") {
    var match = v.VAL;
    return Curry._1(cb, match[0]) + " " + Curry._1(cb, match[1]);
  }
  if (variant === "many") {
    return Belt_Array.reduce(v.VAL, "", (function (acc, item) {
                  if (acc.length === 0) {
                    return Curry._1(cb, item);
                  } else {
                    return acc + " " + Curry._1(cb, item);
                  }
                }));
  }
  if (variant === "stack") {
    return Belt_Array.reduce(v.VAL, "", (function (acc, item) {
                  if (acc.length === 0) {
                    return Curry._1(cb, item);
                  } else {
                    return acc + ", " + Curry._1(cb, item);
                  }
                }));
  }
  var match$1 = v.VAL;
  return Curry._1(cb, match$1[0]) + ", " + Curry._1(cb, match$1[1]);
}

function border(v) {
  if (typeof v !== "object") {
    if (v === "inset" || v === "double" || v === "dotted" || v === "dashed" || v === "groove" || v === "outset" || v === "solid" || v === "ridge" || v === "hidden" || v === "none" || v === "inherit" || v === "unset" || v === "initial") {
      return v;
    } else if (v === "thick" || v === "medium" || v === "thin") {
      return lineWidth(v);
    } else {
      return color(v);
    }
  }
  var variant = v.NAME;
  if (variant === "rem" || variant === "vw" || variant === "vh" || variant === "px" || variant === "pt" || variant === "pc" || variant === "mm" || variant === "ex" || variant === "em" || variant === "cm" || variant === "ch" || variant === "vmin" || variant === "vmax" || variant === "inch") {
    return lineWidth(v);
  } else if (variant === "stack" || variant === "many" || variant === "concat" || variant === "join") {
    return combinator(v, border);
  } else if (variant === "number" || variant === "string" || variant === "int") {
    return scalar(v);
  } else {
    return color(v);
  }
}

function borderColor(v) {
  if (typeof v === "object") {
    return color(v);
  } else if (v === "inherit" || v === "unset" || v === "initial") {
    return v;
  } else if (v === "revert") {
    return "revert";
  } else {
    return color(v);
  }
}

exports.num = num;
exports.number = number;
exports.intg = intg;
exports.integer = integer;
exports.string = string;
exports.scalar = scalar;
exports.ch = ch;
exports.em = em;
exports.ex = ex;
exports.rem = rem;
exports.vh = vh;
exports.vw = vw;
exports.vmin = vmin;
exports.vmax = vmax;
exports.px = px;
exports.cm = cm;
exports.mm = mm;
exports.inch = inch;
exports.pc = pc;
exports.pt = pt;
exports.length = length;
exports.pct = pct;
exports.percentage = percentage;
exports.deg = deg;
exports.grad = grad;
exports.rad = rad;
exports.turn = turn;
exports.angle = angle;
exports.hue = hue;
exports.alpha = alpha;
exports.rgbValue = rgbValue;
exports.hsl = hsl;
exports.hsla = hsla;
exports.rgb = rgb;
exports.rgba = rgba;
exports.rgbHex = rgbHex;
exports.color = color;
exports.combinator = combinator;
exports.lineWidth = lineWidth;
exports.border = border;
exports.borderColor = borderColor;
/* No side effect */
