// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var CssRule$Ress = require("../rule/CssRule.js");
var CssClear$Ress = require("../property/CssClear.js");
var CssColor$Ress = require("../property/CssColor.js");
var CssAtRule$Ress = require("../at_rule/CssAtRule.js");
var CssBorder$Ress = require("../property/CssBorder.js");
var CssCursor$Ress = require("../property/CssCursor.js");
var CssMargin$Ress = require("../property/CssMargin.js");
var CssPadding$Ress = require("../property/CssPadding.js");
var CssBorderTop$Ress = require("../property/CssBorderTop.js");
var CssMarginTop$Ress = require("../property/CssMarginTop.js");
var CssBackground$Ress = require("../property/CssBackground.js");
var CssBorderLeft$Ress = require("../property/CssBorderLeft.js");
var CssFontFamily$Ress = require("../property/CssFontFamily.js");
var CssFontWeight$Ress = require("../property/CssFontWeight.js");
var CssMarginLeft$Ress = require("../property/CssMarginLeft.js");
var CssPaddingTop$Ress = require("../property/CssPaddingTop.js");
var CssRuleHelper$Ress = require("../rule/CssRuleHelper.js");
var CssBorderColor$Ress = require("../property/CssBorderColor.js");
var CssBorderRight$Ress = require("../property/CssBorderRight.js");
var CssBorderStyle$Ress = require("../property/CssBorderStyle.js");
var CssBorderWidth$Ress = require("../property/CssBorderWidth.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssMarginRight$Ress = require("../property/CssMarginRight.js");
var CssPaddingLeft$Ress = require("../property/CssPaddingLeft.js");
var CssPseudoClass$Ress = require("../rule/CssPseudoClass.js");
var CssValueHelper$Ress = require("../value/CssValueHelper.js");
var CssAtRuleHelper$Ress = require("../at_rule/CssAtRuleHelper.js");
var CssBorderBottom$Ress = require("../property/CssBorderBottom.js");
var CssMarginBottom$Ress = require("../property/CssMarginBottom.js");
var CssPaddingRight$Ress = require("../property/CssPaddingRight.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");
var CssPaddingBottom$Ress = require("../property/CssPaddingBottom.js");
var CssBorderTopColor$Ress = require("../property/CssBorderTopColor.js");
var CssBorderTopStyle$Ress = require("../property/CssBorderTopStyle.js");
var CssBorderTopWidth$Ress = require("../property/CssBorderTopWidth.js");
var CssBackgroundColor$Ress = require("../property/CssBackgroundColor.js");
var CssBackgroundImage$Ress = require("../property/CssBackgroundImage.js");
var CssBackgroundStyle$Ress = require("../property/CssBackgroundStyle.js");
var CssBorderLeftColor$Ress = require("../property/CssBorderLeftColor.js");
var CssBorderLeftStyle$Ress = require("../property/CssBorderLeftStyle.js");
var CssBorderLeftWidth$Ress = require("../property/CssBorderLeftWidth.js");
var CssBorderRightColor$Ress = require("../property/CssBorderRightColor.js");
var CssBorderRightStyle$Ress = require("../property/CssBorderRightStyle.js");
var CssBorderRightWidth$Ress = require("../property/CssBorderRightWidth.js");
var CssBorderBottomColor$Ress = require("../property/CssBorderBottomColor.js");
var CssBorderBottomStyle$Ress = require("../property/CssBorderBottomStyle.js");
var CssBorderBottomWidth$Ress = require("../property/CssBorderBottomWidth.js");
var CssPseudoClassHelper$Ress = require("../rule/CssPseudoClassHelper.js");
var CssBackgroundPosition$Ress = require("../property/CssBackgroundPosition.js");
var CssBackgroundAttachment$Ress = require("../property/CssBackgroundAttachment.js");

function Make(Type) {
  var make = CssDeclaration$Ress.make;
  var Declaration = {
    make: make
  };
  var DeclarationFn = CssDeclarationFn$Ress.Make({});
  var map = function (v) {
    return [
            "&" + v[0],
            v[1]
          ];
  };
  var PseudoClass = CssPseudoClass$Ress.Make({
        map: map
      });
  var Rule = CssRule$Ress.Make({});
  var make$1 = CssAtRule$Ress.make;
  var AtRule = {
    make: make$1
  };
  var make$2 = function (declaration) {
    var variant = declaration.NAME;
    if (variant === "FontFace") {
      return CssAtRule$Ress.make(declaration);
    } else if (variant === "DeclarationFn") {
      return Curry._1(DeclarationFn.make, declaration);
    } else if (variant === "Rule") {
      return Curry._1(Rule.make, declaration);
    } else if (variant === "Hover") {
      return Curry._1(PseudoClass.make, declaration);
    } else {
      return CssDeclaration$Ress.make(declaration);
    }
  };
  var AdvancedDeclaration = {
    make: make$2
  };
  var make$3 = function (declarations) {
    return Js_dict.fromArray(Belt_Array.map(declarations, make$2));
  };
  var DeclarationBlocks = {
    make: make$3
  };
  var include = CssRuleHelper$Ress.Make({
        declarationBlocks: make$3
      });
  var include$1 = CssPseudoClassHelper$Ress.Make({
        declarationBlocks: make$3
      });
  return {
          Declaration: Declaration,
          DeclarationFn: DeclarationFn,
          PseudoClass: PseudoClass,
          Rule: Rule,
          AtRule: AtRule,
          AdvancedDeclaration: AdvancedDeclaration,
          DeclarationBlocks: DeclarationBlocks,
          style: make$3,
          Background: undefined,
          BackgroundAttachment: undefined,
          BackgroundColor: undefined,
          BackgroundImage: undefined,
          BackgroundPosition: undefined,
          BackgroundStyle: undefined,
          Border: undefined,
          BorderTop: undefined,
          BorderRight: undefined,
          BorderBottom: undefined,
          BorderLeft: undefined,
          BorderTopColor: undefined,
          BorderRightColor: undefined,
          BorderBottomColor: undefined,
          BorderLeftColor: undefined,
          BorderTopStyle: undefined,
          BorderRightStyle: undefined,
          BorderBottomStyle: undefined,
          BorderLeftStyle: undefined,
          BorderTopWidth: undefined,
          BorderRightWidth: undefined,
          BorderBottomWidth: undefined,
          BorderLeftWidth: undefined,
          BorderColor: undefined,
          BorderStyle: undefined,
          BorderWidth: undefined,
          Clear: undefined,
          Color: undefined,
          Cursor: undefined,
          FontFamily: undefined,
          FontWeight: undefined,
          Margin: undefined,
          MarginTop: undefined,
          MarginRight: undefined,
          MarginBottom: undefined,
          MarginLeft: undefined,
          Padding: undefined,
          PaddingTop: undefined,
          PaddingRight: undefined,
          PaddingBottom: undefined,
          PaddingLeft: undefined,
          $$FontFace: undefined,
          str: CssValueHelper$Ress.str,
          num: CssValueHelper$Ress.num,
          $$int: CssValueHelper$Ress.$$int,
          pct: CssValueHelper$Ress.pct,
          ratio: CssValueHelper$Ress.ratio,
          fr: CssValueHelper$Ress.fr,
          ch: CssValueHelper$Ress.ch,
          em: CssValueHelper$Ress.em,
          ex: CssValueHelper$Ress.ex,
          rem: CssValueHelper$Ress.rem,
          vh: CssValueHelper$Ress.vh,
          vw: CssValueHelper$Ress.vw,
          vmin: CssValueHelper$Ress.vmin,
          vmax: CssValueHelper$Ress.vmax,
          px: CssValueHelper$Ress.px,
          cm: CssValueHelper$Ress.cm,
          mm: CssValueHelper$Ress.mm,
          inch: CssValueHelper$Ress.inch,
          pc: CssValueHelper$Ress.pc,
          pt: CssValueHelper$Ress.pt,
          deg: CssValueHelper$Ress.deg,
          grad: CssValueHelper$Ress.grad,
          rad: CssValueHelper$Ress.rad,
          turn: CssValueHelper$Ress.turn,
          s: CssValueHelper$Ress.s,
          ms: CssValueHelper$Ress.ms,
          hz: CssValueHelper$Ress.hz,
          kHz: CssValueHelper$Ress.kHz,
          dpi: CssValueHelper$Ress.dpi,
          dpcm: CssValueHelper$Ress.dpcm,
          dppx: CssValueHelper$Ress.dppx,
          x: CssValueHelper$Ress.x,
          position2: CssValueHelper$Ress.position2,
          position3: CssValueHelper$Ress.position3,
          position4: CssValueHelper$Ress.position4,
          src: CssValueHelper$Ress.src,
          bgLayer: CssValueHelper$Ress.bgLayer,
          bgSize2: CssValueHelper$Ress.bgSize2,
          hsl: CssValueHelper$Ress.hsl,
          hsla: CssValueHelper$Ress.hsla,
          rgb: CssValueHelper$Ress.rgb,
          rgba: CssValueHelper$Ress.rgba,
          hexColor: CssValueHelper$Ress.hexColor,
          url: CssValueHelper$Ress.url,
          image: CssValueHelper$Ress.image,
          linearColorStop2: CssValueHelper$Ress.linearColorStop2,
          linearColorStop3: CssValueHelper$Ress.linearColorStop3,
          linearGradient: CssValueHelper$Ress.linearGradient,
          linearGradient2: CssValueHelper$Ress.linearGradient2,
          linearGradient3: CssValueHelper$Ress.linearGradient3,
          linearGradient4: CssValueHelper$Ress.linearGradient4,
          repeatingLinearGradient: CssValueHelper$Ress.repeatingLinearGradient,
          repeatingLinearGradient2: CssValueHelper$Ress.repeatingLinearGradient2,
          repeatingLinearGradient3: CssValueHelper$Ress.repeatingLinearGradient3,
          repeatingLinearGradient4: CssValueHelper$Ress.repeatingLinearGradient4,
          radialGradient: CssValueHelper$Ress.radialGradient,
          radialGradient2: CssValueHelper$Ress.radialGradient2,
          radialGradient3: CssValueHelper$Ress.radialGradient3,
          radialGradient4: CssValueHelper$Ress.radialGradient4,
          repeatingRadialGradient: CssValueHelper$Ress.repeatingRadialGradient,
          repeatingRadialGradient2: CssValueHelper$Ress.repeatingRadialGradient2,
          repeatingRadialGradient3: CssValueHelper$Ress.repeatingRadialGradient3,
          repeatingRadialGradient4: CssValueHelper$Ress.repeatingRadialGradient4,
          conicGradient: CssValueHelper$Ress.conicGradient,
          conicGradient2: CssValueHelper$Ress.conicGradient2,
          conicGradient3: CssValueHelper$Ress.conicGradient3,
          conicGradient4: CssValueHelper$Ress.conicGradient4,
          repeatingConicGradient: CssValueHelper$Ress.repeatingConicGradient,
          repeatingConicGradient2: CssValueHelper$Ress.repeatingConicGradient2,
          repeatingConicGradient3: CssValueHelper$Ress.repeatingConicGradient3,
          repeatingConicGradient4: CssValueHelper$Ress.repeatingConicGradient4,
          rule: include.rule,
          fontFace: CssAtRuleHelper$Ress.fontFace,
          hover: include$1.hover,
          background: CssBackground$Ress.DeclarationFnHelper.background,
          background2: CssBackground$Ress.DeclarationFnHelper.background2,
          background3: CssBackground$Ress.DeclarationFnHelper.background3,
          background4: CssBackground$Ress.DeclarationFnHelper.background4,
          backgroundUnion: CssBackground$Ress.DeclarationFnHelper.backgroundUnion,
          backgroundString: CssBackground$Ress.DeclarationFnHelper.backgroundString,
          backgroundFn: CssBackground$Ress.DeclarationFnHelper.backgroundFn,
          backgroundAttachment: CssBackgroundAttachment$Ress.DeclarationFnHelper.backgroundAttachment,
          backgroundAttachment2: CssBackgroundAttachment$Ress.DeclarationFnHelper.backgroundAttachment2,
          backgroundAttachment3: CssBackgroundAttachment$Ress.DeclarationFnHelper.backgroundAttachment3,
          backgroundAttachment4: CssBackgroundAttachment$Ress.DeclarationFnHelper.backgroundAttachment4,
          backgroundAttachmentUnion: CssBackgroundAttachment$Ress.DeclarationFnHelper.backgroundAttachmentUnion,
          backgroundAttachmentString: CssBackgroundAttachment$Ress.DeclarationFnHelper.backgroundAttachmentString,
          backgroundAttachmentFn: CssBackgroundAttachment$Ress.DeclarationFnHelper.backgroundAttachmentFn,
          backgroundColor: CssBackgroundColor$Ress.DeclarationFnHelper.backgroundColor,
          backgroundColorUnion: CssBackgroundColor$Ress.DeclarationFnHelper.backgroundColorUnion,
          backgroundColorString: CssBackgroundColor$Ress.DeclarationFnHelper.backgroundColorString,
          backgroundColorFn: CssBackgroundColor$Ress.DeclarationFnHelper.backgroundColorFn,
          backgroundImage: CssBackgroundImage$Ress.DeclarationFnHelper.backgroundImage,
          backgroundImage2: CssBackgroundImage$Ress.DeclarationFnHelper.backgroundImage2,
          backgroundImage3: CssBackgroundImage$Ress.DeclarationFnHelper.backgroundImage3,
          backgroundImage4: CssBackgroundImage$Ress.DeclarationFnHelper.backgroundImage4,
          backgroundImageUnion: CssBackgroundImage$Ress.DeclarationFnHelper.backgroundImageUnion,
          backgroundImageString: CssBackgroundImage$Ress.DeclarationFnHelper.backgroundImageString,
          backgroundImageFn: CssBackgroundImage$Ress.DeclarationFnHelper.backgroundImageFn,
          backgroundPosition: CssBackgroundPosition$Ress.DeclarationFnHelper.backgroundPosition,
          backgroundPosition2: CssBackgroundPosition$Ress.DeclarationFnHelper.backgroundPosition2,
          backgroundPosition3: CssBackgroundPosition$Ress.DeclarationFnHelper.backgroundPosition3,
          backgroundPosition4: CssBackgroundPosition$Ress.DeclarationFnHelper.backgroundPosition4,
          backgroundPositionUnion: CssBackgroundPosition$Ress.DeclarationFnHelper.backgroundPositionUnion,
          backgroundPositionString: CssBackgroundPosition$Ress.DeclarationFnHelper.backgroundPositionString,
          backgroundPositionFn: CssBackgroundPosition$Ress.DeclarationFnHelper.backgroundPositionFn,
          backgroundStyle: CssBackgroundStyle$Ress.DeclarationFnHelper.backgroundStyle,
          backgroundStyle2: CssBackgroundStyle$Ress.DeclarationFnHelper.backgroundStyle2,
          backgroundStyle3: CssBackgroundStyle$Ress.DeclarationFnHelper.backgroundStyle3,
          backgroundStyle4: CssBackgroundStyle$Ress.DeclarationFnHelper.backgroundStyle4,
          backgroundStyleUnion: CssBackgroundStyle$Ress.DeclarationFnHelper.backgroundStyleUnion,
          backgroundStyleString: CssBackgroundStyle$Ress.DeclarationFnHelper.backgroundStyleString,
          backgroundStyleFn: CssBackgroundStyle$Ress.DeclarationFnHelper.backgroundStyleFn,
          border: CssBorder$Ress.DeclarationFnHelper.border,
          borderUnion: CssBorder$Ress.DeclarationFnHelper.borderUnion,
          borderString: CssBorder$Ress.DeclarationFnHelper.borderString,
          borderFn: CssBorder$Ress.DeclarationFnHelper.borderFn,
          borderTop: CssBorderTop$Ress.DeclarationFnHelper.borderTop,
          borderTopUnion: CssBorderTop$Ress.DeclarationFnHelper.borderTopUnion,
          borderTopString: CssBorderTop$Ress.DeclarationFnHelper.borderTopString,
          borderTopFn: CssBorderTop$Ress.DeclarationFnHelper.borderTopFn,
          borderRight: CssBorderRight$Ress.DeclarationFnHelper.borderRight,
          borderRightUnion: CssBorderRight$Ress.DeclarationFnHelper.borderRightUnion,
          borderRightString: CssBorderRight$Ress.DeclarationFnHelper.borderRightString,
          borderRightFn: CssBorderRight$Ress.DeclarationFnHelper.borderRightFn,
          borderBottom: CssBorderBottom$Ress.DeclarationFnHelper.borderBottom,
          borderBottomUnion: CssBorderBottom$Ress.DeclarationFnHelper.borderBottomUnion,
          borderBottomString: CssBorderBottom$Ress.DeclarationFnHelper.borderBottomString,
          borderBottomFn: CssBorderBottom$Ress.DeclarationFnHelper.borderBottomFn,
          borderLeft: CssBorderLeft$Ress.DeclarationFnHelper.borderLeft,
          borderLeftUnion: CssBorderLeft$Ress.DeclarationFnHelper.borderLeftUnion,
          borderLeftString: CssBorderLeft$Ress.DeclarationFnHelper.borderLeftString,
          borderLeftFn: CssBorderLeft$Ress.DeclarationFnHelper.borderLeftFn,
          borderTopColor: CssBorderTopColor$Ress.DeclarationFnHelper.borderTopColor,
          borderTopColorUnion: CssBorderTopColor$Ress.DeclarationFnHelper.borderTopColorUnion,
          borderTopColorString: CssBorderTopColor$Ress.DeclarationFnHelper.borderTopColorString,
          borderTopColorFn: CssBorderTopColor$Ress.DeclarationFnHelper.borderTopColorFn,
          borderRightColor: CssBorderRightColor$Ress.DeclarationFnHelper.borderRightColor,
          borderRightColorUnion: CssBorderRightColor$Ress.DeclarationFnHelper.borderRightColorUnion,
          borderRightColorString: CssBorderRightColor$Ress.DeclarationFnHelper.borderRightColorString,
          borderRightColorFn: CssBorderRightColor$Ress.DeclarationFnHelper.borderRightColorFn,
          borderBottomColor: CssBorderBottomColor$Ress.DeclarationFnHelper.borderBottomColor,
          borderBottomColorUnion: CssBorderBottomColor$Ress.DeclarationFnHelper.borderBottomColorUnion,
          borderBottomColorString: CssBorderBottomColor$Ress.DeclarationFnHelper.borderBottomColorString,
          borderBottomColorFn: CssBorderBottomColor$Ress.DeclarationFnHelper.borderBottomColorFn,
          borderLeftColor: CssBorderLeftColor$Ress.DeclarationFnHelper.borderLeftColor,
          borderLeftColorUnion: CssBorderLeftColor$Ress.DeclarationFnHelper.borderLeftColorUnion,
          borderLeftColorString: CssBorderLeftColor$Ress.DeclarationFnHelper.borderLeftColorString,
          borderLeftColorFn: CssBorderLeftColor$Ress.DeclarationFnHelper.borderLeftColorFn,
          borderTopStyle: CssBorderTopStyle$Ress.DeclarationFnHelper.borderTopStyle,
          borderTopStyleUnion: CssBorderTopStyle$Ress.DeclarationFnHelper.borderTopStyleUnion,
          borderTopStyleString: CssBorderTopStyle$Ress.DeclarationFnHelper.borderTopStyleString,
          borderTopStyleFn: CssBorderTopStyle$Ress.DeclarationFnHelper.borderTopStyleFn,
          borderRightStyle: CssBorderRightStyle$Ress.DeclarationFnHelper.borderRightStyle,
          borderRightStyleUnion: CssBorderRightStyle$Ress.DeclarationFnHelper.borderRightStyleUnion,
          borderRightStyleString: CssBorderRightStyle$Ress.DeclarationFnHelper.borderRightStyleString,
          borderRightStyleFn: CssBorderRightStyle$Ress.DeclarationFnHelper.borderRightStyleFn,
          borderBottomStyle: CssBorderBottomStyle$Ress.DeclarationFnHelper.borderBottomStyle,
          borderBottomStyleUnion: CssBorderBottomStyle$Ress.DeclarationFnHelper.borderBottomStyleUnion,
          borderBottomStyleString: CssBorderBottomStyle$Ress.DeclarationFnHelper.borderBottomStyleString,
          borderBottomStyleFn: CssBorderBottomStyle$Ress.DeclarationFnHelper.borderBottomStyleFn,
          borderLeftStyle: CssBorderLeftStyle$Ress.DeclarationFnHelper.borderLeftStyle,
          borderLeftStyleUnion: CssBorderLeftStyle$Ress.DeclarationFnHelper.borderLeftStyleUnion,
          borderLeftStyleString: CssBorderLeftStyle$Ress.DeclarationFnHelper.borderLeftStyleString,
          borderLeftStyleFn: CssBorderLeftStyle$Ress.DeclarationFnHelper.borderLeftStyleFn,
          borderTopWidth: CssBorderTopWidth$Ress.DeclarationFnHelper.borderTopWidth,
          borderTopWidthUnion: CssBorderTopWidth$Ress.DeclarationFnHelper.borderTopWidthUnion,
          borderTopWidthString: CssBorderTopWidth$Ress.DeclarationFnHelper.borderTopWidthString,
          borderTopWidthFn: CssBorderTopWidth$Ress.DeclarationFnHelper.borderTopWidthFn,
          borderRightWidth: CssBorderRightWidth$Ress.DeclarationFnHelper.borderRightWidth,
          borderRightWidthUnion: CssBorderRightWidth$Ress.DeclarationFnHelper.borderRightWidthUnion,
          borderRightWidthString: CssBorderRightWidth$Ress.DeclarationFnHelper.borderRightWidthString,
          borderRightWidthFn: CssBorderRightWidth$Ress.DeclarationFnHelper.borderRightWidthFn,
          borderBottomWidth: CssBorderBottomWidth$Ress.DeclarationFnHelper.borderBottomWidth,
          borderBottomWidthUnion: CssBorderBottomWidth$Ress.DeclarationFnHelper.borderBottomWidthUnion,
          borderBottomWidthString: CssBorderBottomWidth$Ress.DeclarationFnHelper.borderBottomWidthString,
          borderBottomWidthFn: CssBorderBottomWidth$Ress.DeclarationFnHelper.borderBottomWidthFn,
          borderLeftWidth: CssBorderLeftWidth$Ress.DeclarationFnHelper.borderLeftWidth,
          borderLeftWidthUnion: CssBorderLeftWidth$Ress.DeclarationFnHelper.borderLeftWidthUnion,
          borderLeftWidthString: CssBorderLeftWidth$Ress.DeclarationFnHelper.borderLeftWidthString,
          borderLeftWidthFn: CssBorderLeftWidth$Ress.DeclarationFnHelper.borderLeftWidthFn,
          borderColor: CssBorderColor$Ress.DeclarationFnHelper.borderColor,
          borderColor2: CssBorderColor$Ress.DeclarationFnHelper.borderColor2,
          borderColor3: CssBorderColor$Ress.DeclarationFnHelper.borderColor3,
          borderColor4: CssBorderColor$Ress.DeclarationFnHelper.borderColor4,
          borderColorUnion: CssBorderColor$Ress.DeclarationFnHelper.borderColorUnion,
          borderColorString: CssBorderColor$Ress.DeclarationFnHelper.borderColorString,
          borderColorFn: CssBorderColor$Ress.DeclarationFnHelper.borderColorFn,
          borderStyle: CssBorderStyle$Ress.DeclarationFnHelper.borderStyle,
          borderStyle2: CssBorderStyle$Ress.DeclarationFnHelper.borderStyle2,
          borderStyle3: CssBorderStyle$Ress.DeclarationFnHelper.borderStyle3,
          borderStyle4: CssBorderStyle$Ress.DeclarationFnHelper.borderStyle4,
          borderStyleUnion: CssBorderStyle$Ress.DeclarationFnHelper.borderStyleUnion,
          borderStyleString: CssBorderStyle$Ress.DeclarationFnHelper.borderStyleString,
          borderStyleFn: CssBorderStyle$Ress.DeclarationFnHelper.borderStyleFn,
          borderWidth: CssBorderWidth$Ress.DeclarationFnHelper.borderWidth,
          borderWidth2: CssBorderWidth$Ress.DeclarationFnHelper.borderWidth2,
          borderWidth3: CssBorderWidth$Ress.DeclarationFnHelper.borderWidth3,
          borderWidth4: CssBorderWidth$Ress.DeclarationFnHelper.borderWidth4,
          borderWidthUnion: CssBorderWidth$Ress.DeclarationFnHelper.borderWidthUnion,
          borderWidthString: CssBorderWidth$Ress.DeclarationFnHelper.borderWidthString,
          borderWidthFn: CssBorderWidth$Ress.DeclarationFnHelper.borderWidthFn,
          clear: CssClear$Ress.DeclarationFnHelper.clear,
          clearFn: CssClear$Ress.DeclarationFnHelper.clearFn,
          color: CssColor$Ress.DeclarationFnHelper.color,
          colorUnion: CssColor$Ress.DeclarationFnHelper.colorUnion,
          colorString: CssColor$Ress.DeclarationFnHelper.colorString,
          colorFn: CssColor$Ress.DeclarationFnHelper.colorFn,
          cursor: CssCursor$Ress.DeclarationFnHelper.cursor,
          cursor1: CssCursor$Ress.DeclarationFnHelper.cursor1,
          cursor2: CssCursor$Ress.DeclarationFnHelper.cursor2,
          cursor3: CssCursor$Ress.DeclarationFnHelper.cursor3,
          cursor4: CssCursor$Ress.DeclarationFnHelper.cursor4,
          cursorUnion: CssCursor$Ress.DeclarationFnHelper.cursorUnion,
          cursorString: CssCursor$Ress.DeclarationFnHelper.cursorString,
          cursorFn: CssCursor$Ress.DeclarationFnHelper.cursorFn,
          fontFamily: CssFontFamily$Ress.DeclarationFnHelper.fontFamily,
          fontFamily2: CssFontFamily$Ress.DeclarationFnHelper.fontFamily2,
          fontFamily3: CssFontFamily$Ress.DeclarationFnHelper.fontFamily3,
          fontFamily4: CssFontFamily$Ress.DeclarationFnHelper.fontFamily4,
          fontFamilyUnion: CssFontFamily$Ress.DeclarationFnHelper.fontFamilyUnion,
          fontFamilyString: CssFontFamily$Ress.DeclarationFnHelper.fontFamilyString,
          fontFamilyFn: CssFontFamily$Ress.DeclarationFnHelper.fontFamilyFn,
          fontWeight: CssFontWeight$Ress.DeclarationFnHelper.fontWeight,
          fontWeightUnion: CssFontWeight$Ress.DeclarationFnHelper.fontWeightUnion,
          fontWeightString: CssFontWeight$Ress.DeclarationFnHelper.fontWeightString,
          fontWeightNumber: CssFontWeight$Ress.DeclarationFnHelper.fontWeightNumber,
          fontWeightFn: CssFontWeight$Ress.DeclarationFnHelper.fontWeightFn,
          margin: CssMargin$Ress.DeclarationFnHelper.margin,
          margin2: CssMargin$Ress.DeclarationFnHelper.margin2,
          margin3: CssMargin$Ress.DeclarationFnHelper.margin3,
          margin4: CssMargin$Ress.DeclarationFnHelper.margin4,
          marginUnion: CssMargin$Ress.DeclarationFnHelper.marginUnion,
          marginString: CssMargin$Ress.DeclarationFnHelper.marginString,
          marginNumber: CssMargin$Ress.DeclarationFnHelper.marginNumber,
          marginFn: CssMargin$Ress.DeclarationFnHelper.marginFn,
          marginTop: CssMarginTop$Ress.DeclarationFnHelper.marginTop,
          marginTopUnion: CssMarginTop$Ress.DeclarationFnHelper.marginTopUnion,
          marginTopString: CssMarginTop$Ress.DeclarationFnHelper.marginTopString,
          marginTopNumber: CssMarginTop$Ress.DeclarationFnHelper.marginTopNumber,
          marginTopFn: CssMarginTop$Ress.DeclarationFnHelper.marginTopFn,
          marginRight: CssMarginRight$Ress.DeclarationFnHelper.marginRight,
          marginRightUnion: CssMarginRight$Ress.DeclarationFnHelper.marginRightUnion,
          marginRightString: CssMarginRight$Ress.DeclarationFnHelper.marginRightString,
          marginRightNumber: CssMarginRight$Ress.DeclarationFnHelper.marginRightNumber,
          marginRightFn: CssMarginRight$Ress.DeclarationFnHelper.marginRightFn,
          marginBottom: CssMarginBottom$Ress.DeclarationFnHelper.marginBottom,
          marginBottomUnion: CssMarginBottom$Ress.DeclarationFnHelper.marginBottomUnion,
          marginBottomString: CssMarginBottom$Ress.DeclarationFnHelper.marginBottomString,
          marginBottomNumber: CssMarginBottom$Ress.DeclarationFnHelper.marginBottomNumber,
          marginBottomFn: CssMarginBottom$Ress.DeclarationFnHelper.marginBottomFn,
          marginLeft: CssMarginLeft$Ress.DeclarationFnHelper.marginLeft,
          marginLeftUnion: CssMarginLeft$Ress.DeclarationFnHelper.marginLeftUnion,
          marginLeftString: CssMarginLeft$Ress.DeclarationFnHelper.marginLeftString,
          marginLeftNumber: CssMarginLeft$Ress.DeclarationFnHelper.marginLeftNumber,
          marginLeftFn: CssMarginLeft$Ress.DeclarationFnHelper.marginLeftFn,
          padding: CssPadding$Ress.DeclarationFnHelper.padding,
          padding2: CssPadding$Ress.DeclarationFnHelper.padding2,
          padding3: CssPadding$Ress.DeclarationFnHelper.padding3,
          padding4: CssPadding$Ress.DeclarationFnHelper.padding4,
          paddingUnion: CssPadding$Ress.DeclarationFnHelper.paddingUnion,
          paddingString: CssPadding$Ress.DeclarationFnHelper.paddingString,
          paddingNumber: CssPadding$Ress.DeclarationFnHelper.paddingNumber,
          paddingFn: CssPadding$Ress.DeclarationFnHelper.paddingFn,
          paddingTop: CssPaddingTop$Ress.DeclarationFnHelper.paddingTop,
          paddingTopUnion: CssPaddingTop$Ress.DeclarationFnHelper.paddingTopUnion,
          paddingTopString: CssPaddingTop$Ress.DeclarationFnHelper.paddingTopString,
          paddingTopNumber: CssPaddingTop$Ress.DeclarationFnHelper.paddingTopNumber,
          paddingTopFn: CssPaddingTop$Ress.DeclarationFnHelper.paddingTopFn,
          paddingRight: CssPaddingRight$Ress.DeclarationFnHelper.paddingRight,
          paddingRightUnion: CssPaddingRight$Ress.DeclarationFnHelper.paddingRightUnion,
          paddingRightString: CssPaddingRight$Ress.DeclarationFnHelper.paddingRightString,
          paddingRightNumber: CssPaddingRight$Ress.DeclarationFnHelper.paddingRightNumber,
          paddingRightFn: CssPaddingRight$Ress.DeclarationFnHelper.paddingRightFn,
          paddingBottom: CssPaddingBottom$Ress.DeclarationFnHelper.paddingBottom,
          paddingBottomUnion: CssPaddingBottom$Ress.DeclarationFnHelper.paddingBottomUnion,
          paddingBottomString: CssPaddingBottom$Ress.DeclarationFnHelper.paddingBottomString,
          paddingBottomNumber: CssPaddingBottom$Ress.DeclarationFnHelper.paddingBottomNumber,
          paddingBottomFn: CssPaddingBottom$Ress.DeclarationFnHelper.paddingBottomFn,
          paddingLeft: CssPaddingLeft$Ress.DeclarationFnHelper.paddingLeft,
          paddingLeftUnion: CssPaddingLeft$Ress.DeclarationFnHelper.paddingLeftUnion,
          paddingLeftString: CssPaddingLeft$Ress.DeclarationFnHelper.paddingLeftString,
          paddingLeftNumber: CssPaddingLeft$Ress.DeclarationFnHelper.paddingLeftNumber,
          paddingLeftFn: CssPaddingLeft$Ress.DeclarationFnHelper.paddingLeftFn
        };
}

exports.Make = Make;
/* CssBorderTop-Ress Not a pure module */
