// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var CssRule$Ress = require("../rule/CssRule.js");
var CssClear$Ress = require("../property/CssClear.js");
var CssColor$Ress = require("../property/CssColor.js");
var CssAtRule$Ress = require("../at_rule/CssAtRule.js");
var CssBorder$Ress = require("../property/CssBorder.js");
var CssCursor$Ress = require("../property/CssCursor.js");
var CssMargin$Ress = require("../property/CssMargin.js");
var CssPadding$Ress = require("../property/CssPadding.js");
var CssBorderTop$Ress = require("../property/CssBorderTop.js");
var CssMarginTop$Ress = require("../property/CssMarginTop.js");
var CssBackground$Ress = require("../property/CssBackground.js");
var CssBorderLeft$Ress = require("../property/CssBorderLeft.js");
var CssFontFamily$Ress = require("../property/CssFontFamily.js");
var CssFontWeight$Ress = require("../property/CssFontWeight.js");
var CssMarginLeft$Ress = require("../property/CssMarginLeft.js");
var CssPaddingTop$Ress = require("../property/CssPaddingTop.js");
var CssRuleHelper$Ress = require("../rule/CssRuleHelper.js");
var CssBorderColor$Ress = require("../property/CssBorderColor.js");
var CssBorderRight$Ress = require("../property/CssBorderRight.js");
var CssBorderStyle$Ress = require("../property/CssBorderStyle.js");
var CssBorderWidth$Ress = require("../property/CssBorderWidth.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssMarginRight$Ress = require("../property/CssMarginRight.js");
var CssPaddingLeft$Ress = require("../property/CssPaddingLeft.js");
var CssPseudoClass$Ress = require("../rule/CssPseudoClass.js");
var CssValueHelper$Ress = require("../value/CssValueHelper.js");
var CssAtRuleHelper$Ress = require("../at_rule/CssAtRuleHelper.js");
var CssBorderBottom$Ress = require("../property/CssBorderBottom.js");
var CssMarginBottom$Ress = require("../property/CssMarginBottom.js");
var CssPaddingRight$Ress = require("../property/CssPaddingRight.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");
var CssPaddingBottom$Ress = require("../property/CssPaddingBottom.js");
var CssBorderTopColor$Ress = require("../property/CssBorderTopColor.js");
var CssBorderTopStyle$Ress = require("../property/CssBorderTopStyle.js");
var CssBorderTopWidth$Ress = require("../property/CssBorderTopWidth.js");
var CssBackgroundColor$Ress = require("../property/CssBackgroundColor.js");
var CssBackgroundImage$Ress = require("../property/CssBackgroundImage.js");
var CssBackgroundStyle$Ress = require("../property/CssBackgroundStyle.js");
var CssBorderLeftColor$Ress = require("../property/CssBorderLeftColor.js");
var CssBorderLeftStyle$Ress = require("../property/CssBorderLeftStyle.js");
var CssBorderLeftWidth$Ress = require("../property/CssBorderLeftWidth.js");
var CssBorderRightColor$Ress = require("../property/CssBorderRightColor.js");
var CssBorderRightStyle$Ress = require("../property/CssBorderRightStyle.js");
var CssBorderRightWidth$Ress = require("../property/CssBorderRightWidth.js");
var CssBorderBottomColor$Ress = require("../property/CssBorderBottomColor.js");
var CssBorderBottomStyle$Ress = require("../property/CssBorderBottomStyle.js");
var CssBorderBottomWidth$Ress = require("../property/CssBorderBottomWidth.js");
var CssPseudoClassHelper$Ress = require("../rule/CssPseudoClassHelper.js");
var CssBackgroundPosition$Ress = require("../property/CssBackgroundPosition.js");
var CssBackgroundAttachment$Ress = require("../property/CssBackgroundAttachment.js");

function Make(Type) {
  var make = CssDeclaration$Ress.make;
  var Declaration = {
    make: make
  };
  var DeclarationFn = CssDeclarationFn$Ress.Make({});
  var map = function (v) {
    return [
            "&" + v[0],
            v[1]
          ];
  };
  var PseudoClass = CssPseudoClass$Ress.Make({
        map: map
      });
  var Rule = CssRule$Ress.Make({});
  var make$1 = CssAtRule$Ress.make;
  var AtRule = {
    make: make$1
  };
  var make$2 = function (declaration) {
    var variant = declaration.NAME;
    if (variant === "FontFace") {
      return CssAtRule$Ress.make(declaration);
    } else if (variant === "DeclarationFn") {
      return Curry._1(DeclarationFn.make, declaration);
    } else if (variant === "Rule") {
      return Curry._1(Rule.make, declaration);
    } else if (variant === "Hover") {
      return Curry._1(PseudoClass.make, declaration);
    } else {
      return CssDeclaration$Ress.make(declaration);
    }
  };
  var AdvancedDeclaration = {
    make: make$2
  };
  var make$3 = function (declarations) {
    return Js_dict.fromArray(Belt_Array.map(declarations, make$2));
  };
  var DeclarationBlocks = {
    make: make$3
  };
  var include = CssBackground$Ress.Make({});
  var DeclarationFnHelper = include.DeclarationFnHelper;
  var Background_value = include.value;
  var Background_value2 = include.value2;
  var Background_value3 = include.value3;
  var Background_value4 = include.value4;
  var Background_DeclarationHelper = include.DeclarationHelper;
  var Background = {
    value: Background_value,
    value2: Background_value2,
    value3: Background_value3,
    value4: Background_value4,
    DeclarationHelper: Background_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper
  };
  var include$1 = CssBackgroundAttachment$Ress.Make({});
  var DeclarationFnHelper$1 = include$1.DeclarationFnHelper;
  var BackgroundAttachment_value = include$1.value;
  var BackgroundAttachment_value2 = include$1.value2;
  var BackgroundAttachment_value3 = include$1.value3;
  var BackgroundAttachment_value4 = include$1.value4;
  var BackgroundAttachment_DeclarationHelper = include$1.DeclarationHelper;
  var BackgroundAttachment = {
    value: BackgroundAttachment_value,
    value2: BackgroundAttachment_value2,
    value3: BackgroundAttachment_value3,
    value4: BackgroundAttachment_value4,
    DeclarationHelper: BackgroundAttachment_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$1
  };
  var include$2 = CssBackgroundColor$Ress.Make({});
  var DeclarationFnHelper$2 = include$2.DeclarationFnHelper;
  var BackgroundColor_value = include$2.value;
  var BackgroundColor_DeclarationHelper = include$2.DeclarationHelper;
  var BackgroundColor = {
    value: BackgroundColor_value,
    DeclarationHelper: BackgroundColor_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$2
  };
  var include$3 = CssBackgroundImage$Ress.Make({});
  var DeclarationFnHelper$3 = include$3.DeclarationFnHelper;
  var BackgroundImage_value = include$3.value;
  var BackgroundImage_value2 = include$3.value2;
  var BackgroundImage_value3 = include$3.value3;
  var BackgroundImage_value4 = include$3.value4;
  var BackgroundImage_DeclarationHelper = include$3.DeclarationHelper;
  var BackgroundImage = {
    value: BackgroundImage_value,
    value2: BackgroundImage_value2,
    value3: BackgroundImage_value3,
    value4: BackgroundImage_value4,
    DeclarationHelper: BackgroundImage_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$3
  };
  var include$4 = CssBackgroundPosition$Ress.Make({});
  var DeclarationFnHelper$4 = include$4.DeclarationFnHelper;
  var BackgroundPosition_value = include$4.value;
  var BackgroundPosition_value2 = include$4.value2;
  var BackgroundPosition_value3 = include$4.value3;
  var BackgroundPosition_value4 = include$4.value4;
  var BackgroundPosition_DeclarationHelper = include$4.DeclarationHelper;
  var BackgroundPosition = {
    value: BackgroundPosition_value,
    value2: BackgroundPosition_value2,
    value3: BackgroundPosition_value3,
    value4: BackgroundPosition_value4,
    DeclarationHelper: BackgroundPosition_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$4
  };
  var include$5 = CssBackgroundStyle$Ress.Make({});
  var DeclarationFnHelper$5 = include$5.DeclarationFnHelper;
  var BackgroundStyle_value = include$5.value;
  var BackgroundStyle_value2 = include$5.value2;
  var BackgroundStyle_value3 = include$5.value3;
  var BackgroundStyle_value4 = include$5.value4;
  var BackgroundStyle_DeclarationHelper = include$5.DeclarationHelper;
  var BackgroundStyle = {
    value: BackgroundStyle_value,
    value2: BackgroundStyle_value2,
    value3: BackgroundStyle_value3,
    value4: BackgroundStyle_value4,
    DeclarationHelper: BackgroundStyle_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$5
  };
  var include$6 = CssBorder$Ress.Make({});
  var DeclarationFnHelper$6 = include$6.DeclarationFnHelper;
  var Border_value = include$6.value;
  var Border_DeclarationHelper = include$6.DeclarationHelper;
  var Border = {
    value: Border_value,
    DeclarationHelper: Border_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$6
  };
  var include$7 = CssBorderTop$Ress.Make({});
  var DeclarationFnHelper$7 = include$7.DeclarationFnHelper;
  var BorderTop_value = include$7.value;
  var BorderTop_DeclarationHelper = include$7.DeclarationHelper;
  var BorderTop = {
    value: BorderTop_value,
    DeclarationHelper: BorderTop_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$7
  };
  var include$8 = CssBorderRight$Ress.Make({});
  var DeclarationFnHelper$8 = include$8.DeclarationFnHelper;
  var BorderRight_value = include$8.value;
  var BorderRight_DeclarationHelper = include$8.DeclarationHelper;
  var BorderRight = {
    value: BorderRight_value,
    DeclarationHelper: BorderRight_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$8
  };
  var include$9 = CssBorderBottom$Ress.Make({});
  var DeclarationFnHelper$9 = include$9.DeclarationFnHelper;
  var BorderBottom_value = include$9.value;
  var BorderBottom_DeclarationHelper = include$9.DeclarationHelper;
  var BorderBottom = {
    value: BorderBottom_value,
    DeclarationHelper: BorderBottom_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$9
  };
  var include$10 = CssBorderLeft$Ress.Make({});
  var DeclarationFnHelper$10 = include$10.DeclarationFnHelper;
  var BorderLeft_value = include$10.value;
  var BorderLeft_DeclarationHelper = include$10.DeclarationHelper;
  var BorderLeft = {
    value: BorderLeft_value,
    DeclarationHelper: BorderLeft_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$10
  };
  var include$11 = CssBorderTopColor$Ress.Make({});
  var DeclarationFnHelper$11 = include$11.DeclarationFnHelper;
  var BorderTopColor_value = include$11.value;
  var BorderTopColor_DeclarationHelper = include$11.DeclarationHelper;
  var BorderTopColor = {
    value: BorderTopColor_value,
    DeclarationHelper: BorderTopColor_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$11
  };
  var include$12 = CssBorderRightColor$Ress.Make({});
  var DeclarationFnHelper$12 = include$12.DeclarationFnHelper;
  var BorderRightColor_value = include$12.value;
  var BorderRightColor_DeclarationHelper = include$12.DeclarationHelper;
  var BorderRightColor = {
    value: BorderRightColor_value,
    DeclarationHelper: BorderRightColor_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$12
  };
  var include$13 = CssBorderBottomColor$Ress.Make({});
  var DeclarationFnHelper$13 = include$13.DeclarationFnHelper;
  var BorderBottomColor_value = include$13.value;
  var BorderBottomColor_DeclarationHelper = include$13.DeclarationHelper;
  var BorderBottomColor = {
    value: BorderBottomColor_value,
    DeclarationHelper: BorderBottomColor_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$13
  };
  var include$14 = CssBorderLeftColor$Ress.Make({});
  var DeclarationFnHelper$14 = include$14.DeclarationFnHelper;
  var BorderLeftColor_value = include$14.value;
  var BorderLeftColor_DeclarationHelper = include$14.DeclarationHelper;
  var BorderLeftColor = {
    value: BorderLeftColor_value,
    DeclarationHelper: BorderLeftColor_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$14
  };
  var include$15 = CssBorderTopStyle$Ress.Make({});
  var DeclarationFnHelper$15 = include$15.DeclarationFnHelper;
  var BorderTopStyle_value = include$15.value;
  var BorderTopStyle_DeclarationHelper = include$15.DeclarationHelper;
  var BorderTopStyle = {
    value: BorderTopStyle_value,
    DeclarationHelper: BorderTopStyle_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$15
  };
  var include$16 = CssBorderRightStyle$Ress.Make({});
  var DeclarationFnHelper$16 = include$16.DeclarationFnHelper;
  var BorderRightStyle_value = include$16.value;
  var BorderRightStyle_DeclarationHelper = include$16.DeclarationHelper;
  var BorderRightStyle = {
    value: BorderRightStyle_value,
    DeclarationHelper: BorderRightStyle_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$16
  };
  var include$17 = CssBorderBottomStyle$Ress.Make({});
  var DeclarationFnHelper$17 = include$17.DeclarationFnHelper;
  var BorderBottomStyle_value = include$17.value;
  var BorderBottomStyle_DeclarationHelper = include$17.DeclarationHelper;
  var BorderBottomStyle = {
    value: BorderBottomStyle_value,
    DeclarationHelper: BorderBottomStyle_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$17
  };
  var include$18 = CssBorderLeftStyle$Ress.Make({});
  var DeclarationFnHelper$18 = include$18.DeclarationFnHelper;
  var BorderLeftStyle_value = include$18.value;
  var BorderLeftStyle_DeclarationHelper = include$18.DeclarationHelper;
  var BorderLeftStyle = {
    value: BorderLeftStyle_value,
    DeclarationHelper: BorderLeftStyle_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$18
  };
  var include$19 = CssBorderTopWidth$Ress.Make({});
  var DeclarationFnHelper$19 = include$19.DeclarationFnHelper;
  var BorderTopWidth_value = include$19.value;
  var BorderTopWidth_DeclarationHelper = include$19.DeclarationHelper;
  var BorderTopWidth = {
    value: BorderTopWidth_value,
    DeclarationHelper: BorderTopWidth_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$19
  };
  var include$20 = CssBorderRightWidth$Ress.Make({});
  var DeclarationFnHelper$20 = include$20.DeclarationFnHelper;
  var BorderRightWidth_value = include$20.value;
  var BorderRightWidth_DeclarationHelper = include$20.DeclarationHelper;
  var BorderRightWidth = {
    value: BorderRightWidth_value,
    DeclarationHelper: BorderRightWidth_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$20
  };
  var include$21 = CssBorderBottomWidth$Ress.Make({});
  var DeclarationFnHelper$21 = include$21.DeclarationFnHelper;
  var BorderBottomWidth_value = include$21.value;
  var BorderBottomWidth_DeclarationHelper = include$21.DeclarationHelper;
  var BorderBottomWidth = {
    value: BorderBottomWidth_value,
    DeclarationHelper: BorderBottomWidth_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$21
  };
  var include$22 = CssBorderLeftWidth$Ress.Make({});
  var DeclarationFnHelper$22 = include$22.DeclarationFnHelper;
  var BorderLeftWidth_value = include$22.value;
  var BorderLeftWidth_DeclarationHelper = include$22.DeclarationHelper;
  var BorderLeftWidth = {
    value: BorderLeftWidth_value,
    DeclarationHelper: BorderLeftWidth_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$22
  };
  var include$23 = CssBorderColor$Ress.Make({});
  var DeclarationFnHelper$23 = include$23.DeclarationFnHelper;
  var BorderColor_value = include$23.value;
  var BorderColor_value2 = include$23.value2;
  var BorderColor_value3 = include$23.value3;
  var BorderColor_value4 = include$23.value4;
  var BorderColor_DeclarationHelper = include$23.DeclarationHelper;
  var BorderColor = {
    value: BorderColor_value,
    value2: BorderColor_value2,
    value3: BorderColor_value3,
    value4: BorderColor_value4,
    DeclarationHelper: BorderColor_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$23
  };
  var include$24 = CssBorderStyle$Ress.Make({});
  var DeclarationFnHelper$24 = include$24.DeclarationFnHelper;
  var BorderStyle_value = include$24.value;
  var BorderStyle_value2 = include$24.value2;
  var BorderStyle_value3 = include$24.value3;
  var BorderStyle_value4 = include$24.value4;
  var BorderStyle_DeclarationConstructor = include$24.DeclarationConstructor;
  var BorderStyle_DeclarationFnConstructor = include$24.DeclarationFnConstructor;
  var BorderStyle_DeclarationHelper = include$24.DeclarationHelper;
  var BorderStyle = {
    value: BorderStyle_value,
    value2: BorderStyle_value2,
    value3: BorderStyle_value3,
    value4: BorderStyle_value4,
    DeclarationConstructor: BorderStyle_DeclarationConstructor,
    DeclarationFnConstructor: BorderStyle_DeclarationFnConstructor,
    DeclarationHelper: BorderStyle_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$24
  };
  var include$25 = CssBorderWidth$Ress.Make({});
  var DeclarationFnHelper$25 = include$25.DeclarationFnHelper;
  var BorderWidth_value = include$25.value;
  var BorderWidth_value2 = include$25.value2;
  var BorderWidth_value3 = include$25.value3;
  var BorderWidth_value4 = include$25.value4;
  var BorderWidth_DeclarationHelper = include$25.DeclarationHelper;
  var BorderWidth = {
    value: BorderWidth_value,
    value2: BorderWidth_value2,
    value3: BorderWidth_value3,
    value4: BorderWidth_value4,
    DeclarationHelper: BorderWidth_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$25
  };
  var include$26 = CssClear$Ress.Make({});
  var DeclarationFnHelper$26 = include$26.DeclarationFnHelper;
  var Clear_value = include$26.value;
  var Clear_DeclarationHelper = include$26.DeclarationHelper;
  var Clear = {
    value: Clear_value,
    DeclarationHelper: Clear_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$26
  };
  var include$27 = CssColor$Ress.Make({});
  var DeclarationFnHelper$27 = include$27.DeclarationFnHelper;
  var Color_value = include$27.value;
  var Color_DeclarationHelper = include$27.DeclarationHelper;
  var Color = {
    value: Color_value,
    DeclarationHelper: Color_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$27
  };
  var include$28 = CssCursor$Ress.Make({});
  var DeclarationFnHelper$28 = include$28.DeclarationFnHelper;
  var Cursor_value = include$28.value;
  var Cursor_value1 = include$28.value1;
  var Cursor_value2 = include$28.value2;
  var Cursor_value3 = include$28.value3;
  var Cursor_value4 = include$28.value4;
  var Cursor_DeclarationHelper = include$28.DeclarationHelper;
  var Cursor = {
    value: Cursor_value,
    value1: Cursor_value1,
    value2: Cursor_value2,
    value3: Cursor_value3,
    value4: Cursor_value4,
    DeclarationHelper: Cursor_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$28
  };
  var include$29 = CssFontFamily$Ress.Make({});
  var DeclarationFnHelper$29 = include$29.DeclarationFnHelper;
  var FontFamily_value = include$29.value;
  var FontFamily_value2 = include$29.value2;
  var FontFamily_value3 = include$29.value3;
  var FontFamily_value4 = include$29.value4;
  var FontFamily_DeclarationHelper = include$29.DeclarationHelper;
  var FontFamily = {
    value: FontFamily_value,
    value2: FontFamily_value2,
    value3: FontFamily_value3,
    value4: FontFamily_value4,
    DeclarationHelper: FontFamily_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$29
  };
  var include$30 = CssFontWeight$Ress.Make({});
  var DeclarationFnHelper$30 = include$30.DeclarationFnHelper;
  var FontWeight_value = include$30.value;
  var FontWeight_DeclarationHelper = include$30.DeclarationHelper;
  var FontWeight = {
    value: FontWeight_value,
    DeclarationHelper: FontWeight_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$30
  };
  var include$31 = CssMargin$Ress.Make({});
  var DeclarationFnHelper$31 = include$31.DeclarationFnHelper;
  var Margin_value = include$31.value;
  var Margin_value2 = include$31.value2;
  var Margin_value3 = include$31.value3;
  var Margin_value4 = include$31.value4;
  var Margin_DeclarationHelper = include$31.DeclarationHelper;
  var Margin = {
    value: Margin_value,
    value2: Margin_value2,
    value3: Margin_value3,
    value4: Margin_value4,
    DeclarationHelper: Margin_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$31
  };
  var include$32 = CssMarginTop$Ress.Make({});
  var DeclarationFnHelper$32 = include$32.DeclarationFnHelper;
  var MarginTop_value = include$32.value;
  var MarginTop_DeclarationHelper = include$32.DeclarationHelper;
  var MarginTop = {
    value: MarginTop_value,
    DeclarationHelper: MarginTop_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$32
  };
  var include$33 = CssMarginRight$Ress.Make({});
  var DeclarationFnHelper$33 = include$33.DeclarationFnHelper;
  var MarginRight_value = include$33.value;
  var MarginRight_DeclarationHelper = include$33.DeclarationHelper;
  var MarginRight = {
    value: MarginRight_value,
    DeclarationHelper: MarginRight_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$33
  };
  var include$34 = CssMarginBottom$Ress.Make({});
  var DeclarationFnHelper$34 = include$34.DeclarationFnHelper;
  var MarginBottom_value = include$34.value;
  var MarginBottom_DeclarationHelper = include$34.DeclarationHelper;
  var MarginBottom = {
    value: MarginBottom_value,
    DeclarationHelper: MarginBottom_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$34
  };
  var include$35 = CssMarginLeft$Ress.Make({});
  var DeclarationFnHelper$35 = include$35.DeclarationFnHelper;
  var MarginLeft_value = include$35.value;
  var MarginLeft_DeclarationHelper = include$35.DeclarationHelper;
  var MarginLeft = {
    value: MarginLeft_value,
    DeclarationHelper: MarginLeft_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$35
  };
  var include$36 = CssPadding$Ress.Make({});
  var DeclarationFnHelper$36 = include$36.DeclarationFnHelper;
  var Padding_value = include$36.value;
  var Padding_value2 = include$36.value2;
  var Padding_value3 = include$36.value3;
  var Padding_value4 = include$36.value4;
  var Padding_DeclarationHelper = include$36.DeclarationHelper;
  var Padding = {
    value: Padding_value,
    value2: Padding_value2,
    value3: Padding_value3,
    value4: Padding_value4,
    DeclarationHelper: Padding_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$36
  };
  var include$37 = CssPaddingTop$Ress.Make({});
  var DeclarationFnHelper$37 = include$37.DeclarationFnHelper;
  var PaddingTop_value = include$37.value;
  var PaddingTop_DeclarationHelper = include$37.DeclarationHelper;
  var PaddingTop = {
    value: PaddingTop_value,
    DeclarationHelper: PaddingTop_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$37
  };
  var include$38 = CssPaddingRight$Ress.Make({});
  var DeclarationFnHelper$38 = include$38.DeclarationFnHelper;
  var PaddingRight_value = include$38.value;
  var PaddingRight_DeclarationHelper = include$38.DeclarationHelper;
  var PaddingRight = {
    value: PaddingRight_value,
    DeclarationHelper: PaddingRight_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$38
  };
  var include$39 = CssPaddingBottom$Ress.Make({});
  var DeclarationFnHelper$39 = include$39.DeclarationFnHelper;
  var PaddingBottom_value = include$39.value;
  var PaddingBottom_DeclarationHelper = include$39.DeclarationHelper;
  var PaddingBottom = {
    value: PaddingBottom_value,
    DeclarationHelper: PaddingBottom_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$39
  };
  var include$40 = CssPaddingLeft$Ress.Make({});
  var DeclarationFnHelper$40 = include$40.DeclarationFnHelper;
  var PaddingLeft_value = include$40.value;
  var PaddingLeft_DeclarationHelper = include$40.DeclarationHelper;
  var PaddingLeft = {
    value: PaddingLeft_value,
    DeclarationHelper: PaddingLeft_DeclarationHelper,
    DeclarationFnHelper: DeclarationFnHelper$40
  };
  var include$41 = CssRuleHelper$Ress.Make({
        declarationBlocks: make$3
      });
  var include$42 = CssPseudoClassHelper$Ress.Make({
        declarationBlocks: make$3
      });
  return {
          Declaration: Declaration,
          DeclarationFn: DeclarationFn,
          PseudoClass: PseudoClass,
          Rule: Rule,
          AtRule: AtRule,
          AdvancedDeclaration: AdvancedDeclaration,
          DeclarationBlocks: DeclarationBlocks,
          style: make$3,
          Background: Background,
          BackgroundAttachment: BackgroundAttachment,
          BackgroundColor: BackgroundColor,
          BackgroundImage: BackgroundImage,
          BackgroundPosition: BackgroundPosition,
          BackgroundStyle: BackgroundStyle,
          Border: Border,
          BorderTop: BorderTop,
          BorderRight: BorderRight,
          BorderBottom: BorderBottom,
          BorderLeft: BorderLeft,
          BorderTopColor: BorderTopColor,
          BorderRightColor: BorderRightColor,
          BorderBottomColor: BorderBottomColor,
          BorderLeftColor: BorderLeftColor,
          BorderTopStyle: BorderTopStyle,
          BorderRightStyle: BorderRightStyle,
          BorderBottomStyle: BorderBottomStyle,
          BorderLeftStyle: BorderLeftStyle,
          BorderTopWidth: BorderTopWidth,
          BorderRightWidth: BorderRightWidth,
          BorderBottomWidth: BorderBottomWidth,
          BorderLeftWidth: BorderLeftWidth,
          BorderColor: BorderColor,
          BorderStyle: BorderStyle,
          BorderWidth: BorderWidth,
          Clear: Clear,
          Color: Color,
          Cursor: Cursor,
          FontFamily: FontFamily,
          FontWeight: FontWeight,
          Margin: Margin,
          MarginTop: MarginTop,
          MarginRight: MarginRight,
          MarginBottom: MarginBottom,
          MarginLeft: MarginLeft,
          Padding: Padding,
          PaddingTop: PaddingTop,
          PaddingRight: PaddingRight,
          PaddingBottom: PaddingBottom,
          PaddingLeft: PaddingLeft,
          $$FontFace: undefined,
          str: CssValueHelper$Ress.str,
          num: CssValueHelper$Ress.num,
          $$int: CssValueHelper$Ress.$$int,
          pct: CssValueHelper$Ress.pct,
          ratio: CssValueHelper$Ress.ratio,
          fr: CssValueHelper$Ress.fr,
          ch: CssValueHelper$Ress.ch,
          em: CssValueHelper$Ress.em,
          ex: CssValueHelper$Ress.ex,
          rem: CssValueHelper$Ress.rem,
          vh: CssValueHelper$Ress.vh,
          vw: CssValueHelper$Ress.vw,
          vmin: CssValueHelper$Ress.vmin,
          vmax: CssValueHelper$Ress.vmax,
          px: CssValueHelper$Ress.px,
          cm: CssValueHelper$Ress.cm,
          mm: CssValueHelper$Ress.mm,
          inch: CssValueHelper$Ress.inch,
          pc: CssValueHelper$Ress.pc,
          pt: CssValueHelper$Ress.pt,
          deg: CssValueHelper$Ress.deg,
          grad: CssValueHelper$Ress.grad,
          rad: CssValueHelper$Ress.rad,
          turn: CssValueHelper$Ress.turn,
          s: CssValueHelper$Ress.s,
          ms: CssValueHelper$Ress.ms,
          hz: CssValueHelper$Ress.hz,
          kHz: CssValueHelper$Ress.kHz,
          dpi: CssValueHelper$Ress.dpi,
          dpcm: CssValueHelper$Ress.dpcm,
          dppx: CssValueHelper$Ress.dppx,
          x: CssValueHelper$Ress.x,
          position2: CssValueHelper$Ress.position2,
          position3: CssValueHelper$Ress.position3,
          position4: CssValueHelper$Ress.position4,
          src: CssValueHelper$Ress.src,
          bgLayer: CssValueHelper$Ress.bgLayer,
          bgSize2: CssValueHelper$Ress.bgSize2,
          hsl: CssValueHelper$Ress.hsl,
          hsla: CssValueHelper$Ress.hsla,
          rgb: CssValueHelper$Ress.rgb,
          rgba: CssValueHelper$Ress.rgba,
          hexColor: CssValueHelper$Ress.hexColor,
          url: CssValueHelper$Ress.url,
          image: CssValueHelper$Ress.image,
          linearColorStop2: CssValueHelper$Ress.linearColorStop2,
          linearColorStop3: CssValueHelper$Ress.linearColorStop3,
          linearGradient: CssValueHelper$Ress.linearGradient,
          linearGradient2: CssValueHelper$Ress.linearGradient2,
          linearGradient3: CssValueHelper$Ress.linearGradient3,
          linearGradient4: CssValueHelper$Ress.linearGradient4,
          repeatingLinearGradient: CssValueHelper$Ress.repeatingLinearGradient,
          repeatingLinearGradient2: CssValueHelper$Ress.repeatingLinearGradient2,
          repeatingLinearGradient3: CssValueHelper$Ress.repeatingLinearGradient3,
          repeatingLinearGradient4: CssValueHelper$Ress.repeatingLinearGradient4,
          radialGradient: CssValueHelper$Ress.radialGradient,
          radialGradient2: CssValueHelper$Ress.radialGradient2,
          radialGradient3: CssValueHelper$Ress.radialGradient3,
          radialGradient4: CssValueHelper$Ress.radialGradient4,
          repeatingRadialGradient: CssValueHelper$Ress.repeatingRadialGradient,
          repeatingRadialGradient2: CssValueHelper$Ress.repeatingRadialGradient2,
          repeatingRadialGradient3: CssValueHelper$Ress.repeatingRadialGradient3,
          repeatingRadialGradient4: CssValueHelper$Ress.repeatingRadialGradient4,
          conicGradient: CssValueHelper$Ress.conicGradient,
          conicGradient2: CssValueHelper$Ress.conicGradient2,
          conicGradient3: CssValueHelper$Ress.conicGradient3,
          conicGradient4: CssValueHelper$Ress.conicGradient4,
          repeatingConicGradient: CssValueHelper$Ress.repeatingConicGradient,
          repeatingConicGradient2: CssValueHelper$Ress.repeatingConicGradient2,
          repeatingConicGradient3: CssValueHelper$Ress.repeatingConicGradient3,
          repeatingConicGradient4: CssValueHelper$Ress.repeatingConicGradient4,
          rule: include$41.rule,
          fontFace: CssAtRuleHelper$Ress.fontFace,
          hover: include$42.hover,
          background: DeclarationFnHelper.background,
          background2: DeclarationFnHelper.background2,
          background3: DeclarationFnHelper.background3,
          background4: DeclarationFnHelper.background4,
          backgroundUnion: DeclarationFnHelper.backgroundUnion,
          backgroundString: DeclarationFnHelper.backgroundString,
          backgroundFn: DeclarationFnHelper.backgroundFn,
          backgroundAttachment: DeclarationFnHelper$1.backgroundAttachment,
          backgroundAttachment2: DeclarationFnHelper$1.backgroundAttachment2,
          backgroundAttachment3: DeclarationFnHelper$1.backgroundAttachment3,
          backgroundAttachment4: DeclarationFnHelper$1.backgroundAttachment4,
          backgroundAttachmentUnion: DeclarationFnHelper$1.backgroundAttachmentUnion,
          backgroundAttachmentString: DeclarationFnHelper$1.backgroundAttachmentString,
          backgroundAttachmentFn: DeclarationFnHelper$1.backgroundAttachmentFn,
          backgroundColor: DeclarationFnHelper$2.backgroundColor,
          backgroundColorUnion: DeclarationFnHelper$2.backgroundColorUnion,
          backgroundColorString: DeclarationFnHelper$2.backgroundColorString,
          backgroundColorFn: DeclarationFnHelper$2.backgroundColorFn,
          backgroundImage: DeclarationFnHelper$3.backgroundImage,
          backgroundImage2: DeclarationFnHelper$3.backgroundImage2,
          backgroundImage3: DeclarationFnHelper$3.backgroundImage3,
          backgroundImage4: DeclarationFnHelper$3.backgroundImage4,
          backgroundImageUnion: DeclarationFnHelper$3.backgroundImageUnion,
          backgroundImageString: DeclarationFnHelper$3.backgroundImageString,
          backgroundImageFn: DeclarationFnHelper$3.backgroundImageFn,
          backgroundPosition: DeclarationFnHelper$4.backgroundPosition,
          backgroundPosition2: DeclarationFnHelper$4.backgroundPosition2,
          backgroundPosition3: DeclarationFnHelper$4.backgroundPosition3,
          backgroundPosition4: DeclarationFnHelper$4.backgroundPosition4,
          backgroundPositionUnion: DeclarationFnHelper$4.backgroundPositionUnion,
          backgroundPositionString: DeclarationFnHelper$4.backgroundPositionString,
          backgroundPositionFn: DeclarationFnHelper$4.backgroundPositionFn,
          backgroundStyle: DeclarationFnHelper$5.backgroundStyle,
          backgroundStyle2: DeclarationFnHelper$5.backgroundStyle2,
          backgroundStyle3: DeclarationFnHelper$5.backgroundStyle3,
          backgroundStyle4: DeclarationFnHelper$5.backgroundStyle4,
          backgroundStyleUnion: DeclarationFnHelper$5.backgroundStyleUnion,
          backgroundStyleString: DeclarationFnHelper$5.backgroundStyleString,
          backgroundStyleFn: DeclarationFnHelper$5.backgroundStyleFn,
          border: DeclarationFnHelper$6.border,
          borderUnion: DeclarationFnHelper$6.borderUnion,
          borderString: DeclarationFnHelper$6.borderString,
          borderFn: DeclarationFnHelper$6.borderFn,
          borderTop: DeclarationFnHelper$7.borderTop,
          borderTopUnion: DeclarationFnHelper$7.borderTopUnion,
          borderTopString: DeclarationFnHelper$7.borderTopString,
          borderTopFn: DeclarationFnHelper$7.borderTopFn,
          borderRight: DeclarationFnHelper$8.borderRight,
          borderRightUnion: DeclarationFnHelper$8.borderRightUnion,
          borderRightString: DeclarationFnHelper$8.borderRightString,
          borderRightFn: DeclarationFnHelper$8.borderRightFn,
          borderBottom: DeclarationFnHelper$9.borderBottom,
          borderBottomUnion: DeclarationFnHelper$9.borderBottomUnion,
          borderBottomString: DeclarationFnHelper$9.borderBottomString,
          borderBottomFn: DeclarationFnHelper$9.borderBottomFn,
          borderLeft: DeclarationFnHelper$10.borderLeft,
          borderLeftUnion: DeclarationFnHelper$10.borderLeftUnion,
          borderLeftString: DeclarationFnHelper$10.borderLeftString,
          borderLeftFn: DeclarationFnHelper$10.borderLeftFn,
          borderTopColor: DeclarationFnHelper$11.borderTopColor,
          borderTopColorUnion: DeclarationFnHelper$11.borderTopColorUnion,
          borderTopColorString: DeclarationFnHelper$11.borderTopColorString,
          borderTopColorFn: DeclarationFnHelper$11.borderTopColorFn,
          borderRightColor: DeclarationFnHelper$12.borderRightColor,
          borderRightColorUnion: DeclarationFnHelper$12.borderRightColorUnion,
          borderRightColorString: DeclarationFnHelper$12.borderRightColorString,
          borderRightColorFn: DeclarationFnHelper$12.borderRightColorFn,
          borderBottomColor: DeclarationFnHelper$13.borderBottomColor,
          borderBottomColorUnion: DeclarationFnHelper$13.borderBottomColorUnion,
          borderBottomColorString: DeclarationFnHelper$13.borderBottomColorString,
          borderBottomColorFn: DeclarationFnHelper$13.borderBottomColorFn,
          borderLeftColor: DeclarationFnHelper$14.borderLeftColor,
          borderLeftColorUnion: DeclarationFnHelper$14.borderLeftColorUnion,
          borderLeftColorString: DeclarationFnHelper$14.borderLeftColorString,
          borderLeftColorFn: DeclarationFnHelper$14.borderLeftColorFn,
          borderTopStyle: DeclarationFnHelper$15.borderTopStyle,
          borderTopStyleUnion: DeclarationFnHelper$15.borderTopStyleUnion,
          borderTopStyleString: DeclarationFnHelper$15.borderTopStyleString,
          borderTopStyleFn: DeclarationFnHelper$15.borderTopStyleFn,
          borderRightStyle: DeclarationFnHelper$16.borderRightStyle,
          borderRightStyleUnion: DeclarationFnHelper$16.borderRightStyleUnion,
          borderRightStyleString: DeclarationFnHelper$16.borderRightStyleString,
          borderRightStyleFn: DeclarationFnHelper$16.borderRightStyleFn,
          borderBottomStyle: DeclarationFnHelper$17.borderBottomStyle,
          borderBottomStyleUnion: DeclarationFnHelper$17.borderBottomStyleUnion,
          borderBottomStyleString: DeclarationFnHelper$17.borderBottomStyleString,
          borderBottomStyleFn: DeclarationFnHelper$17.borderBottomStyleFn,
          borderLeftStyle: DeclarationFnHelper$18.borderLeftStyle,
          borderLeftStyleUnion: DeclarationFnHelper$18.borderLeftStyleUnion,
          borderLeftStyleString: DeclarationFnHelper$18.borderLeftStyleString,
          borderLeftStyleFn: DeclarationFnHelper$18.borderLeftStyleFn,
          borderTopWidth: DeclarationFnHelper$19.borderTopWidth,
          borderTopWidthUnion: DeclarationFnHelper$19.borderTopWidthUnion,
          borderTopWidthString: DeclarationFnHelper$19.borderTopWidthString,
          borderTopWidthFn: DeclarationFnHelper$19.borderTopWidthFn,
          borderRightWidth: DeclarationFnHelper$20.borderRightWidth,
          borderRightWidthUnion: DeclarationFnHelper$20.borderRightWidthUnion,
          borderRightWidthString: DeclarationFnHelper$20.borderRightWidthString,
          borderRightWidthFn: DeclarationFnHelper$20.borderRightWidthFn,
          borderBottomWidth: DeclarationFnHelper$21.borderBottomWidth,
          borderBottomWidthUnion: DeclarationFnHelper$21.borderBottomWidthUnion,
          borderBottomWidthString: DeclarationFnHelper$21.borderBottomWidthString,
          borderBottomWidthFn: DeclarationFnHelper$21.borderBottomWidthFn,
          borderLeftWidth: DeclarationFnHelper$22.borderLeftWidth,
          borderLeftWidthUnion: DeclarationFnHelper$22.borderLeftWidthUnion,
          borderLeftWidthString: DeclarationFnHelper$22.borderLeftWidthString,
          borderLeftWidthFn: DeclarationFnHelper$22.borderLeftWidthFn,
          borderColor: DeclarationFnHelper$23.borderColor,
          borderColor2: DeclarationFnHelper$23.borderColor2,
          borderColor3: DeclarationFnHelper$23.borderColor3,
          borderColor4: DeclarationFnHelper$23.borderColor4,
          borderColorUnion: DeclarationFnHelper$23.borderColorUnion,
          borderColorString: DeclarationFnHelper$23.borderColorString,
          borderColorFn: DeclarationFnHelper$23.borderColorFn,
          borderStyle: DeclarationFnHelper$24.borderStyle,
          borderStyle2: DeclarationFnHelper$24.borderStyle2,
          borderStyle3: DeclarationFnHelper$24.borderStyle3,
          borderStyle4: DeclarationFnHelper$24.borderStyle4,
          borderStyleUnion: DeclarationFnHelper$24.borderStyleUnion,
          borderStyleString: DeclarationFnHelper$24.borderStyleString,
          borderStyleFn: DeclarationFnHelper$24.borderStyleFn,
          borderWidth: DeclarationFnHelper$25.borderWidth,
          borderWidth2: DeclarationFnHelper$25.borderWidth2,
          borderWidth3: DeclarationFnHelper$25.borderWidth3,
          borderWidth4: DeclarationFnHelper$25.borderWidth4,
          borderWidthUnion: DeclarationFnHelper$25.borderWidthUnion,
          borderWidthString: DeclarationFnHelper$25.borderWidthString,
          borderWidthFn: DeclarationFnHelper$25.borderWidthFn,
          clear: DeclarationFnHelper$26.clear,
          clearFn: DeclarationFnHelper$26.clearFn,
          color: DeclarationFnHelper$27.color,
          colorUnion: DeclarationFnHelper$27.colorUnion,
          colorString: DeclarationFnHelper$27.colorString,
          colorFn: DeclarationFnHelper$27.colorFn,
          cursor: DeclarationFnHelper$28.cursor,
          cursor1: DeclarationFnHelper$28.cursor1,
          cursor2: DeclarationFnHelper$28.cursor2,
          cursor3: DeclarationFnHelper$28.cursor3,
          cursor4: DeclarationFnHelper$28.cursor4,
          cursorUnion: DeclarationFnHelper$28.cursorUnion,
          cursorString: DeclarationFnHelper$28.cursorString,
          cursorFn: DeclarationFnHelper$28.cursorFn,
          fontFamily: DeclarationFnHelper$29.fontFamily,
          fontFamily2: DeclarationFnHelper$29.fontFamily2,
          fontFamily3: DeclarationFnHelper$29.fontFamily3,
          fontFamily4: DeclarationFnHelper$29.fontFamily4,
          fontFamilyUnion: DeclarationFnHelper$29.fontFamilyUnion,
          fontFamilyString: DeclarationFnHelper$29.fontFamilyString,
          fontFamilyFn: DeclarationFnHelper$29.fontFamilyFn,
          fontWeight: DeclarationFnHelper$30.fontWeight,
          fontWeightUnion: DeclarationFnHelper$30.fontWeightUnion,
          fontWeightString: DeclarationFnHelper$30.fontWeightString,
          fontWeightNumber: DeclarationFnHelper$30.fontWeightNumber,
          fontWeightFn: DeclarationFnHelper$30.fontWeightFn,
          margin: DeclarationFnHelper$31.margin,
          margin2: DeclarationFnHelper$31.margin2,
          margin3: DeclarationFnHelper$31.margin3,
          margin4: DeclarationFnHelper$31.margin4,
          marginUnion: DeclarationFnHelper$31.marginUnion,
          marginString: DeclarationFnHelper$31.marginString,
          marginNumber: DeclarationFnHelper$31.marginNumber,
          marginFn: DeclarationFnHelper$31.marginFn,
          marginTop: DeclarationFnHelper$32.marginTop,
          marginTopUnion: DeclarationFnHelper$32.marginTopUnion,
          marginTopString: DeclarationFnHelper$32.marginTopString,
          marginTopNumber: DeclarationFnHelper$32.marginTopNumber,
          marginTopFn: DeclarationFnHelper$32.marginTopFn,
          marginRight: DeclarationFnHelper$33.marginRight,
          marginRightUnion: DeclarationFnHelper$33.marginRightUnion,
          marginRightString: DeclarationFnHelper$33.marginRightString,
          marginRightNumber: DeclarationFnHelper$33.marginRightNumber,
          marginRightFn: DeclarationFnHelper$33.marginRightFn,
          marginBottom: DeclarationFnHelper$34.marginBottom,
          marginBottomUnion: DeclarationFnHelper$34.marginBottomUnion,
          marginBottomString: DeclarationFnHelper$34.marginBottomString,
          marginBottomNumber: DeclarationFnHelper$34.marginBottomNumber,
          marginBottomFn: DeclarationFnHelper$34.marginBottomFn,
          marginLeft: DeclarationFnHelper$35.marginLeft,
          marginLeftUnion: DeclarationFnHelper$35.marginLeftUnion,
          marginLeftString: DeclarationFnHelper$35.marginLeftString,
          marginLeftNumber: DeclarationFnHelper$35.marginLeftNumber,
          marginLeftFn: DeclarationFnHelper$35.marginLeftFn,
          padding: DeclarationFnHelper$36.padding,
          padding2: DeclarationFnHelper$36.padding2,
          padding3: DeclarationFnHelper$36.padding3,
          padding4: DeclarationFnHelper$36.padding4,
          paddingUnion: DeclarationFnHelper$36.paddingUnion,
          paddingString: DeclarationFnHelper$36.paddingString,
          paddingNumber: DeclarationFnHelper$36.paddingNumber,
          paddingFn: DeclarationFnHelper$36.paddingFn,
          paddingTop: DeclarationFnHelper$37.paddingTop,
          paddingTopUnion: DeclarationFnHelper$37.paddingTopUnion,
          paddingTopString: DeclarationFnHelper$37.paddingTopString,
          paddingTopNumber: DeclarationFnHelper$37.paddingTopNumber,
          paddingTopFn: DeclarationFnHelper$37.paddingTopFn,
          paddingRight: DeclarationFnHelper$38.paddingRight,
          paddingRightUnion: DeclarationFnHelper$38.paddingRightUnion,
          paddingRightString: DeclarationFnHelper$38.paddingRightString,
          paddingRightNumber: DeclarationFnHelper$38.paddingRightNumber,
          paddingRightFn: DeclarationFnHelper$38.paddingRightFn,
          paddingBottom: DeclarationFnHelper$39.paddingBottom,
          paddingBottomUnion: DeclarationFnHelper$39.paddingBottomUnion,
          paddingBottomString: DeclarationFnHelper$39.paddingBottomString,
          paddingBottomNumber: DeclarationFnHelper$39.paddingBottomNumber,
          paddingBottomFn: DeclarationFnHelper$39.paddingBottomFn,
          paddingLeft: DeclarationFnHelper$40.paddingLeft,
          paddingLeftUnion: DeclarationFnHelper$40.paddingLeftUnion,
          paddingLeftString: DeclarationFnHelper$40.paddingLeftString,
          paddingLeftNumber: DeclarationFnHelper$40.paddingLeftNumber,
          paddingLeftFn: DeclarationFnHelper$40.paddingLeftFn
        };
}

exports.Make = Make;
/* No side effect */
