// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssFontFace$Ress = require("./CssFontFace.js");

function fontFace(properties) {
  return {
          NAME: "FontFace",
          VAL: CssFontFace$Ress.descriptors(properties)
        };
}

exports.fontFace = fontFace;
/* No side effect */
