// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssValue$Ress = require("./CssValue.js");

function hsl(v1, v2, v3) {
  return {
          NAME: "hsl",
          VAL: [
            v1,
            v2,
            v3
          ]
        };
}

function hsla(v1, v2, v3, v4) {
  return {
          NAME: "hsla",
          VAL: [
            v1,
            v2,
            v3,
            CssValue$Ress.num(v4)
          ]
        };
}

function rgb(v1, v2, v3) {
  return {
          NAME: "rgb",
          VAL: [
            CssValue$Ress.num(v1),
            CssValue$Ress.num(v2),
            CssValue$Ress.num(v3)
          ]
        };
}

function rgba(v1, v2, v3, v4) {
  return {
          NAME: "rgba",
          VAL: [
            CssValue$Ress.num(v1),
            CssValue$Ress.num(v2),
            CssValue$Ress.num(v3),
            CssValue$Ress.num(v4)
          ]
        };
}

function rgbX(v) {
  return {
          NAME: "rgbX",
          VAL: v
        };
}

function url(v) {
  return {
          NAME: "url",
          VAL: v
        };
}

function image(dir, color, imageSrcOrColor) {
  return {
          NAME: "image",
          VAL: [
            dir,
            color,
            imageSrcOrColor
          ]
        };
}

function linearColorStop2(c, l) {
  return {
          NAME: "linearColorStop2",
          VAL: [
            c,
            l
          ]
        };
}

function linearColorStop3(c, l1, l2) {
  return {
          NAME: "linearColorStop3",
          VAL: [
            c,
            l1,
            l2
          ]
        };
}

function linearGradient(angle, c) {
  return {
          NAME: "linearGradient",
          VAL: [
            angle,
            c
          ]
        };
}

function linearGradient2(angle, c1, c2) {
  return {
          NAME: "linearGradient2",
          VAL: [
            angle,
            c1,
            c2
          ]
        };
}

function linearGradient3(angle, c1, c2, c3) {
  return {
          NAME: "linearGradient3",
          VAL: [
            angle,
            c1,
            c2,
            c3
          ]
        };
}

function linearGradient4(angle, c1, c2, c3, c4) {
  return {
          NAME: "linearGradient4",
          VAL: [
            angle,
            c1,
            c2,
            c3,
            c4
          ]
        };
}

function repeatingLinearGradient(angle, c) {
  return {
          NAME: "repeatingLinearGradient",
          VAL: [
            angle,
            c
          ]
        };
}

function repeatingLinearGradient2(angle, c1, c2) {
  return {
          NAME: "repeatingLinearGradient2",
          VAL: [
            angle,
            c1,
            c2
          ]
        };
}

function repeatingLinearGradient3(angle, c1, c2, c3) {
  return {
          NAME: "repeatingLinearGradient3",
          VAL: [
            angle,
            c1,
            c2,
            c3
          ]
        };
}

function repeatingLinearGradient4(angle, c1, c2, c3, c4) {
  return {
          NAME: "repeatingLinearGradient4",
          VAL: [
            angle,
            c1,
            c2,
            c3,
            c4
          ]
        };
}

function radialGradient(position, endingShape, size, c) {
  return {
          NAME: "radialGradient",
          VAL: [
            position,
            endingShape,
            size,
            c
          ]
        };
}

function radialGradient2(position, endingShape, size, c1, c2) {
  return {
          NAME: "radialGradient2",
          VAL: [
            position,
            endingShape,
            size,
            c1,
            c2
          ]
        };
}

function radialGradient3(position, endingShape, size, c1, c2, c3) {
  return {
          NAME: "radialGradient3",
          VAL: [
            position,
            endingShape,
            size,
            c1,
            c2,
            c3
          ]
        };
}

function radialGradient4(position, endingShape, size, c1, c2, c3, c4) {
  return {
          NAME: "radialGradient4",
          VAL: [
            position,
            endingShape,
            size,
            c1,
            c2,
            c3,
            c4
          ]
        };
}

function repeatingRadialGradient(position, endingShape, size, c) {
  return {
          NAME: "repeatingRadialGradient",
          VAL: [
            position,
            endingShape,
            size,
            c
          ]
        };
}

function repeatingRadialGradient2(position, endingShape, size, c1, c2) {
  return {
          NAME: "repeatingRadialGradient2",
          VAL: [
            position,
            endingShape,
            size,
            c1,
            c2
          ]
        };
}

function repeatingRadialGradient3(position, endingShape, size, c1, c2, c3) {
  return {
          NAME: "repeatingRadialGradient3",
          VAL: [
            position,
            endingShape,
            size,
            c1,
            c2,
            c3
          ]
        };
}

function repeatingRadialGradient4(position, endingShape, size, c1, c2, c3, c4) {
  return {
          NAME: "repeatingRadialGradient4",
          VAL: [
            position,
            endingShape,
            size,
            c1,
            c2,
            c3,
            c4
          ]
        };
}

function conicGradient(angle, position, c) {
  return {
          NAME: "conicGradient",
          VAL: [
            angle,
            position,
            c
          ]
        };
}

function conicGradient2(angle, position, c1, c2) {
  return {
          NAME: "conicGradient2",
          VAL: [
            angle,
            position,
            c1,
            c2
          ]
        };
}

function conicGradient3(angle, position, c1, c2, c3) {
  return {
          NAME: "conicGradient3",
          VAL: [
            angle,
            position,
            c1,
            c2,
            c3
          ]
        };
}

function conicGradient4(angle, position, c1, c2, c3, c4) {
  return {
          NAME: "conicGradient4",
          VAL: [
            angle,
            position,
            c1,
            c2,
            c3,
            c4
          ]
        };
}

function repeatingConicGradient(angle, position, c) {
  return {
          NAME: "repeatingConicGradient",
          VAL: [
            angle,
            position,
            c
          ]
        };
}

function repeatingConicGradient2(angle, position, c1, c2) {
  return {
          NAME: "repeatingConicGradient2",
          VAL: [
            angle,
            position,
            c1,
            c2
          ]
        };
}

function repeatingConicGradient3(angle, position, c1, c2, c3) {
  return {
          NAME: "repeatingConicGradient3",
          VAL: [
            angle,
            position,
            c1,
            c2,
            c3
          ]
        };
}

function repeatingConicGradient4(angle, position, c1, c2, c3, c4) {
  return {
          NAME: "repeatingConicGradient4",
          VAL: [
            angle,
            position,
            c1,
            c2,
            c3,
            c4
          ]
        };
}

exports.hsl = hsl;
exports.hsla = hsla;
exports.rgb = rgb;
exports.rgba = rgba;
exports.rgbX = rgbX;
exports.url = url;
exports.image = image;
exports.linearColorStop2 = linearColorStop2;
exports.linearColorStop3 = linearColorStop3;
exports.linearGradient = linearGradient;
exports.linearGradient2 = linearGradient2;
exports.linearGradient3 = linearGradient3;
exports.linearGradient4 = linearGradient4;
exports.repeatingLinearGradient = repeatingLinearGradient;
exports.repeatingLinearGradient2 = repeatingLinearGradient2;
exports.repeatingLinearGradient3 = repeatingLinearGradient3;
exports.repeatingLinearGradient4 = repeatingLinearGradient4;
exports.radialGradient = radialGradient;
exports.radialGradient2 = radialGradient2;
exports.radialGradient3 = radialGradient3;
exports.radialGradient4 = radialGradient4;
exports.repeatingRadialGradient = repeatingRadialGradient;
exports.repeatingRadialGradient2 = repeatingRadialGradient2;
exports.repeatingRadialGradient3 = repeatingRadialGradient3;
exports.repeatingRadialGradient4 = repeatingRadialGradient4;
exports.conicGradient = conicGradient;
exports.conicGradient2 = conicGradient2;
exports.conicGradient3 = conicGradient3;
exports.conicGradient4 = conicGradient4;
exports.repeatingConicGradient = repeatingConicGradient;
exports.repeatingConicGradient2 = repeatingConicGradient2;
exports.repeatingConicGradient3 = repeatingConicGradient3;
exports.repeatingConicGradient4 = repeatingConicGradient4;
/* No side effect */
