// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssPropertyValue$Ress = require("./CssPropertyValue.js");

function property(name, value) {
  return {
          TAG: /* Property */0,
          _0: name,
          _1: value
        };
}

function propertyNumber(name, value) {
  return {
          TAG: /* Property */0,
          _0: name,
          _1: value
        };
}

function propertyInteger(name, value) {
  return {
          TAG: /* Property */0,
          _0: name,
          _1: value
        };
}

function border(width, color, style) {
  return {
          TAG: /* Border */1,
          _0: CssPropertyValue$Ress.border(width, color, style)
        };
}

function borderString(v) {
  return {
          TAG: /* Border */1,
          _0: v
        };
}

function borderTop(width, color, style) {
  return {
          TAG: /* BorderTop */2,
          _0: CssPropertyValue$Ress.border(width, color, style)
        };
}

function borderTopString(v) {
  return {
          TAG: /* BorderTop */2,
          _0: v
        };
}

function borderLeft(width, color, style) {
  return {
          TAG: /* BorderLeft */5,
          _0: CssPropertyValue$Ress.border(width, color, style)
        };
}

function borderLeftString(v) {
  return {
          TAG: /* BorderLeft */5,
          _0: v
        };
}

function borderRight(width, color, style) {
  return {
          TAG: /* BorderRight */3,
          _0: CssPropertyValue$Ress.border(width, color, style)
        };
}

function borderRightString(v) {
  return {
          TAG: /* BorderRight */3,
          _0: v
        };
}

function borderBottom(width, color, style) {
  return {
          TAG: /* BorderBottom */4,
          _0: CssPropertyValue$Ress.border(width, color, style)
        };
}

function borderBottomString(v) {
  return {
          TAG: /* BorderBottom */4,
          _0: v
        };
}

function borderColor(v) {
  return {
          TAG: /* BorderColor */16,
          _0: CssPropertyValue$Ress.borderColor(v)
        };
}

function borderColor2(tb, lr) {
  return {
          TAG: /* BorderColor */16,
          _0: CssPropertyValue$Ress.borderColor2(tb, lr)
        };
}

function borderColor3(top, lr, bottom) {
  return {
          TAG: /* BorderColor */16,
          _0: CssPropertyValue$Ress.borderColor3(top, lr, bottom)
        };
}

function borderColor4(top, right, bottom, left) {
  return {
          TAG: /* BorderColor */16,
          _0: CssPropertyValue$Ress.borderColor4(top, right, bottom, left)
        };
}

function borderColorString(v) {
  return {
          TAG: /* BorderColor */16,
          _0: v
        };
}

function borderTopColor(v) {
  return {
          TAG: /* BorderTopColor */17,
          _0: CssPropertyValue$Ress.borderTopColor(v)
        };
}

function borderTopColorString(v) {
  return {
          TAG: /* BorderTopColor */17,
          _0: v
        };
}

function borderRightColor(v) {
  return {
          TAG: /* BorderRightColor */18,
          _0: CssPropertyValue$Ress.borderRightColor(v)
        };
}

function borderRightColorString(v) {
  return {
          TAG: /* BorderRightColor */18,
          _0: v
        };
}

function borderBottomColor(v) {
  return {
          TAG: /* BorderBottomColor */19,
          _0: CssPropertyValue$Ress.borderBottomColor(v)
        };
}

function borderBottomColorString(v) {
  return {
          TAG: /* BorderBottomColor */19,
          _0: v
        };
}

function borderLeftColor(v) {
  return {
          TAG: /* BorderLeftColor */20,
          _0: CssPropertyValue$Ress.borderLeftColor(v)
        };
}

function borderLeftColorString(v) {
  return {
          TAG: /* BorderLeftColor */20,
          _0: v
        };
}

function borderStyle(v) {
  return {
          TAG: /* BorderStyle */6,
          _0: CssPropertyValue$Ress.borderStyle(v)
        };
}

function borderStyle2(tb, lr) {
  return {
          TAG: /* BorderStyle */6,
          _0: CssPropertyValue$Ress.borderStyle2(tb, lr)
        };
}

function borderStyle3(top, lr, bottom) {
  return {
          TAG: /* BorderStyle */6,
          _0: CssPropertyValue$Ress.borderStyle3(top, lr, bottom)
        };
}

function borderStyle4(top, right, bottom, left) {
  return {
          TAG: /* BorderStyle */6,
          _0: CssPropertyValue$Ress.borderStyle4(top, right, bottom, left)
        };
}

function borderStyleString(v) {
  return {
          TAG: /* BorderStyle */6,
          _0: v
        };
}

function borderTopStyle(v) {
  return {
          TAG: /* BorderTopStyle */7,
          _0: CssPropertyValue$Ress.borderTopStyle(v)
        };
}

function borderTopStyleString(v) {
  return {
          TAG: /* BorderTopStyle */7,
          _0: v
        };
}

function borderRightStyle(v) {
  return {
          TAG: /* BorderRightStyle */8,
          _0: CssPropertyValue$Ress.borderRightStyle(v)
        };
}

function borderRightStyleString(v) {
  return {
          TAG: /* BorderRightStyle */8,
          _0: v
        };
}

function borderBottomStyle(v) {
  return {
          TAG: /* BorderBottomStyle */9,
          _0: CssPropertyValue$Ress.borderBottomStyle(v)
        };
}

function borderBottomStyleString(v) {
  return {
          TAG: /* BorderBottomStyle */9,
          _0: v
        };
}

function borderLeftStyle(v) {
  return {
          TAG: /* BorderLeftStyle */10,
          _0: CssPropertyValue$Ress.borderLeftStyle(v)
        };
}

function borderLeftStyleString(v) {
  return {
          TAG: /* BorderLeftStyle */10,
          _0: v
        };
}

function borderWidth(v) {
  return {
          TAG: /* BorderWidth */11,
          _0: CssPropertyValue$Ress.borderWidth(v)
        };
}

function borderWidth2(tb, lr) {
  return {
          TAG: /* BorderWidth */11,
          _0: CssPropertyValue$Ress.borderWidth2(tb, lr)
        };
}

function borderWidth3(top, lr, bottom) {
  return {
          TAG: /* BorderWidth */11,
          _0: CssPropertyValue$Ress.borderWidth3(top, lr, bottom)
        };
}

function borderWidth4(top, right, bottom, left) {
  return {
          TAG: /* BorderWidth */11,
          _0: CssPropertyValue$Ress.borderWidth4(top, right, bottom, left)
        };
}

function borderWidthString(v) {
  return {
          TAG: /* BorderWidth */11,
          _0: v
        };
}

function borderTopWidth(v) {
  return {
          TAG: /* BorderTopWidth */12,
          _0: CssPropertyValue$Ress.borderTopWidth(v)
        };
}

function borderTopWidthString(v) {
  return {
          TAG: /* BorderTopWidth */12,
          _0: v
        };
}

function borderRightWidth(v) {
  return {
          TAG: /* BorderRightWidth */13,
          _0: CssPropertyValue$Ress.borderRightWidth(v)
        };
}

function borderRightWidthString(v) {
  return {
          TAG: /* BorderRightWidth */13,
          _0: v
        };
}

function borderBottomWidth(v) {
  return {
          TAG: /* BorderBottomWidth */14,
          _0: CssPropertyValue$Ress.borderBottomWidth(v)
        };
}

function borderBottomWidthString(v) {
  return {
          TAG: /* BorderBottomWidth */14,
          _0: v
        };
}

function borderLeftWidth(v) {
  return {
          TAG: /* BorderLeftWidth */15,
          _0: CssPropertyValue$Ress.borderLeftWidth(v)
        };
}

function borderLeftWidthString(v) {
  return {
          TAG: /* BorderLeftWidth */15,
          _0: v
        };
}

function background(color, position, size, repeat, attachment, origin, clip, imageOrColor) {
  return {
          TAG: /* Background */21,
          _0: CssPropertyValue$Ress.background(color, position, size, repeat, attachment, origin, clip, imageOrColor)
        };
}

function background2(l1, l2) {
  return {
          TAG: /* Background */21,
          _0: CssPropertyValue$Ress.background2(l1, l2)
        };
}

function background3(l1, l2, l3) {
  return {
          TAG: /* Background */21,
          _0: CssPropertyValue$Ress.background3(l1, l2, l3)
        };
}

function background4(l1, l2, l3, l4) {
  return {
          TAG: /* Background */21,
          _0: CssPropertyValue$Ress.background4(l1, l2, l3, l4)
        };
}

function backgroundString(v) {
  return {
          TAG: /* Background */21,
          _0: v
        };
}

function backgroundAttachment(v) {
  return {
          TAG: /* BackgroundAttachment */22,
          _0: CssPropertyValue$Ress.backgroundAttachment(v)
        };
}

function backgroundAttachment2(v1, v2) {
  return {
          TAG: /* BackgroundAttachment */22,
          _0: CssPropertyValue$Ress.backgroundAttachment2(v1, v2)
        };
}

function backgroundAttachment3(v1, v2, v3) {
  return {
          TAG: /* BackgroundAttachment */22,
          _0: CssPropertyValue$Ress.backgroundAttachment3(v1, v2, v3)
        };
}

function backgroundAttachment4(v1, v2, v3, v4) {
  return {
          TAG: /* BackgroundAttachment */22,
          _0: CssPropertyValue$Ress.backgroundAttachment4(v1, v2, v3, v4)
        };
}

function backgroundAttachmentString(v) {
  return {
          TAG: /* BackgroundAttachment */22,
          _0: v
        };
}

function backgroundColor(v) {
  return {
          TAG: /* BackgroundColor */23,
          _0: CssPropertyValue$Ress.backgroundColor(v)
        };
}

function backgroundColorString(v) {
  return {
          TAG: /* BackgroundColor */23,
          _0: v
        };
}

function backgroundImage(v) {
  return {
          TAG: /* BackgroundImage */24,
          _0: CssPropertyValue$Ress.backgroundImage(v)
        };
}

function backgroundImage2(v1, v2) {
  return {
          TAG: /* BackgroundImage */24,
          _0: CssPropertyValue$Ress.backgroundImage2(v1, v2)
        };
}

function backgroundImage3(v1, v2, v3) {
  return {
          TAG: /* BackgroundImage */24,
          _0: CssPropertyValue$Ress.backgroundImage3(v1, v2, v3)
        };
}

function backgroundImage4(v1, v2, v3, v4) {
  return {
          TAG: /* BackgroundImage */24,
          _0: CssPropertyValue$Ress.backgroundImage4(v1, v2, v3, v4)
        };
}

function backgroundImageString(v) {
  return {
          TAG: /* BackgroundImage */24,
          _0: v
        };
}

function backgroundPosition(v) {
  return {
          TAG: /* BackgroundPosition */25,
          _0: CssPropertyValue$Ress.backgroundPosition(v)
        };
}

function backgroundPosition2(v1, v2) {
  return {
          TAG: /* BackgroundPosition */25,
          _0: CssPropertyValue$Ress.backgroundPosition2(v1, v2)
        };
}

function backgroundPosition3(v1, v2, v3) {
  return {
          TAG: /* BackgroundPosition */25,
          _0: CssPropertyValue$Ress.backgroundPosition3(v1, v2, v3)
        };
}

function backgroundPosition4(v1, v2, v3, v4) {
  return {
          TAG: /* BackgroundPosition */25,
          _0: CssPropertyValue$Ress.backgroundPosition4(v1, v2, v3, v4)
        };
}

function backgroundPositionString(v) {
  return {
          TAG: /* BackgroundPosition */25,
          _0: v
        };
}

function backgroundStyle(v) {
  return {
          TAG: /* BackgroundStyle */26,
          _0: CssPropertyValue$Ress.backgroundStyle(v)
        };
}

function backgroundStyle2(v1, v2) {
  return {
          TAG: /* BackgroundStyle */26,
          _0: CssPropertyValue$Ress.backgroundStyle2(v1, v2)
        };
}

function backgroundStyle3(v1, v2, v3) {
  return {
          TAG: /* BackgroundStyle */26,
          _0: CssPropertyValue$Ress.backgroundStyle3(v1, v2, v3)
        };
}

function backgroundStyle4(v1, v2, v3, v4) {
  return {
          TAG: /* BackgroundStyle */26,
          _0: CssPropertyValue$Ress.backgroundStyle4(v1, v2, v3, v4)
        };
}

function backgroundStyleString(v) {
  return {
          TAG: /* BackgroundStyle */26,
          _0: v
        };
}

function margin(v) {
  return {
          TAG: /* Margin */27,
          _0: CssPropertyValue$Ress.margin(v)
        };
}

function margin2(tb, lr) {
  return {
          TAG: /* Margin */27,
          _0: CssPropertyValue$Ress.margin2(tb, lr)
        };
}

function margin3(top, lr, bottom) {
  return {
          TAG: /* Margin */27,
          _0: CssPropertyValue$Ress.margin3(top, lr, bottom)
        };
}

function margin4(top, right, bottom, left) {
  return {
          TAG: /* Margin */27,
          _0: CssPropertyValue$Ress.margin4(top, right, bottom, left)
        };
}

function marginString(v) {
  return {
          TAG: /* Margin */27,
          _0: v
        };
}

function marginNumber(v) {
  return {
          TAG: /* Margin */27,
          _0: v
        };
}

function marginTop(v) {
  return {
          TAG: /* MarginTop */28,
          _0: CssPropertyValue$Ress.marginTop(v)
        };
}

function marginTopString(v) {
  return {
          TAG: /* MarginTop */28,
          _0: v
        };
}

function marginTopNumber(v) {
  return {
          TAG: /* MarginTop */28,
          _0: v
        };
}

function marginRight(v) {
  return {
          TAG: /* MarginRight */29,
          _0: CssPropertyValue$Ress.marginRight(v)
        };
}

function marginRightString(v) {
  return {
          TAG: /* MarginRight */29,
          _0: v
        };
}

function marginRightNumber(v) {
  return {
          TAG: /* MarginRight */29,
          _0: v
        };
}

function marginBottom(v) {
  return {
          TAG: /* MarginBottom */30,
          _0: CssPropertyValue$Ress.marginBottom(v)
        };
}

function marginBottomString(v) {
  return {
          TAG: /* MarginBottom */30,
          _0: v
        };
}

function marginBottomNumber(v) {
  return {
          TAG: /* MarginBottom */30,
          _0: v
        };
}

function marginLeft(v) {
  return {
          TAG: /* MarginLeft */31,
          _0: CssPropertyValue$Ress.marginLeft(v)
        };
}

function marginLeftString(v) {
  return {
          TAG: /* MarginLeft */31,
          _0: v
        };
}

function marginLeftNumber(v) {
  return {
          TAG: /* MarginLeft */31,
          _0: v
        };
}

function padding(v) {
  return {
          TAG: /* Padding */32,
          _0: CssPropertyValue$Ress.padding(v)
        };
}

function padding2(tb, lr) {
  return {
          TAG: /* Padding */32,
          _0: CssPropertyValue$Ress.padding2(tb, lr)
        };
}

function padding3(top, lr, bottom) {
  return {
          TAG: /* Padding */32,
          _0: CssPropertyValue$Ress.padding3(top, lr, bottom)
        };
}

function padding4(top, right, bottom, left) {
  return {
          TAG: /* Padding */32,
          _0: CssPropertyValue$Ress.padding4(top, right, bottom, left)
        };
}

function paddingString(v) {
  return {
          TAG: /* Padding */32,
          _0: v
        };
}

function paddingNumber(v) {
  return {
          TAG: /* Padding */32,
          _0: v
        };
}

function paddingTop(v) {
  return {
          TAG: /* PaddingTop */33,
          _0: CssPropertyValue$Ress.paddingTop(v)
        };
}

function paddingTopString(v) {
  return {
          TAG: /* PaddingTop */33,
          _0: v
        };
}

function paddingTopNumber(v) {
  return {
          TAG: /* PaddingTop */33,
          _0: v
        };
}

function paddingRight(v) {
  return {
          TAG: /* PaddingRight */35,
          _0: CssPropertyValue$Ress.paddingRight(v)
        };
}

function paddingRightString(v) {
  return {
          TAG: /* PaddingRight */35,
          _0: v
        };
}

function paddingRightNumber(v) {
  return {
          TAG: /* PaddingRight */35,
          _0: v
        };
}

function paddingBottom(v) {
  return {
          TAG: /* PaddingBottom */34,
          _0: CssPropertyValue$Ress.paddingBottom(v)
        };
}

function paddingBottomString(v) {
  return {
          TAG: /* PaddingBottom */34,
          _0: v
        };
}

function paddingBottomNumber(v) {
  return {
          TAG: /* PaddingBottom */34,
          _0: v
        };
}

function paddingLeft(v) {
  return {
          TAG: /* PaddingLeft */36,
          _0: CssPropertyValue$Ress.paddingLeft(v)
        };
}

function paddingLeftString(v) {
  return {
          TAG: /* PaddingLeft */36,
          _0: v
        };
}

function paddingLeftNumber(v) {
  return {
          TAG: /* PaddingLeft */36,
          _0: v
        };
}

function clear(v) {
  return {
          TAG: /* Clear */38,
          _0: CssPropertyValue$Ress.clear(v)
        };
}

function color(v) {
  return {
          TAG: /* Color */37,
          _0: CssPropertyValue$Ress.color(v)
        };
}

function colorString(v) {
  return {
          TAG: /* Color */37,
          _0: v
        };
}

function cursor(v) {
  return {
          TAG: /* Cursor */39,
          _0: CssPropertyValue$Ress.cursor(v)
        };
}

function cursor1(i, k) {
  return {
          TAG: /* Cursor */39,
          _0: CssPropertyValue$Ress.cursor1(i, k)
        };
}

function cursor2(i1, i2, k) {
  return {
          TAG: /* Cursor */39,
          _0: CssPropertyValue$Ress.cursor2(i1, i2, k)
        };
}

function cursor3(i1, i2, i3, k) {
  return {
          TAG: /* Cursor */39,
          _0: CssPropertyValue$Ress.cursor3(i1, i2, i3, k)
        };
}

function cursor4(i1, i2, i3, i4, k) {
  return {
          TAG: /* Cursor */39,
          _0: CssPropertyValue$Ress.cursor4(i1, i2, i3, i4, k)
        };
}

function cursorString(v) {
  return {
          TAG: /* Cursor */39,
          _0: v
        };
}

exports.property = property;
exports.propertyNumber = propertyNumber;
exports.propertyInteger = propertyInteger;
exports.border = border;
exports.borderString = borderString;
exports.borderTop = borderTop;
exports.borderTopString = borderTopString;
exports.borderLeft = borderLeft;
exports.borderLeftString = borderLeftString;
exports.borderRight = borderRight;
exports.borderRightString = borderRightString;
exports.borderBottom = borderBottom;
exports.borderBottomString = borderBottomString;
exports.borderColor = borderColor;
exports.borderColor2 = borderColor2;
exports.borderColor3 = borderColor3;
exports.borderColor4 = borderColor4;
exports.borderColorString = borderColorString;
exports.borderTopColor = borderTopColor;
exports.borderTopColorString = borderTopColorString;
exports.borderRightColor = borderRightColor;
exports.borderRightColorString = borderRightColorString;
exports.borderBottomColor = borderBottomColor;
exports.borderBottomColorString = borderBottomColorString;
exports.borderLeftColor = borderLeftColor;
exports.borderLeftColorString = borderLeftColorString;
exports.borderStyle = borderStyle;
exports.borderStyle2 = borderStyle2;
exports.borderStyle3 = borderStyle3;
exports.borderStyle4 = borderStyle4;
exports.borderStyleString = borderStyleString;
exports.borderTopStyle = borderTopStyle;
exports.borderTopStyleString = borderTopStyleString;
exports.borderRightStyle = borderRightStyle;
exports.borderRightStyleString = borderRightStyleString;
exports.borderBottomStyle = borderBottomStyle;
exports.borderBottomStyleString = borderBottomStyleString;
exports.borderLeftStyle = borderLeftStyle;
exports.borderLeftStyleString = borderLeftStyleString;
exports.borderWidth = borderWidth;
exports.borderWidth2 = borderWidth2;
exports.borderWidth3 = borderWidth3;
exports.borderWidth4 = borderWidth4;
exports.borderWidthString = borderWidthString;
exports.borderTopWidth = borderTopWidth;
exports.borderTopWidthString = borderTopWidthString;
exports.borderRightWidth = borderRightWidth;
exports.borderRightWidthString = borderRightWidthString;
exports.borderBottomWidth = borderBottomWidth;
exports.borderBottomWidthString = borderBottomWidthString;
exports.borderLeftWidth = borderLeftWidth;
exports.borderLeftWidthString = borderLeftWidthString;
exports.background = background;
exports.backgroundString = backgroundString;
exports.background2 = background2;
exports.background3 = background3;
exports.background4 = background4;
exports.backgroundAttachment = backgroundAttachment;
exports.backgroundAttachment2 = backgroundAttachment2;
exports.backgroundAttachment3 = backgroundAttachment3;
exports.backgroundAttachment4 = backgroundAttachment4;
exports.backgroundAttachmentString = backgroundAttachmentString;
exports.backgroundColor = backgroundColor;
exports.backgroundColorString = backgroundColorString;
exports.backgroundImage = backgroundImage;
exports.backgroundImage2 = backgroundImage2;
exports.backgroundImage3 = backgroundImage3;
exports.backgroundImage4 = backgroundImage4;
exports.backgroundImageString = backgroundImageString;
exports.backgroundPosition = backgroundPosition;
exports.backgroundPosition2 = backgroundPosition2;
exports.backgroundPosition3 = backgroundPosition3;
exports.backgroundPosition4 = backgroundPosition4;
exports.backgroundPositionString = backgroundPositionString;
exports.backgroundStyle = backgroundStyle;
exports.backgroundStyle2 = backgroundStyle2;
exports.backgroundStyle3 = backgroundStyle3;
exports.backgroundStyle4 = backgroundStyle4;
exports.backgroundStyleString = backgroundStyleString;
exports.margin = margin;
exports.margin2 = margin2;
exports.margin3 = margin3;
exports.margin4 = margin4;
exports.marginString = marginString;
exports.marginNumber = marginNumber;
exports.marginTop = marginTop;
exports.marginTopString = marginTopString;
exports.marginTopNumber = marginTopNumber;
exports.marginRight = marginRight;
exports.marginRightString = marginRightString;
exports.marginRightNumber = marginRightNumber;
exports.marginBottom = marginBottom;
exports.marginBottomString = marginBottomString;
exports.marginBottomNumber = marginBottomNumber;
exports.marginLeft = marginLeft;
exports.marginLeftString = marginLeftString;
exports.marginLeftNumber = marginLeftNumber;
exports.padding = padding;
exports.padding2 = padding2;
exports.padding3 = padding3;
exports.padding4 = padding4;
exports.paddingString = paddingString;
exports.paddingNumber = paddingNumber;
exports.paddingTop = paddingTop;
exports.paddingTopString = paddingTopString;
exports.paddingTopNumber = paddingTopNumber;
exports.paddingRight = paddingRight;
exports.paddingRightString = paddingRightString;
exports.paddingRightNumber = paddingRightNumber;
exports.paddingBottom = paddingBottom;
exports.paddingBottomString = paddingBottomString;
exports.paddingBottomNumber = paddingBottomNumber;
exports.paddingLeft = paddingLeft;
exports.paddingLeftString = paddingLeftString;
exports.paddingLeftNumber = paddingLeftNumber;
exports.clear = clear;
exports.color = color;
exports.colorString = colorString;
exports.cursor = cursor;
exports.cursor1 = cursor1;
exports.cursor2 = cursor2;
exports.cursor3 = cursor3;
exports.cursor4 = cursor4;
exports.cursorString = cursorString;
/* No side effect */
