// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssPropertyValue$Ress = require("./CssPropertyValue.js");

function property(name, value) {
  return [
          name,
          value
        ];
}

function propertyString(name, value) {
  return [
          name,
          value
        ];
}

function propertyNumber(name, value) {
  return [
          name,
          value
        ];
}

function propertyInteger(name, value) {
  return [
          name,
          value
        ];
}

function border(width, color, style) {
  return [
          "border",
          CssPropertyValue$Ress.border(width, color, style)
        ];
}

function borderString(v) {
  return [
          "border",
          v
        ];
}

function borderTop(width, color, style) {
  return [
          "borderTop",
          CssPropertyValue$Ress.border(width, color, style)
        ];
}

function borderTopString(v) {
  return [
          "borderTop",
          v
        ];
}

function borderLeft(width, color, style) {
  return [
          "borderLeft",
          CssPropertyValue$Ress.border(width, color, style)
        ];
}

function borderLeftString(v) {
  return [
          "borderLeft",
          v
        ];
}

function borderRight(width, color, style) {
  return [
          "borderRight",
          CssPropertyValue$Ress.border(width, color, style)
        ];
}

function borderRightString(v) {
  return [
          "borderRight",
          v
        ];
}

function borderBottom(width, color, style) {
  return [
          "borderBottom",
          CssPropertyValue$Ress.border(width, color, style)
        ];
}

function borderBottomString(v) {
  return [
          "borderBottom",
          v
        ];
}

function borderColor(v) {
  return [
          "borderColor",
          CssPropertyValue$Ress.borderColor(v)
        ];
}

function borderColor2(tb, lr) {
  return [
          "borderColor",
          CssPropertyValue$Ress.borderColor2(tb, lr)
        ];
}

function borderColor3(top, lr, bottom) {
  return [
          "borderColor",
          CssPropertyValue$Ress.borderColor3(top, lr, bottom)
        ];
}

function borderColor4(top, right, bottom, left) {
  return [
          "borderColor",
          CssPropertyValue$Ress.borderColor4(top, right, bottom, left)
        ];
}

function borderColorString(v) {
  return [
          "borderColor",
          v
        ];
}

function borderTopColor(v) {
  return [
          "borderTopColor",
          CssPropertyValue$Ress.borderTopColor(v)
        ];
}

function borderTopColorString(v) {
  return [
          "borderTopColor",
          v
        ];
}

function borderRightColor(v) {
  return [
          "borderRightColor",
          CssPropertyValue$Ress.borderRightColor(v)
        ];
}

function borderRightColorString(v) {
  return [
          "borderRightColor",
          v
        ];
}

function borderBottomColor(v) {
  return [
          "borderBottomColor",
          CssPropertyValue$Ress.borderBottomColor(v)
        ];
}

function borderBottomColorString(v) {
  return [
          "borderBottomColor",
          v
        ];
}

function borderLeftColor(v) {
  return [
          "borderLeftColor",
          CssPropertyValue$Ress.borderLeftColor(v)
        ];
}

function borderLeftColorString(v) {
  return [
          "borderLeftColor",
          v
        ];
}

function borderStyle(v) {
  return [
          "borderStyle",
          CssPropertyValue$Ress.borderStyle(v)
        ];
}

function borderStyle2(tb, lr) {
  return [
          "borderStyle",
          CssPropertyValue$Ress.borderStyle2(tb, lr)
        ];
}

function borderStyle3(top, lr, bottom) {
  return [
          "borderStyle",
          CssPropertyValue$Ress.borderStyle3(top, lr, bottom)
        ];
}

function borderStyle4(top, right, bottom, left) {
  return [
          "borderStyle",
          CssPropertyValue$Ress.borderStyle4(top, right, bottom, left)
        ];
}

function borderStyleString(v) {
  return [
          "borderStyle",
          v
        ];
}

function borderTopStyle(v) {
  return [
          "borderTopStyle",
          CssPropertyValue$Ress.borderStyle(v)
        ];
}

function borderTopStyleString(v) {
  return [
          "borderTopStyle",
          v
        ];
}

function borderRightStyle(v) {
  return [
          "borderRightStyle",
          CssPropertyValue$Ress.borderStyle(v)
        ];
}

function borderRightStyleString(v) {
  return [
          "borderRightStyle",
          v
        ];
}

function borderBottomStyle(v) {
  return [
          "borderBottomStyle",
          CssPropertyValue$Ress.borderStyle(v)
        ];
}

function borderBottomStyleString(v) {
  return [
          "borderBottomStyle",
          v
        ];
}

function borderLeftStyle(v) {
  return [
          "borderLeftStyle",
          CssPropertyValue$Ress.borderStyle(v)
        ];
}

function borderLeftStyleString(v) {
  return [
          "borderLeftStyle",
          v
        ];
}

function borderWidth(v) {
  return [
          "borderWidth",
          CssPropertyValue$Ress.borderWidth(v)
        ];
}

function borderWidth2(tb, lr) {
  return [
          "borderWidth",
          CssPropertyValue$Ress.borderWidth2(tb, lr)
        ];
}

function borderWidth3(top, lr, bottom) {
  return [
          "borderWidth",
          CssPropertyValue$Ress.borderWidth3(top, lr, bottom)
        ];
}

function borderWidth4(top, right, bottom, left) {
  return [
          "borderWidth",
          CssPropertyValue$Ress.borderWidth4(top, right, bottom, left)
        ];
}

function borderWidthString(v) {
  return [
          "borderWidth",
          v
        ];
}

function borderTopWidth(v) {
  return [
          "borderTopWidth",
          CssPropertyValue$Ress.borderTopWidth(v)
        ];
}

function borderTopWidthString(v) {
  return [
          "borderTopWidth",
          v
        ];
}

function borderRightWidth(v) {
  return [
          "borderRightWidth",
          CssPropertyValue$Ress.borderRightWidth(v)
        ];
}

function borderRightWidthString(v) {
  return [
          "borderRightWidth",
          v
        ];
}

function borderBottomWidth(v) {
  return [
          "borderBottomWidth",
          CssPropertyValue$Ress.borderBottomWidth(v)
        ];
}

function borderBottomWidthString(v) {
  return [
          "borderBottomWidth",
          v
        ];
}

function borderLeftWidth(v) {
  return [
          "borderLeftWidth",
          CssPropertyValue$Ress.borderLeftWidth(v)
        ];
}

function borderLeftWidthString(v) {
  return [
          "borderLeftWidth",
          v
        ];
}

function background(color, position, size, repeat, attachment, origin, clip, imageOrColor) {
  return [
          "background",
          CssPropertyValue$Ress.background(color, position, size, repeat, attachment, origin, clip, imageOrColor)
        ];
}

function background2(l1, l2) {
  return [
          "background",
          CssPropertyValue$Ress.background2(l1, l2)
        ];
}

function background3(l1, l2, l3) {
  return [
          "background",
          CssPropertyValue$Ress.background3(l1, l2, l3)
        ];
}

function background4(l1, l2, l3, l4) {
  return [
          "background",
          CssPropertyValue$Ress.background4(l1, l2, l3, l4)
        ];
}

function backgroundString(v) {
  return [
          "background",
          v
        ];
}

function backgroundAttachment(v) {
  return [
          "backgroundAttachment",
          CssPropertyValue$Ress.backgroundAttachment(v)
        ];
}

function backgroundAttachment2(v1, v2) {
  return [
          "backgroundAttachment",
          CssPropertyValue$Ress.backgroundAttachment2(v1, v2)
        ];
}

function backgroundAttachment3(v1, v2, v3) {
  return [
          "backgroundAttachment",
          CssPropertyValue$Ress.backgroundAttachment3(v1, v2, v3)
        ];
}

function backgroundAttachment4(v1, v2, v3, v4) {
  return [
          "backgroundAttachment",
          CssPropertyValue$Ress.backgroundAttachment4(v1, v2, v3, v4)
        ];
}

function backgroundAttachmentString(v) {
  return [
          "backgroundAttachment",
          v
        ];
}

function backgroundColor(v) {
  return [
          "backgroundColor",
          CssPropertyValue$Ress.backgroundColor(v)
        ];
}

function backgroundColorString(v) {
  return [
          "backgroundColor",
          v
        ];
}

function backgroundImage(v) {
  return [
          "backgroundImage",
          CssPropertyValue$Ress.backgroundImage(v)
        ];
}

function backgroundImage2(v1, v2) {
  return [
          "backgroundImage",
          CssPropertyValue$Ress.backgroundImage2(v1, v2)
        ];
}

function backgroundImage3(v1, v2, v3) {
  return [
          "backgroundImage",
          CssPropertyValue$Ress.backgroundImage3(v1, v2, v3)
        ];
}

function backgroundImage4(v1, v2, v3, v4) {
  return [
          "backgroundImage",
          CssPropertyValue$Ress.backgroundImage4(v1, v2, v3, v4)
        ];
}

function backgroundImageString(v) {
  return [
          "backgroundImage",
          v
        ];
}

function backgroundPosition(v) {
  return [
          "backgroundPosition",
          CssPropertyValue$Ress.backgroundPosition(v)
        ];
}

function backgroundPosition2(v1, v2) {
  return [
          "backgroundPosition",
          CssPropertyValue$Ress.backgroundPosition2(v1, v2)
        ];
}

function backgroundPosition3(v1, v2, v3) {
  return [
          "backgroundPosition",
          CssPropertyValue$Ress.backgroundPosition3(v1, v2, v3)
        ];
}

function backgroundPosition4(v1, v2, v3, v4) {
  return [
          "backgroundPosition",
          CssPropertyValue$Ress.backgroundPosition4(v1, v2, v3, v4)
        ];
}

function backgroundPositionString(v) {
  return [
          "backgroundPosition",
          v
        ];
}

function backgroundStyle(v) {
  return [
          "backgroundStyle",
          CssPropertyValue$Ress.backgroundStyle(v)
        ];
}

function backgroundStyle2(v1, v2) {
  return [
          "backgroundStyle",
          CssPropertyValue$Ress.backgroundStyle2(v1, v2)
        ];
}

function backgroundStyle3(v1, v2, v3) {
  return [
          "backgroundStyle",
          CssPropertyValue$Ress.backgroundStyle3(v1, v2, v3)
        ];
}

function backgroundStyle4(v1, v2, v3, v4) {
  return [
          "backgroundStyle",
          CssPropertyValue$Ress.backgroundStyle4(v1, v2, v3, v4)
        ];
}

function backgroundStyleString(v) {
  return [
          "backgroundStyle",
          v
        ];
}

function margin(v) {
  return [
          "margin",
          CssPropertyValue$Ress.margin(v)
        ];
}

function margin2(tb, lr) {
  return [
          "margin",
          CssPropertyValue$Ress.margin2(tb, lr)
        ];
}

function margin3(top, lr, bottom) {
  return [
          "margin",
          CssPropertyValue$Ress.margin3(top, lr, bottom)
        ];
}

function margin4(top, right, bottom, left) {
  return [
          "margin",
          CssPropertyValue$Ress.margin4(top, right, bottom, left)
        ];
}

function marginString(v) {
  return [
          "margin",
          v
        ];
}

function marginNumber(v) {
  return [
          "margin",
          v
        ];
}

function marginTop(v) {
  return [
          "marginTop",
          CssPropertyValue$Ress.marginTop(v)
        ];
}

function marginTopString(v) {
  return [
          "marginTop",
          v
        ];
}

function marginTopNumber(v) {
  return [
          "marginTop",
          v
        ];
}

function marginRight(v) {
  return [
          "marginRight",
          CssPropertyValue$Ress.marginRight(v)
        ];
}

function marginRightString(v) {
  return [
          "marginRight",
          v
        ];
}

function marginRightNumber(v) {
  return [
          "marginRight",
          v
        ];
}

function marginBottom(v) {
  return [
          "marginBottom",
          CssPropertyValue$Ress.marginBottom(v)
        ];
}

function marginBottomString(v) {
  return [
          "marginBottom",
          v
        ];
}

function marginBottomNumber(v) {
  return [
          "marginBottom",
          v
        ];
}

function marginLeft(v) {
  return [
          "marginLeft",
          CssPropertyValue$Ress.marginLeft(v)
        ];
}

function marginLeftString(v) {
  return [
          "marginLeft",
          v
        ];
}

function marginLeftNumber(v) {
  return [
          "marginLeft",
          v
        ];
}

function padding(v) {
  return [
          "padding",
          CssPropertyValue$Ress.padding(v)
        ];
}

function padding2(tb, lr) {
  return [
          "padding",
          CssPropertyValue$Ress.padding2(tb, lr)
        ];
}

function padding3(top, lr, bottom) {
  return [
          "padding",
          CssPropertyValue$Ress.padding3(top, lr, bottom)
        ];
}

function padding4(top, right, bottom, left) {
  return [
          "padding",
          CssPropertyValue$Ress.padding4(top, right, bottom, left)
        ];
}

function paddingString(v) {
  return [
          "padding",
          v
        ];
}

function paddingNumber(v) {
  return [
          "padding",
          v
        ];
}

function paddingTop(v) {
  return [
          "paddingTop",
          CssPropertyValue$Ress.paddingTop(v)
        ];
}

function paddingTopString(v) {
  return [
          "paddingTop",
          v
        ];
}

function paddingTopNumber(v) {
  return [
          "paddingTop",
          v
        ];
}

function paddingRight(v) {
  return [
          "paddingRight",
          CssPropertyValue$Ress.paddingRight(v)
        ];
}

function paddingRightString(v) {
  return [
          "paddingRight",
          v
        ];
}

function paddingRightNumber(v) {
  return [
          "paddingRight",
          v
        ];
}

function paddingBottom(v) {
  return [
          "paddingBottom",
          CssPropertyValue$Ress.paddingBottom(v)
        ];
}

function paddingBottomString(v) {
  return [
          "paddingBottom",
          v
        ];
}

function paddingBottomNumber(v) {
  return [
          "paddingBottom",
          v
        ];
}

function paddingLeft(v) {
  return [
          "paddingLeft",
          CssPropertyValue$Ress.paddingLeft(v)
        ];
}

function paddingLeftString(v) {
  return [
          "paddingLeft",
          v
        ];
}

function paddingLeftNumber(v) {
  return [
          "paddingLeft",
          v
        ];
}

function clear(v) {
  return [
          "clear",
          CssPropertyValue$Ress.clear(v)
        ];
}

function color(v) {
  return [
          "color",
          CssPropertyValue$Ress.color(v)
        ];
}

function colorString(v) {
  return [
          "color",
          v
        ];
}

function cursor(v) {
  return [
          "cursor",
          CssPropertyValue$Ress.cursor(v)
        ];
}

function cursor1(i, k) {
  return [
          "cursor",
          CssPropertyValue$Ress.cursor1(i, k)
        ];
}

function cursor2(i1, i2, k) {
  return [
          "cursor",
          CssPropertyValue$Ress.cursor2(i1, i2, k)
        ];
}

function cursor3(i1, i2, i3, k) {
  return [
          "cursor",
          CssPropertyValue$Ress.cursor3(i1, i2, i3, k)
        ];
}

function cursor4(i1, i2, i3, i4, k) {
  return [
          "cursor",
          CssPropertyValue$Ress.cursor4(i1, i2, i3, i4, k)
        ];
}

function cursorString(v) {
  return [
          "cursor",
          v
        ];
}

exports.property = property;
exports.propertyString = propertyString;
exports.propertyNumber = propertyNumber;
exports.propertyInteger = propertyInteger;
exports.border = border;
exports.borderString = borderString;
exports.borderTop = borderTop;
exports.borderTopString = borderTopString;
exports.borderLeft = borderLeft;
exports.borderLeftString = borderLeftString;
exports.borderRight = borderRight;
exports.borderRightString = borderRightString;
exports.borderBottom = borderBottom;
exports.borderBottomString = borderBottomString;
exports.borderColor = borderColor;
exports.borderColor2 = borderColor2;
exports.borderColor3 = borderColor3;
exports.borderColor4 = borderColor4;
exports.borderColorString = borderColorString;
exports.borderTopColor = borderTopColor;
exports.borderTopColorString = borderTopColorString;
exports.borderRightColor = borderRightColor;
exports.borderRightColorString = borderRightColorString;
exports.borderBottomColor = borderBottomColor;
exports.borderBottomColorString = borderBottomColorString;
exports.borderLeftColor = borderLeftColor;
exports.borderLeftColorString = borderLeftColorString;
exports.borderStyle = borderStyle;
exports.borderStyle2 = borderStyle2;
exports.borderStyle3 = borderStyle3;
exports.borderStyle4 = borderStyle4;
exports.borderStyleString = borderStyleString;
exports.borderTopStyle = borderTopStyle;
exports.borderTopStyleString = borderTopStyleString;
exports.borderRightStyle = borderRightStyle;
exports.borderRightStyleString = borderRightStyleString;
exports.borderBottomStyle = borderBottomStyle;
exports.borderBottomStyleString = borderBottomStyleString;
exports.borderLeftStyle = borderLeftStyle;
exports.borderLeftStyleString = borderLeftStyleString;
exports.borderWidth = borderWidth;
exports.borderWidth2 = borderWidth2;
exports.borderWidth3 = borderWidth3;
exports.borderWidth4 = borderWidth4;
exports.borderWidthString = borderWidthString;
exports.borderTopWidth = borderTopWidth;
exports.borderTopWidthString = borderTopWidthString;
exports.borderRightWidth = borderRightWidth;
exports.borderRightWidthString = borderRightWidthString;
exports.borderBottomWidth = borderBottomWidth;
exports.borderBottomWidthString = borderBottomWidthString;
exports.borderLeftWidth = borderLeftWidth;
exports.borderLeftWidthString = borderLeftWidthString;
exports.background = background;
exports.backgroundString = backgroundString;
exports.background2 = background2;
exports.background3 = background3;
exports.background4 = background4;
exports.backgroundAttachment = backgroundAttachment;
exports.backgroundAttachment2 = backgroundAttachment2;
exports.backgroundAttachment3 = backgroundAttachment3;
exports.backgroundAttachment4 = backgroundAttachment4;
exports.backgroundAttachmentString = backgroundAttachmentString;
exports.backgroundColor = backgroundColor;
exports.backgroundColorString = backgroundColorString;
exports.backgroundImage = backgroundImage;
exports.backgroundImage2 = backgroundImage2;
exports.backgroundImage3 = backgroundImage3;
exports.backgroundImage4 = backgroundImage4;
exports.backgroundImageString = backgroundImageString;
exports.backgroundPosition = backgroundPosition;
exports.backgroundPosition2 = backgroundPosition2;
exports.backgroundPosition3 = backgroundPosition3;
exports.backgroundPosition4 = backgroundPosition4;
exports.backgroundPositionString = backgroundPositionString;
exports.backgroundStyle = backgroundStyle;
exports.backgroundStyle2 = backgroundStyle2;
exports.backgroundStyle3 = backgroundStyle3;
exports.backgroundStyle4 = backgroundStyle4;
exports.backgroundStyleString = backgroundStyleString;
exports.margin = margin;
exports.margin2 = margin2;
exports.margin3 = margin3;
exports.margin4 = margin4;
exports.marginString = marginString;
exports.marginNumber = marginNumber;
exports.marginTop = marginTop;
exports.marginTopString = marginTopString;
exports.marginTopNumber = marginTopNumber;
exports.marginRight = marginRight;
exports.marginRightString = marginRightString;
exports.marginRightNumber = marginRightNumber;
exports.marginBottom = marginBottom;
exports.marginBottomString = marginBottomString;
exports.marginBottomNumber = marginBottomNumber;
exports.marginLeft = marginLeft;
exports.marginLeftString = marginLeftString;
exports.marginLeftNumber = marginLeftNumber;
exports.padding = padding;
exports.padding2 = padding2;
exports.padding3 = padding3;
exports.padding4 = padding4;
exports.paddingString = paddingString;
exports.paddingNumber = paddingNumber;
exports.paddingTop = paddingTop;
exports.paddingTopString = paddingTopString;
exports.paddingTopNumber = paddingTopNumber;
exports.paddingRight = paddingRight;
exports.paddingRightString = paddingRightString;
exports.paddingRightNumber = paddingRightNumber;
exports.paddingBottom = paddingBottom;
exports.paddingBottomString = paddingBottomString;
exports.paddingBottomNumber = paddingBottomNumber;
exports.paddingLeft = paddingLeft;
exports.paddingLeftString = paddingLeftString;
exports.paddingLeftNumber = paddingLeftNumber;
exports.clear = clear;
exports.color = color;
exports.colorString = colorString;
exports.cursor = cursor;
exports.cursor1 = cursor1;
exports.cursor2 = cursor2;
exports.cursor3 = cursor3;
exports.cursor4 = cursor4;
exports.cursorString = cursorString;
/* No side effect */
