// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function Make(Type) {
  var hover = function (declarations) {
    return {
            NAME: "Hover",
            VAL: Curry._1(Type.declarations, declarations)
          };
  };
  return {
          hover: hover
        };
}

exports.Make = Make;
/* No side effect */
