// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var FontFace$Ress = require("./FontFace.js");
var CssPropertyValue$Ress = require("./CssPropertyValue.js");

function Make(funarg) {
  var style = function (statements) {
    return Js_dict.fromArray(Belt_Array.map(statements, (function (statement) {
                      switch (statement.TAG | 0) {
                        case /* FontFace */1 :
                            return [
                                    "@font-face",
                                    statement._0
                                  ];
                        case /* Selector */0 :
                        case /* Property */2 :
                            return [
                                    statement._0,
                                    statement._1
                                  ];
                        case /* BorderTop */4 :
                            return [
                                    "borderTop",
                                    statement._0
                                  ];
                        case /* BorderRight */5 :
                            return [
                                    "borderRight",
                                    statement._0
                                  ];
                        case /* BorderBottom */6 :
                            return [
                                    "borderBottom",
                                    statement._0
                                  ];
                        case /* BorderLeft */7 :
                            return [
                                    "borderLeft",
                                    statement._0
                                  ];
                        case /* Border */3 :
                        case /* BorderStyle */8 :
                            return [
                                    "border",
                                    statement._0
                                  ];
                        case /* BorderTopStyle */9 :
                            return [
                                    "borderTopStyle",
                                    statement._0
                                  ];
                        case /* BorderRightStyle */10 :
                            return [
                                    "borderRightStyle",
                                    statement._0
                                  ];
                        case /* BorderBottomStyle */11 :
                            return [
                                    "borderBottomStyle",
                                    statement._0
                                  ];
                        case /* BorderLeftStyle */12 :
                            return [
                                    "borderLeftStyle",
                                    statement._0
                                  ];
                        case /* BorderWidth */13 :
                            return [
                                    "boderWidth",
                                    statement._0
                                  ];
                        case /* BorderTopWidth */14 :
                            return [
                                    "borderTopWidth",
                                    statement._0
                                  ];
                        case /* BorderRightWidth */15 :
                            return [
                                    "borderRightWidth",
                                    statement._0
                                  ];
                        case /* BorderBottomWidth */16 :
                            return [
                                    "borderBottomWidth",
                                    statement._0
                                  ];
                        case /* BorderLeftWidth */17 :
                            return [
                                    "borderLeftWidth",
                                    statement._0
                                  ];
                        case /* BorderColor */18 :
                            return [
                                    "borderColor",
                                    statement._0
                                  ];
                        case /* BorderTopColor */19 :
                            return [
                                    "borderTopColor",
                                    statement._0
                                  ];
                        case /* BorderRightColor */20 :
                            return [
                                    "borderRightColor",
                                    statement._0
                                  ];
                        case /* BorderBottomColor */21 :
                            return [
                                    "borderBottomColor",
                                    statement._0
                                  ];
                        case /* BorderLeftColor */22 :
                            return [
                                    "borderLeftColor",
                                    statement._0
                                  ];
                        case /* Background */23 :
                            return [
                                    "background",
                                    statement._0
                                  ];
                        case /* BackgroundAttachment */24 :
                            return [
                                    "backgroundAttachment",
                                    statement._0
                                  ];
                        case /* BackgroundColor */25 :
                            return [
                                    "backgroundColor",
                                    statement._0
                                  ];
                        case /* BackgroundImage */26 :
                            return [
                                    "backgroundImage",
                                    statement._0
                                  ];
                        case /* BackgroundPosition */27 :
                            return [
                                    "backgroundPosition",
                                    statement._0
                                  ];
                        case /* BackgroundStyle */28 :
                            return [
                                    "backgroundStyle",
                                    statement._0
                                  ];
                        case /* Margin */29 :
                            return [
                                    "margin",
                                    statement._0
                                  ];
                        case /* MarginTop */30 :
                            return [
                                    "marginTop",
                                    statement._0
                                  ];
                        case /* MarginRight */31 :
                            return [
                                    "marginRight",
                                    statement._0
                                  ];
                        case /* MarginBottom */32 :
                            return [
                                    "marginBottom",
                                    statement._0
                                  ];
                        case /* MarginLeft */33 :
                            return [
                                    "marginLeft",
                                    statement._0
                                  ];
                        case /* Padding */34 :
                            return [
                                    "padding",
                                    statement._0
                                  ];
                        case /* PaddingTop */35 :
                            return [
                                    "paddingTop",
                                    statement._0
                                  ];
                        case /* PaddingBottom */36 :
                            return [
                                    "paddingBottom",
                                    statement._0
                                  ];
                        case /* PaddingRight */37 :
                            return [
                                    "paddingRight",
                                    statement._0
                                  ];
                        case /* PaddingLeft */38 :
                            return [
                                    "paddingLeft",
                                    statement._0
                                  ];
                        case /* Color */39 :
                            return [
                                    "color",
                                    statement._0
                                  ];
                        case /* Clear */40 :
                            return [
                                    "clear",
                                    statement._0
                                  ];
                        case /* Cursor */41 :
                            return [
                                    "cursor",
                                    statement._0
                                  ];
                        
                      }
                    })));
  };
  var selector = function (selector$1, declaration) {
    return {
            TAG: /* Selector */0,
            _0: selector$1,
            _1: style(declaration)
          };
  };
  var fontFace = function (descriptors) {
    return {
            TAG: /* FontFace */1,
            _0: FontFace$Ress.make(descriptors)
          };
  };
  var property = function (name, value) {
    return {
            TAG: /* Property */2,
            _0: name,
            _1: value
          };
  };
  var propertyNumber = function (name, value) {
    return {
            TAG: /* Property */2,
            _0: name,
            _1: value
          };
  };
  var propertyInteger = function (name, value) {
    return {
            TAG: /* Property */2,
            _0: name,
            _1: value
          };
  };
  var border = function (width, color, style) {
    return {
            TAG: /* Border */3,
            _0: CssPropertyValue$Ress.border(width, color, style)
          };
  };
  var borderString = function (v) {
    return {
            TAG: /* Border */3,
            _0: v
          };
  };
  var borderTop = function (width, color, style) {
    return {
            TAG: /* BorderTop */4,
            _0: CssPropertyValue$Ress.border(width, color, style)
          };
  };
  var borderTopString = function (v) {
    return {
            TAG: /* BorderTop */4,
            _0: v
          };
  };
  var borderLeft = function (width, color, style) {
    return {
            TAG: /* BorderLeft */7,
            _0: CssPropertyValue$Ress.border(width, color, style)
          };
  };
  var borderLeftString = function (v) {
    return {
            TAG: /* BorderLeft */7,
            _0: v
          };
  };
  var borderRight = function (width, color, style) {
    return {
            TAG: /* BorderRight */5,
            _0: CssPropertyValue$Ress.border(width, color, style)
          };
  };
  var borderRightString = function (v) {
    return {
            TAG: /* BorderRight */5,
            _0: v
          };
  };
  var borderBottom = function (width, color, style) {
    return {
            TAG: /* BorderBottom */6,
            _0: CssPropertyValue$Ress.border(width, color, style)
          };
  };
  var borderBottomString = function (v) {
    return {
            TAG: /* BorderBottom */6,
            _0: v
          };
  };
  var borderColor = function (v) {
    return {
            TAG: /* BorderColor */18,
            _0: CssPropertyValue$Ress.borderColor(v)
          };
  };
  var borderColor2 = function (tb, lr) {
    return {
            TAG: /* BorderColor */18,
            _0: CssPropertyValue$Ress.borderColor2(tb, lr)
          };
  };
  var borderColor3 = function (top, lr, bottom) {
    return {
            TAG: /* BorderColor */18,
            _0: CssPropertyValue$Ress.borderColor3(top, lr, bottom)
          };
  };
  var borderColor4 = function (top, right, bottom, left) {
    return {
            TAG: /* BorderColor */18,
            _0: CssPropertyValue$Ress.borderColor4(top, right, bottom, left)
          };
  };
  var borderColorString = function (v) {
    return {
            TAG: /* BorderColor */18,
            _0: v
          };
  };
  var borderTopColor = function (v) {
    return {
            TAG: /* BorderTopColor */19,
            _0: CssPropertyValue$Ress.borderTopColor(v)
          };
  };
  var borderTopColorString = function (v) {
    return {
            TAG: /* BorderTopColor */19,
            _0: v
          };
  };
  var borderRightColor = function (v) {
    return {
            TAG: /* BorderRightColor */20,
            _0: CssPropertyValue$Ress.borderRightColor(v)
          };
  };
  var borderRightColorString = function (v) {
    return {
            TAG: /* BorderRightColor */20,
            _0: v
          };
  };
  var borderBottomColor = function (v) {
    return {
            TAG: /* BorderBottomColor */21,
            _0: CssPropertyValue$Ress.borderBottomColor(v)
          };
  };
  var borderBottomColorString = function (v) {
    return {
            TAG: /* BorderBottomColor */21,
            _0: v
          };
  };
  var borderLeftColor = function (v) {
    return {
            TAG: /* BorderLeftColor */22,
            _0: CssPropertyValue$Ress.borderLeftColor(v)
          };
  };
  var borderLeftColorString = function (v) {
    return {
            TAG: /* BorderLeftColor */22,
            _0: v
          };
  };
  var borderStyle = function (v) {
    return {
            TAG: /* BorderStyle */8,
            _0: CssPropertyValue$Ress.borderStyle(v)
          };
  };
  var borderStyle2 = function (tb, lr) {
    return {
            TAG: /* BorderStyle */8,
            _0: CssPropertyValue$Ress.borderStyle2(tb, lr)
          };
  };
  var borderStyle3 = function (top, lr, bottom) {
    return {
            TAG: /* BorderStyle */8,
            _0: CssPropertyValue$Ress.borderStyle3(top, lr, bottom)
          };
  };
  var borderStyle4 = function (top, right, bottom, left) {
    return {
            TAG: /* BorderStyle */8,
            _0: CssPropertyValue$Ress.borderStyle4(top, right, bottom, left)
          };
  };
  var borderStyleString = function (v) {
    return {
            TAG: /* BorderStyle */8,
            _0: v
          };
  };
  var borderTopStyle = function (v) {
    return {
            TAG: /* BorderTopStyle */9,
            _0: CssPropertyValue$Ress.borderTopStyle(v)
          };
  };
  var borderTopStyleString = function (v) {
    return {
            TAG: /* BorderTopStyle */9,
            _0: v
          };
  };
  var borderRightStyle = function (v) {
    return {
            TAG: /* BorderRightStyle */10,
            _0: CssPropertyValue$Ress.borderRightStyle(v)
          };
  };
  var borderRightStyleString = function (v) {
    return {
            TAG: /* BorderRightStyle */10,
            _0: v
          };
  };
  var borderBottomStyle = function (v) {
    return {
            TAG: /* BorderBottomStyle */11,
            _0: CssPropertyValue$Ress.borderBottomStyle(v)
          };
  };
  var borderBottomStyleString = function (v) {
    return {
            TAG: /* BorderBottomStyle */11,
            _0: v
          };
  };
  var borderLeftStyle = function (v) {
    return {
            TAG: /* BorderLeftStyle */12,
            _0: CssPropertyValue$Ress.borderLeftStyle(v)
          };
  };
  var borderLeftStyleString = function (v) {
    return {
            TAG: /* BorderLeftStyle */12,
            _0: v
          };
  };
  var borderWidth = function (v) {
    return {
            TAG: /* BorderWidth */13,
            _0: CssPropertyValue$Ress.borderWidth(v)
          };
  };
  var borderWidth2 = function (tb, lr) {
    return {
            TAG: /* BorderWidth */13,
            _0: CssPropertyValue$Ress.borderWidth2(tb, lr)
          };
  };
  var borderWidth3 = function (top, lr, bottom) {
    return {
            TAG: /* BorderWidth */13,
            _0: CssPropertyValue$Ress.borderWidth3(top, lr, bottom)
          };
  };
  var borderWidth4 = function (top, right, bottom, left) {
    return {
            TAG: /* BorderWidth */13,
            _0: CssPropertyValue$Ress.borderWidth4(top, right, bottom, left)
          };
  };
  var borderWidthString = function (v) {
    return {
            TAG: /* BorderWidth */13,
            _0: v
          };
  };
  var borderTopWidth = function (v) {
    return {
            TAG: /* BorderTopWidth */14,
            _0: CssPropertyValue$Ress.borderTopWidth(v)
          };
  };
  var borderTopWidthString = function (v) {
    return {
            TAG: /* BorderTopWidth */14,
            _0: v
          };
  };
  var borderRightWidth = function (v) {
    return {
            TAG: /* BorderRightWidth */15,
            _0: CssPropertyValue$Ress.borderRightWidth(v)
          };
  };
  var borderRightWidthString = function (v) {
    return {
            TAG: /* BorderRightWidth */15,
            _0: v
          };
  };
  var borderBottomWidth = function (v) {
    return {
            TAG: /* BorderBottomWidth */16,
            _0: CssPropertyValue$Ress.borderBottomWidth(v)
          };
  };
  var borderBottomWidthString = function (v) {
    return {
            TAG: /* BorderBottomWidth */16,
            _0: v
          };
  };
  var borderLeftWidth = function (v) {
    return {
            TAG: /* BorderLeftWidth */17,
            _0: CssPropertyValue$Ress.borderLeftWidth(v)
          };
  };
  var borderLeftWidthString = function (v) {
    return {
            TAG: /* BorderLeftWidth */17,
            _0: v
          };
  };
  var background = function (color, position, size, repeat, attachment, origin, clip, imageOrColor) {
    return {
            TAG: /* Background */23,
            _0: CssPropertyValue$Ress.background(color, position, size, repeat, attachment, origin, clip, imageOrColor)
          };
  };
  var background2 = function (l1, l2) {
    return {
            TAG: /* Background */23,
            _0: CssPropertyValue$Ress.background2(l1, l2)
          };
  };
  var background3 = function (l1, l2, l3) {
    return {
            TAG: /* Background */23,
            _0: CssPropertyValue$Ress.background3(l1, l2, l3)
          };
  };
  var background4 = function (l1, l2, l3, l4) {
    return {
            TAG: /* Background */23,
            _0: CssPropertyValue$Ress.background4(l1, l2, l3, l4)
          };
  };
  var backgroundString = function (v) {
    return {
            TAG: /* Background */23,
            _0: v
          };
  };
  var backgroundAttachment = function (v) {
    return {
            TAG: /* BackgroundAttachment */24,
            _0: CssPropertyValue$Ress.backgroundAttachment(v)
          };
  };
  var backgroundAttachment2 = function (v1, v2) {
    return {
            TAG: /* BackgroundAttachment */24,
            _0: CssPropertyValue$Ress.backgroundAttachment2(v1, v2)
          };
  };
  var backgroundAttachment3 = function (v1, v2, v3) {
    return {
            TAG: /* BackgroundAttachment */24,
            _0: CssPropertyValue$Ress.backgroundAttachment3(v1, v2, v3)
          };
  };
  var backgroundAttachment4 = function (v1, v2, v3, v4) {
    return {
            TAG: /* BackgroundAttachment */24,
            _0: CssPropertyValue$Ress.backgroundAttachment4(v1, v2, v3, v4)
          };
  };
  var backgroundAttachmentString = function (v) {
    return {
            TAG: /* BackgroundAttachment */24,
            _0: v
          };
  };
  var backgroundColor = function (v) {
    return {
            TAG: /* BackgroundColor */25,
            _0: CssPropertyValue$Ress.backgroundColor(v)
          };
  };
  var backgroundColorString = function (v) {
    return {
            TAG: /* BackgroundColor */25,
            _0: v
          };
  };
  var backgroundImage = function (v) {
    return {
            TAG: /* BackgroundImage */26,
            _0: CssPropertyValue$Ress.backgroundImage(v)
          };
  };
  var backgroundImage2 = function (v1, v2) {
    return {
            TAG: /* BackgroundImage */26,
            _0: CssPropertyValue$Ress.backgroundImage2(v1, v2)
          };
  };
  var backgroundImage3 = function (v1, v2, v3) {
    return {
            TAG: /* BackgroundImage */26,
            _0: CssPropertyValue$Ress.backgroundImage3(v1, v2, v3)
          };
  };
  var backgroundImage4 = function (v1, v2, v3, v4) {
    return {
            TAG: /* BackgroundImage */26,
            _0: CssPropertyValue$Ress.backgroundImage4(v1, v2, v3, v4)
          };
  };
  var backgroundImageString = function (v) {
    return {
            TAG: /* BackgroundImage */26,
            _0: v
          };
  };
  var backgroundPosition = function (v) {
    return {
            TAG: /* BackgroundPosition */27,
            _0: CssPropertyValue$Ress.backgroundPosition(v)
          };
  };
  var backgroundPosition2 = function (v1, v2) {
    return {
            TAG: /* BackgroundPosition */27,
            _0: CssPropertyValue$Ress.backgroundPosition2(v1, v2)
          };
  };
  var backgroundPosition3 = function (v1, v2, v3) {
    return {
            TAG: /* BackgroundPosition */27,
            _0: CssPropertyValue$Ress.backgroundPosition3(v1, v2, v3)
          };
  };
  var backgroundPosition4 = function (v1, v2, v3, v4) {
    return {
            TAG: /* BackgroundPosition */27,
            _0: CssPropertyValue$Ress.backgroundPosition4(v1, v2, v3, v4)
          };
  };
  var backgroundPositionString = function (v) {
    return {
            TAG: /* BackgroundPosition */27,
            _0: v
          };
  };
  var backgroundStyle = function (v) {
    return {
            TAG: /* BackgroundStyle */28,
            _0: CssPropertyValue$Ress.backgroundStyle(v)
          };
  };
  var backgroundStyle2 = function (v1, v2) {
    return {
            TAG: /* BackgroundStyle */28,
            _0: CssPropertyValue$Ress.backgroundStyle2(v1, v2)
          };
  };
  var backgroundStyle3 = function (v1, v2, v3) {
    return {
            TAG: /* BackgroundStyle */28,
            _0: CssPropertyValue$Ress.backgroundStyle3(v1, v2, v3)
          };
  };
  var backgroundStyle4 = function (v1, v2, v3, v4) {
    return {
            TAG: /* BackgroundStyle */28,
            _0: CssPropertyValue$Ress.backgroundStyle4(v1, v2, v3, v4)
          };
  };
  var backgroundStyleString = function (v) {
    return {
            TAG: /* BackgroundStyle */28,
            _0: v
          };
  };
  var margin = function (v) {
    return {
            TAG: /* Margin */29,
            _0: CssPropertyValue$Ress.margin(v)
          };
  };
  var margin2 = function (tb, lr) {
    return {
            TAG: /* Margin */29,
            _0: CssPropertyValue$Ress.margin2(tb, lr)
          };
  };
  var margin3 = function (top, lr, bottom) {
    return {
            TAG: /* Margin */29,
            _0: CssPropertyValue$Ress.margin3(top, lr, bottom)
          };
  };
  var margin4 = function (top, right, bottom, left) {
    return {
            TAG: /* Margin */29,
            _0: CssPropertyValue$Ress.margin4(top, right, bottom, left)
          };
  };
  var marginString = function (v) {
    return {
            TAG: /* Margin */29,
            _0: v
          };
  };
  var marginNumber = function (v) {
    return {
            TAG: /* Margin */29,
            _0: v
          };
  };
  var marginTop = function (v) {
    return {
            TAG: /* MarginTop */30,
            _0: CssPropertyValue$Ress.marginTop(v)
          };
  };
  var marginTopString = function (v) {
    return {
            TAG: /* MarginTop */30,
            _0: v
          };
  };
  var marginTopNumber = function (v) {
    return {
            TAG: /* MarginTop */30,
            _0: v
          };
  };
  var marginRight = function (v) {
    return {
            TAG: /* MarginRight */31,
            _0: CssPropertyValue$Ress.marginRight(v)
          };
  };
  var marginRightString = function (v) {
    return {
            TAG: /* MarginRight */31,
            _0: v
          };
  };
  var marginRightNumber = function (v) {
    return {
            TAG: /* MarginRight */31,
            _0: v
          };
  };
  var marginBottom = function (v) {
    return {
            TAG: /* MarginBottom */32,
            _0: CssPropertyValue$Ress.marginBottom(v)
          };
  };
  var marginBottomString = function (v) {
    return {
            TAG: /* MarginBottom */32,
            _0: v
          };
  };
  var marginBottomNumber = function (v) {
    return {
            TAG: /* MarginBottom */32,
            _0: v
          };
  };
  var marginLeft = function (v) {
    return {
            TAG: /* MarginLeft */33,
            _0: CssPropertyValue$Ress.marginLeft(v)
          };
  };
  var marginLeftString = function (v) {
    return {
            TAG: /* MarginLeft */33,
            _0: v
          };
  };
  var marginLeftNumber = function (v) {
    return {
            TAG: /* MarginLeft */33,
            _0: v
          };
  };
  var padding = function (v) {
    return {
            TAG: /* Padding */34,
            _0: CssPropertyValue$Ress.padding(v)
          };
  };
  var padding2 = function (tb, lr) {
    return {
            TAG: /* Padding */34,
            _0: CssPropertyValue$Ress.padding2(tb, lr)
          };
  };
  var padding3 = function (top, lr, bottom) {
    return {
            TAG: /* Padding */34,
            _0: CssPropertyValue$Ress.padding3(top, lr, bottom)
          };
  };
  var padding4 = function (top, right, bottom, left) {
    return {
            TAG: /* Padding */34,
            _0: CssPropertyValue$Ress.padding4(top, right, bottom, left)
          };
  };
  var paddingString = function (v) {
    return {
            TAG: /* Padding */34,
            _0: v
          };
  };
  var paddingNumber = function (v) {
    return {
            TAG: /* Padding */34,
            _0: v
          };
  };
  var paddingTop = function (v) {
    return {
            TAG: /* PaddingTop */35,
            _0: CssPropertyValue$Ress.paddingTop(v)
          };
  };
  var paddingTopString = function (v) {
    return {
            TAG: /* PaddingTop */35,
            _0: v
          };
  };
  var paddingTopNumber = function (v) {
    return {
            TAG: /* PaddingTop */35,
            _0: v
          };
  };
  var paddingRight = function (v) {
    return {
            TAG: /* PaddingRight */37,
            _0: CssPropertyValue$Ress.paddingRight(v)
          };
  };
  var paddingRightString = function (v) {
    return {
            TAG: /* PaddingRight */37,
            _0: v
          };
  };
  var paddingRightNumber = function (v) {
    return {
            TAG: /* PaddingRight */37,
            _0: v
          };
  };
  var paddingBottom = function (v) {
    return {
            TAG: /* PaddingBottom */36,
            _0: CssPropertyValue$Ress.paddingBottom(v)
          };
  };
  var paddingBottomString = function (v) {
    return {
            TAG: /* PaddingBottom */36,
            _0: v
          };
  };
  var paddingBottomNumber = function (v) {
    return {
            TAG: /* PaddingBottom */36,
            _0: v
          };
  };
  var paddingLeft = function (v) {
    return {
            TAG: /* PaddingLeft */38,
            _0: CssPropertyValue$Ress.paddingLeft(v)
          };
  };
  var paddingLeftString = function (v) {
    return {
            TAG: /* PaddingLeft */38,
            _0: v
          };
  };
  var paddingLeftNumber = function (v) {
    return {
            TAG: /* PaddingLeft */38,
            _0: v
          };
  };
  var clear = function (v) {
    return {
            TAG: /* Clear */40,
            _0: CssPropertyValue$Ress.clear(v)
          };
  };
  var color = function (v) {
    return {
            TAG: /* Color */39,
            _0: CssPropertyValue$Ress.color(v)
          };
  };
  var colorString = function (v) {
    return {
            TAG: /* Color */39,
            _0: v
          };
  };
  var cursor = function (v) {
    return {
            TAG: /* Cursor */41,
            _0: CssPropertyValue$Ress.cursor(v)
          };
  };
  var cursor1 = function (i, k) {
    return {
            TAG: /* Cursor */41,
            _0: CssPropertyValue$Ress.cursor1(i, k)
          };
  };
  var cursor2 = function (i1, i2, k) {
    return {
            TAG: /* Cursor */41,
            _0: CssPropertyValue$Ress.cursor2(i1, i2, k)
          };
  };
  var cursor3 = function (i1, i2, i3, k) {
    return {
            TAG: /* Cursor */41,
            _0: CssPropertyValue$Ress.cursor3(i1, i2, i3, k)
          };
  };
  var cursor4 = function (i1, i2, i3, i4, k) {
    return {
            TAG: /* Cursor */41,
            _0: CssPropertyValue$Ress.cursor4(i1, i2, i3, i4, k)
          };
  };
  var cursorString = function (v) {
    return {
            TAG: /* Cursor */41,
            _0: v
          };
  };
  return {
          style: style,
          selector: selector,
          fontFace: fontFace,
          property: property,
          propertyNumber: propertyNumber,
          propertyInteger: propertyInteger,
          border: border,
          borderString: borderString,
          borderTop: borderTop,
          borderTopString: borderTopString,
          borderLeft: borderLeft,
          borderLeftString: borderLeftString,
          borderRight: borderRight,
          borderRightString: borderRightString,
          borderBottom: borderBottom,
          borderBottomString: borderBottomString,
          borderColor: borderColor,
          borderColor2: borderColor2,
          borderColor3: borderColor3,
          borderColor4: borderColor4,
          borderColorString: borderColorString,
          borderTopColor: borderTopColor,
          borderTopColorString: borderTopColorString,
          borderRightColor: borderRightColor,
          borderRightColorString: borderRightColorString,
          borderBottomColor: borderBottomColor,
          borderBottomColorString: borderBottomColorString,
          borderLeftColor: borderLeftColor,
          borderLeftColorString: borderLeftColorString,
          borderStyle: borderStyle,
          borderStyle2: borderStyle2,
          borderStyle3: borderStyle3,
          borderStyle4: borderStyle4,
          borderStyleString: borderStyleString,
          borderTopStyle: borderTopStyle,
          borderTopStyleString: borderTopStyleString,
          borderRightStyle: borderRightStyle,
          borderRightStyleString: borderRightStyleString,
          borderBottomStyle: borderBottomStyle,
          borderBottomStyleString: borderBottomStyleString,
          borderLeftStyle: borderLeftStyle,
          borderLeftStyleString: borderLeftStyleString,
          borderWidth: borderWidth,
          borderWidth2: borderWidth2,
          borderWidth3: borderWidth3,
          borderWidth4: borderWidth4,
          borderWidthString: borderWidthString,
          borderTopWidth: borderTopWidth,
          borderTopWidthString: borderTopWidthString,
          borderRightWidth: borderRightWidth,
          borderRightWidthString: borderRightWidthString,
          borderBottomWidth: borderBottomWidth,
          borderBottomWidthString: borderBottomWidthString,
          borderLeftWidth: borderLeftWidth,
          borderLeftWidthString: borderLeftWidthString,
          background: background,
          backgroundString: backgroundString,
          background2: background2,
          background3: background3,
          background4: background4,
          backgroundAttachment: backgroundAttachment,
          backgroundAttachment2: backgroundAttachment2,
          backgroundAttachment3: backgroundAttachment3,
          backgroundAttachment4: backgroundAttachment4,
          backgroundAttachmentString: backgroundAttachmentString,
          backgroundColor: backgroundColor,
          backgroundColorString: backgroundColorString,
          backgroundImage: backgroundImage,
          backgroundImage2: backgroundImage2,
          backgroundImage3: backgroundImage3,
          backgroundImage4: backgroundImage4,
          backgroundImageString: backgroundImageString,
          backgroundPosition: backgroundPosition,
          backgroundPosition2: backgroundPosition2,
          backgroundPosition3: backgroundPosition3,
          backgroundPosition4: backgroundPosition4,
          backgroundPositionString: backgroundPositionString,
          backgroundStyle: backgroundStyle,
          backgroundStyle2: backgroundStyle2,
          backgroundStyle3: backgroundStyle3,
          backgroundStyle4: backgroundStyle4,
          backgroundStyleString: backgroundStyleString,
          margin: margin,
          margin2: margin2,
          margin3: margin3,
          margin4: margin4,
          marginString: marginString,
          marginNumber: marginNumber,
          marginTop: marginTop,
          marginTopString: marginTopString,
          marginTopNumber: marginTopNumber,
          marginRight: marginRight,
          marginRightString: marginRightString,
          marginRightNumber: marginRightNumber,
          marginBottom: marginBottom,
          marginBottomString: marginBottomString,
          marginBottomNumber: marginBottomNumber,
          marginLeft: marginLeft,
          marginLeftString: marginLeftString,
          marginLeftNumber: marginLeftNumber,
          padding: padding,
          padding2: padding2,
          padding3: padding3,
          padding4: padding4,
          paddingString: paddingString,
          paddingNumber: paddingNumber,
          paddingTop: paddingTop,
          paddingTopString: paddingTopString,
          paddingTopNumber: paddingTopNumber,
          paddingRight: paddingRight,
          paddingRightString: paddingRightString,
          paddingRightNumber: paddingRightNumber,
          paddingBottom: paddingBottom,
          paddingBottomString: paddingBottomString,
          paddingBottomNumber: paddingBottomNumber,
          paddingLeft: paddingLeft,
          paddingLeftString: paddingLeftString,
          paddingLeftNumber: paddingLeftNumber,
          clear: clear,
          color: color,
          colorString: colorString,
          cursor: cursor,
          cursor1: cursor1,
          cursor2: cursor2,
          cursor3: cursor3,
          cursor4: cursor4,
          cursorString: cursorString
        };
}

exports.Make = Make;
/* No side effect */
