// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var CssAdvancedDeclaration$Ress = require("./CssAdvancedDeclaration.js");

function Make(funarg) {
  var Declaration = CssAdvancedDeclaration$Ress.Make({});
  var make = function (declarations) {
    return Js_dict.fromArray(Belt_Array.map(declarations, (function (declaration) {
                      return Curry._1(Declaration.make, declaration);
                    })));
  };
  return {
          make: make
        };
}

exports.Make = Make;
/* No side effect */
