// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(declaration) {
  var match = declaration.VAL;
  return [
          match[0],
          match[1]
        ];
}

exports.make = make;
/* No side effect */
