// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var CssStyleDeclaration$Ress = require("./CssStyleDeclaration.js");

function make(declarations) {
  return Js_dict.fromArray(Belt_Array.map(declarations, CssStyleDeclaration$Ress.make));
}

exports.make = make;
/* No side effect */
