// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function declaration(property, value) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            value
          ]
        };
}

var Helper = {
  declaration: declaration
};

function Make(funarg) {
  var map = funarg.map;
  var make = function (declaration) {
    var match = declaration.VAL;
    return Curry._1(map, [
                match[0],
                match[1]
              ]);
  };
  return {
          make: make
        };
}

exports.Make = Make;
exports.Helper = Helper;
/* No side effect */
