// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(declaration) {
  var match = declaration.VAL;
  return [
          match[0],
          match[1]
        ];
}

function declaration(property, value) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            value
          ]
        };
}

var Helper = {
  declaration: declaration
};

exports.make = make;
exports.Helper = Helper;
/* No side effect */
