// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Theme;

var Palette;

var Color;

var ActionColor;

var AugmentColor;

var BackgroundColor;

var CommonColors;

var PaletteColor;

var PaletteColorOptions;

var TextColor;

var TonalOffset;

var Typography;

exports.Theme = Theme;
exports.Palette = Palette;
exports.Color = Color;
exports.ActionColor = ActionColor;
exports.AugmentColor = AugmentColor;
exports.BackgroundColor = BackgroundColor;
exports.CommonColors = CommonColors;
exports.PaletteColor = PaletteColor;
exports.PaletteColorOptions = PaletteColorOptions;
exports.TextColor = TextColor;
exports.TonalOffset = TonalOffset;
exports.Typography = Typography;
/* No side effect */
