// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");
var Styles = require("@material-ui/core/styles");

function make(palette, param) {
  var tmp = {};
  if (palette !== undefined) {
    tmp.palette = Caml_option.valFromOption(palette);
  }
  return Styles.createTheme(tmp);
}

exports.make = make;
/* @material-ui/core/styles Not a pure module */
