// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssMui5$Ress = require("resstype/src/mui5/CssMui5.js");

var Syntax = CssMui5$Ress.Syntax;

var DeclarationBlock = CssMui5$Ress.DeclarationBlock;

var Statements = CssMui5$Ress.Statements;

var sx = CssMui5$Ress.sx;

var styles = CssMui5$Ress.styles;

var Type = CssMui5$Ress.Type;

var Background = CssMui5$Ress.Background;

var BackgroundAttachment = CssMui5$Ress.BackgroundAttachment;

var BackgroundColor = CssMui5$Ress.BackgroundColor;

var BackgroundImage = CssMui5$Ress.BackgroundImage;

var BackgroundPosition = CssMui5$Ress.BackgroundPosition;

var BackgroundStyle = CssMui5$Ress.BackgroundStyle;

var Border = CssMui5$Ress.Border;

var BorderTop = CssMui5$Ress.BorderTop;

var BorderRight = CssMui5$Ress.BorderRight;

var BorderBottom = CssMui5$Ress.BorderBottom;

var BorderLeft = CssMui5$Ress.BorderLeft;

var BorderTopColor = CssMui5$Ress.BorderTopColor;

var BorderRightColor = CssMui5$Ress.BorderRightColor;

var BorderBottomColor = CssMui5$Ress.BorderBottomColor;

var BorderLeftColor = CssMui5$Ress.BorderLeftColor;

var BorderTopStyle = CssMui5$Ress.BorderTopStyle;

var BorderRightStyle = CssMui5$Ress.BorderRightStyle;

var BorderBottomStyle = CssMui5$Ress.BorderBottomStyle;

var BorderLeftStyle = CssMui5$Ress.BorderLeftStyle;

var BorderTopWidth = CssMui5$Ress.BorderTopWidth;

var BorderRightWidth = CssMui5$Ress.BorderRightWidth;

var BorderBottomWidth = CssMui5$Ress.BorderBottomWidth;

var BorderLeftWidth = CssMui5$Ress.BorderLeftWidth;

var BorderColor = CssMui5$Ress.BorderColor;

var BorderStyle = CssMui5$Ress.BorderStyle;

var BorderWidth = CssMui5$Ress.BorderWidth;

var Clear = CssMui5$Ress.Clear;

var Color = CssMui5$Ress.Color;

var Cursor = CssMui5$Ress.Cursor;

var FontFamily = CssMui5$Ress.FontFamily;

var FontWeight = CssMui5$Ress.FontWeight;

var Margin = CssMui5$Ress.Margin;

var MarginTop = CssMui5$Ress.MarginTop;

var MarginRight = CssMui5$Ress.MarginRight;

var MarginBottom = CssMui5$Ress.MarginBottom;

var MarginLeft = CssMui5$Ress.MarginLeft;

var Padding = CssMui5$Ress.Padding;

var PaddingTop = CssMui5$Ress.PaddingTop;

var PaddingRight = CssMui5$Ress.PaddingRight;

var PaddingBottom = CssMui5$Ress.PaddingBottom;

var PaddingLeft = CssMui5$Ress.PaddingLeft;

var str = CssMui5$Ress.str;

var num = CssMui5$Ress.num;

var $$int = CssMui5$Ress.$$int;

var pct = CssMui5$Ress.pct;

var ratio = CssMui5$Ress.ratio;

var fr = CssMui5$Ress.fr;

var ch = CssMui5$Ress.ch;

var em = CssMui5$Ress.em;

var ex = CssMui5$Ress.ex;

var rem = CssMui5$Ress.rem;

var vh = CssMui5$Ress.vh;

var vw = CssMui5$Ress.vw;

var vmin = CssMui5$Ress.vmin;

var vmax = CssMui5$Ress.vmax;

var px = CssMui5$Ress.px;

var cm = CssMui5$Ress.cm;

var mm = CssMui5$Ress.mm;

var inch = CssMui5$Ress.inch;

var pc = CssMui5$Ress.pc;

var pt = CssMui5$Ress.pt;

var deg = CssMui5$Ress.deg;

var grad = CssMui5$Ress.grad;

var rad = CssMui5$Ress.rad;

var turn = CssMui5$Ress.turn;

var s = CssMui5$Ress.s;

var ms = CssMui5$Ress.ms;

var hz = CssMui5$Ress.hz;

var kHz = CssMui5$Ress.kHz;

var dpi = CssMui5$Ress.dpi;

var dpcm = CssMui5$Ress.dpcm;

var dppx = CssMui5$Ress.dppx;

var x = CssMui5$Ress.x;

var position2 = CssMui5$Ress.position2;

var position3 = CssMui5$Ress.position3;

var position4 = CssMui5$Ress.position4;

var src = CssMui5$Ress.src;

var bgLayer = CssMui5$Ress.bgLayer;

var bgSize2 = CssMui5$Ress.bgSize2;

var hsl = CssMui5$Ress.hsl;

var hsla = CssMui5$Ress.hsla;

var rgb = CssMui5$Ress.rgb;

var rgba = CssMui5$Ress.rgba;

var hexColor = CssMui5$Ress.hexColor;

var url = CssMui5$Ress.url;

var image = CssMui5$Ress.image;

var linearColorStop2 = CssMui5$Ress.linearColorStop2;

var linearColorStop3 = CssMui5$Ress.linearColorStop3;

var linearGradient = CssMui5$Ress.linearGradient;

var linearGradient2 = CssMui5$Ress.linearGradient2;

var linearGradient3 = CssMui5$Ress.linearGradient3;

var linearGradient4 = CssMui5$Ress.linearGradient4;

var repeatingLinearGradient = CssMui5$Ress.repeatingLinearGradient;

var repeatingLinearGradient2 = CssMui5$Ress.repeatingLinearGradient2;

var repeatingLinearGradient3 = CssMui5$Ress.repeatingLinearGradient3;

var repeatingLinearGradient4 = CssMui5$Ress.repeatingLinearGradient4;

var radialGradient = CssMui5$Ress.radialGradient;

var radialGradient2 = CssMui5$Ress.radialGradient2;

var radialGradient3 = CssMui5$Ress.radialGradient3;

var radialGradient4 = CssMui5$Ress.radialGradient4;

var repeatingRadialGradient = CssMui5$Ress.repeatingRadialGradient;

var repeatingRadialGradient2 = CssMui5$Ress.repeatingRadialGradient2;

var repeatingRadialGradient3 = CssMui5$Ress.repeatingRadialGradient3;

var repeatingRadialGradient4 = CssMui5$Ress.repeatingRadialGradient4;

var conicGradient = CssMui5$Ress.conicGradient;

var conicGradient2 = CssMui5$Ress.conicGradient2;

var conicGradient3 = CssMui5$Ress.conicGradient3;

var conicGradient4 = CssMui5$Ress.conicGradient4;

var repeatingConicGradient = CssMui5$Ress.repeatingConicGradient;

var repeatingConicGradient2 = CssMui5$Ress.repeatingConicGradient2;

var repeatingConicGradient3 = CssMui5$Ress.repeatingConicGradient3;

var repeatingConicGradient4 = CssMui5$Ress.repeatingConicGradient4;

var font = CssMui5$Ress.font;

var rule = CssMui5$Ress.rule;

var regularAtRule = CssMui5$Ress.regularAtRule;

var nestedAtRule = CssMui5$Ress.nestedAtRule;

var fontFace = CssMui5$Ress.fontFace;

var $$FontFace = CssMui5$Ress.$$FontFace;

var pseudoClass = CssMui5$Ress.pseudoClass;

var hover = CssMui5$Ress.hover;

var background = CssMui5$Ress.background;

var background2 = CssMui5$Ress.background2;

var background3 = CssMui5$Ress.background3;

var background4 = CssMui5$Ress.background4;

var backgroundUnion = CssMui5$Ress.backgroundUnion;

var backgroundString = CssMui5$Ress.backgroundString;

var backgroundAttachment = CssMui5$Ress.backgroundAttachment;

var backgroundAttachment2 = CssMui5$Ress.backgroundAttachment2;

var backgroundAttachment3 = CssMui5$Ress.backgroundAttachment3;

var backgroundAttachment4 = CssMui5$Ress.backgroundAttachment4;

var backgroundAttachmentUnion = CssMui5$Ress.backgroundAttachmentUnion;

var backgroundAttachmentString = CssMui5$Ress.backgroundAttachmentString;

var backgroundColor = CssMui5$Ress.backgroundColor;

var backgroundColorUnion = CssMui5$Ress.backgroundColorUnion;

var backgroundColorString = CssMui5$Ress.backgroundColorString;

var backgroundImage = CssMui5$Ress.backgroundImage;

var backgroundImage2 = CssMui5$Ress.backgroundImage2;

var backgroundImage3 = CssMui5$Ress.backgroundImage3;

var backgroundImage4 = CssMui5$Ress.backgroundImage4;

var backgroundImageUnion = CssMui5$Ress.backgroundImageUnion;

var backgroundImageString = CssMui5$Ress.backgroundImageString;

var backgroundPosition = CssMui5$Ress.backgroundPosition;

var backgroundPosition2 = CssMui5$Ress.backgroundPosition2;

var backgroundPosition3 = CssMui5$Ress.backgroundPosition3;

var backgroundPosition4 = CssMui5$Ress.backgroundPosition4;

var backgroundPositionUnion = CssMui5$Ress.backgroundPositionUnion;

var backgroundPositionString = CssMui5$Ress.backgroundPositionString;

var backgroundStyle = CssMui5$Ress.backgroundStyle;

var backgroundStyle2 = CssMui5$Ress.backgroundStyle2;

var backgroundStyle3 = CssMui5$Ress.backgroundStyle3;

var backgroundStyle4 = CssMui5$Ress.backgroundStyle4;

var backgroundStyleUnion = CssMui5$Ress.backgroundStyleUnion;

var backgroundStyleString = CssMui5$Ress.backgroundStyleString;

var border = CssMui5$Ress.border;

var borderUnion = CssMui5$Ress.borderUnion;

var borderString = CssMui5$Ress.borderString;

var borderTop = CssMui5$Ress.borderTop;

var borderTopUnion = CssMui5$Ress.borderTopUnion;

var borderTopString = CssMui5$Ress.borderTopString;

var borderRight = CssMui5$Ress.borderRight;

var borderRightUnion = CssMui5$Ress.borderRightUnion;

var borderRightString = CssMui5$Ress.borderRightString;

var borderBottom = CssMui5$Ress.borderBottom;

var borderBottomUnion = CssMui5$Ress.borderBottomUnion;

var borderBottomString = CssMui5$Ress.borderBottomString;

var borderLeft = CssMui5$Ress.borderLeft;

var borderLeftUnion = CssMui5$Ress.borderLeftUnion;

var borderLeftString = CssMui5$Ress.borderLeftString;

var borderTopColor = CssMui5$Ress.borderTopColor;

var borderTopColorUnion = CssMui5$Ress.borderTopColorUnion;

var borderTopColorString = CssMui5$Ress.borderTopColorString;

var borderRightColor = CssMui5$Ress.borderRightColor;

var borderRightColorUnion = CssMui5$Ress.borderRightColorUnion;

var borderRightColorString = CssMui5$Ress.borderRightColorString;

var borderBottomColor = CssMui5$Ress.borderBottomColor;

var borderBottomColorUnion = CssMui5$Ress.borderBottomColorUnion;

var borderBottomColorString = CssMui5$Ress.borderBottomColorString;

var borderLeftColor = CssMui5$Ress.borderLeftColor;

var borderLeftColorUnion = CssMui5$Ress.borderLeftColorUnion;

var borderLeftColorString = CssMui5$Ress.borderLeftColorString;

var borderTopStyle = CssMui5$Ress.borderTopStyle;

var borderTopStyleUnion = CssMui5$Ress.borderTopStyleUnion;

var borderTopStyleString = CssMui5$Ress.borderTopStyleString;

var borderRightStyle = CssMui5$Ress.borderRightStyle;

var borderRightStyleUnion = CssMui5$Ress.borderRightStyleUnion;

var borderRightStyleString = CssMui5$Ress.borderRightStyleString;

var borderBottomStyle = CssMui5$Ress.borderBottomStyle;

var borderBottomStyleUnion = CssMui5$Ress.borderBottomStyleUnion;

var borderBottomStyleString = CssMui5$Ress.borderBottomStyleString;

var borderLeftStyle = CssMui5$Ress.borderLeftStyle;

var borderLeftStyleUnion = CssMui5$Ress.borderLeftStyleUnion;

var borderLeftStyleString = CssMui5$Ress.borderLeftStyleString;

var borderTopWidth = CssMui5$Ress.borderTopWidth;

var borderTopWidthUnion = CssMui5$Ress.borderTopWidthUnion;

var borderTopWidthString = CssMui5$Ress.borderTopWidthString;

var borderRightWidth = CssMui5$Ress.borderRightWidth;

var borderRightWidthUnion = CssMui5$Ress.borderRightWidthUnion;

var borderRightWidthString = CssMui5$Ress.borderRightWidthString;

var borderBottomWidth = CssMui5$Ress.borderBottomWidth;

var borderBottomWidthUnion = CssMui5$Ress.borderBottomWidthUnion;

var borderBottomWidthString = CssMui5$Ress.borderBottomWidthString;

var borderLeftWidth = CssMui5$Ress.borderLeftWidth;

var borderLeftWidthUnion = CssMui5$Ress.borderLeftWidthUnion;

var borderLeftWidthString = CssMui5$Ress.borderLeftWidthString;

var borderColor = CssMui5$Ress.borderColor;

var borderColor2 = CssMui5$Ress.borderColor2;

var borderColor3 = CssMui5$Ress.borderColor3;

var borderColor4 = CssMui5$Ress.borderColor4;

var borderColorUnion = CssMui5$Ress.borderColorUnion;

var borderColorString = CssMui5$Ress.borderColorString;

var borderStyle = CssMui5$Ress.borderStyle;

var borderStyle2 = CssMui5$Ress.borderStyle2;

var borderStyle3 = CssMui5$Ress.borderStyle3;

var borderStyle4 = CssMui5$Ress.borderStyle4;

var borderStyleUnion = CssMui5$Ress.borderStyleUnion;

var borderStyleString = CssMui5$Ress.borderStyleString;

var borderWidth = CssMui5$Ress.borderWidth;

var borderWidth2 = CssMui5$Ress.borderWidth2;

var borderWidth3 = CssMui5$Ress.borderWidth3;

var borderWidth4 = CssMui5$Ress.borderWidth4;

var borderWidthUnion = CssMui5$Ress.borderWidthUnion;

var borderWidthString = CssMui5$Ress.borderWidthString;

var clear = CssMui5$Ress.clear;

var clearUnion = CssMui5$Ress.clearUnion;

var clearString = CssMui5$Ress.clearString;

var color = CssMui5$Ress.color;

var colorUnion = CssMui5$Ress.colorUnion;

var colorString = CssMui5$Ress.colorString;

var cursor = CssMui5$Ress.cursor;

var cursor1 = CssMui5$Ress.cursor1;

var cursor2 = CssMui5$Ress.cursor2;

var cursor3 = CssMui5$Ress.cursor3;

var cursor4 = CssMui5$Ress.cursor4;

var cursorUnion = CssMui5$Ress.cursorUnion;

var cursorString = CssMui5$Ress.cursorString;

var fontFamily = CssMui5$Ress.fontFamily;

var fontFamily2 = CssMui5$Ress.fontFamily2;

var fontFamily3 = CssMui5$Ress.fontFamily3;

var fontFamily4 = CssMui5$Ress.fontFamily4;

var fontFamilyUnion = CssMui5$Ress.fontFamilyUnion;

var fontFamilyString = CssMui5$Ress.fontFamilyString;

var fontWeight = CssMui5$Ress.fontWeight;

var fontWeightUnion = CssMui5$Ress.fontWeightUnion;

var fontWeightString = CssMui5$Ress.fontWeightString;

var fontWeightInteger = CssMui5$Ress.fontWeightInteger;

var margin = CssMui5$Ress.margin;

var margin2 = CssMui5$Ress.margin2;

var margin3 = CssMui5$Ress.margin3;

var margin4 = CssMui5$Ress.margin4;

var marginUnion = CssMui5$Ress.marginUnion;

var marginString = CssMui5$Ress.marginString;

var marginNumber = CssMui5$Ress.marginNumber;

var marginTop = CssMui5$Ress.marginTop;

var marginTopUnion = CssMui5$Ress.marginTopUnion;

var marginTopString = CssMui5$Ress.marginTopString;

var marginTopNumber = CssMui5$Ress.marginTopNumber;

var marginRight = CssMui5$Ress.marginRight;

var marginRightUnion = CssMui5$Ress.marginRightUnion;

var marginRightString = CssMui5$Ress.marginRightString;

var marginRightNumber = CssMui5$Ress.marginRightNumber;

var marginBottom = CssMui5$Ress.marginBottom;

var marginBottomUnion = CssMui5$Ress.marginBottomUnion;

var marginBottomString = CssMui5$Ress.marginBottomString;

var marginBottomNumber = CssMui5$Ress.marginBottomNumber;

var marginLeft = CssMui5$Ress.marginLeft;

var marginLeftUnion = CssMui5$Ress.marginLeftUnion;

var marginLeftString = CssMui5$Ress.marginLeftString;

var marginLeftNumber = CssMui5$Ress.marginLeftNumber;

var padding = CssMui5$Ress.padding;

var padding2 = CssMui5$Ress.padding2;

var padding3 = CssMui5$Ress.padding3;

var padding4 = CssMui5$Ress.padding4;

var paddingUnion = CssMui5$Ress.paddingUnion;

var paddingString = CssMui5$Ress.paddingString;

var paddingNumber = CssMui5$Ress.paddingNumber;

var paddingTop = CssMui5$Ress.paddingTop;

var paddingTopUnion = CssMui5$Ress.paddingTopUnion;

var paddingTopString = CssMui5$Ress.paddingTopString;

var paddingTopNumber = CssMui5$Ress.paddingTopNumber;

var paddingRight = CssMui5$Ress.paddingRight;

var paddingRightUnion = CssMui5$Ress.paddingRightUnion;

var paddingRightString = CssMui5$Ress.paddingRightString;

var paddingRightNumber = CssMui5$Ress.paddingRightNumber;

var paddingBottom = CssMui5$Ress.paddingBottom;

var paddingBottomUnion = CssMui5$Ress.paddingBottomUnion;

var paddingBottomString = CssMui5$Ress.paddingBottomString;

var paddingBottomNumber = CssMui5$Ress.paddingBottomNumber;

var paddingLeft = CssMui5$Ress.paddingLeft;

var paddingLeftUnion = CssMui5$Ress.paddingLeftUnion;

var paddingLeftString = CssMui5$Ress.paddingLeftString;

var paddingLeftNumber = CssMui5$Ress.paddingLeftNumber;

var declaration = CssMui5$Ress.declaration;

var backgroundFn = CssMui5$Ress.backgroundFn;

var backgroundAttachmentFn = CssMui5$Ress.backgroundAttachmentFn;

var backgroundColorFn = CssMui5$Ress.backgroundColorFn;

var backgroundImageFn = CssMui5$Ress.backgroundImageFn;

var backgroundPositionFn = CssMui5$Ress.backgroundPositionFn;

var backgroundStyleFn = CssMui5$Ress.backgroundStyleFn;

var borderFn = CssMui5$Ress.borderFn;

var borderTopFn = CssMui5$Ress.borderTopFn;

var borderRightFn = CssMui5$Ress.borderRightFn;

var borderBottomFn = CssMui5$Ress.borderBottomFn;

var borderLeftFn = CssMui5$Ress.borderLeftFn;

var borderTopColorFn = CssMui5$Ress.borderTopColorFn;

var borderRightColorFn = CssMui5$Ress.borderRightColorFn;

var borderBottomColorFn = CssMui5$Ress.borderBottomColorFn;

var borderLeftColorFn = CssMui5$Ress.borderLeftColorFn;

var borderTopStyleFn = CssMui5$Ress.borderTopStyleFn;

var borderRightStyleFn = CssMui5$Ress.borderRightStyleFn;

var borderBottomStyleFn = CssMui5$Ress.borderBottomStyleFn;

var borderLeftStyleFn = CssMui5$Ress.borderLeftStyleFn;

var borderTopWidthFn = CssMui5$Ress.borderTopWidthFn;

var borderRightWidthFn = CssMui5$Ress.borderRightWidthFn;

var borderBottomWidthFn = CssMui5$Ress.borderBottomWidthFn;

var borderLeftWidthFn = CssMui5$Ress.borderLeftWidthFn;

var borderColorFn = CssMui5$Ress.borderColorFn;

var borderStyleFn = CssMui5$Ress.borderStyleFn;

var borderWidthFn = CssMui5$Ress.borderWidthFn;

var clearFn = CssMui5$Ress.clearFn;

var colorFn = CssMui5$Ress.colorFn;

var cursorFn = CssMui5$Ress.cursorFn;

var fontFamilyFn = CssMui5$Ress.fontFamilyFn;

var fontWeightFn = CssMui5$Ress.fontWeightFn;

var marginFn = CssMui5$Ress.marginFn;

var marginTopFn = CssMui5$Ress.marginTopFn;

var marginRightFn = CssMui5$Ress.marginRightFn;

var marginBottomFn = CssMui5$Ress.marginBottomFn;

var marginLeftFn = CssMui5$Ress.marginLeftFn;

var paddingFn = CssMui5$Ress.paddingFn;

var paddingTopFn = CssMui5$Ress.paddingTopFn;

var paddingRightFn = CssMui5$Ress.paddingRightFn;

var paddingBottomFn = CssMui5$Ress.paddingBottomFn;

var paddingLeftFn = CssMui5$Ress.paddingLeftFn;

exports.Syntax = Syntax;
exports.DeclarationBlock = DeclarationBlock;
exports.Statements = Statements;
exports.sx = sx;
exports.styles = styles;
exports.Type = Type;
exports.Background = Background;
exports.BackgroundAttachment = BackgroundAttachment;
exports.BackgroundColor = BackgroundColor;
exports.BackgroundImage = BackgroundImage;
exports.BackgroundPosition = BackgroundPosition;
exports.BackgroundStyle = BackgroundStyle;
exports.Border = Border;
exports.BorderTop = BorderTop;
exports.BorderRight = BorderRight;
exports.BorderBottom = BorderBottom;
exports.BorderLeft = BorderLeft;
exports.BorderTopColor = BorderTopColor;
exports.BorderRightColor = BorderRightColor;
exports.BorderBottomColor = BorderBottomColor;
exports.BorderLeftColor = BorderLeftColor;
exports.BorderTopStyle = BorderTopStyle;
exports.BorderRightStyle = BorderRightStyle;
exports.BorderBottomStyle = BorderBottomStyle;
exports.BorderLeftStyle = BorderLeftStyle;
exports.BorderTopWidth = BorderTopWidth;
exports.BorderRightWidth = BorderRightWidth;
exports.BorderBottomWidth = BorderBottomWidth;
exports.BorderLeftWidth = BorderLeftWidth;
exports.BorderColor = BorderColor;
exports.BorderStyle = BorderStyle;
exports.BorderWidth = BorderWidth;
exports.Clear = Clear;
exports.Color = Color;
exports.Cursor = Cursor;
exports.FontFamily = FontFamily;
exports.FontWeight = FontWeight;
exports.Margin = Margin;
exports.MarginTop = MarginTop;
exports.MarginRight = MarginRight;
exports.MarginBottom = MarginBottom;
exports.MarginLeft = MarginLeft;
exports.Padding = Padding;
exports.PaddingTop = PaddingTop;
exports.PaddingRight = PaddingRight;
exports.PaddingBottom = PaddingBottom;
exports.PaddingLeft = PaddingLeft;
exports.str = str;
exports.num = num;
exports.$$int = $$int;
exports.pct = pct;
exports.ratio = ratio;
exports.fr = fr;
exports.ch = ch;
exports.em = em;
exports.ex = ex;
exports.rem = rem;
exports.vh = vh;
exports.vw = vw;
exports.vmin = vmin;
exports.vmax = vmax;
exports.px = px;
exports.cm = cm;
exports.mm = mm;
exports.inch = inch;
exports.pc = pc;
exports.pt = pt;
exports.deg = deg;
exports.grad = grad;
exports.rad = rad;
exports.turn = turn;
exports.s = s;
exports.ms = ms;
exports.hz = hz;
exports.kHz = kHz;
exports.dpi = dpi;
exports.dpcm = dpcm;
exports.dppx = dppx;
exports.x = x;
exports.position2 = position2;
exports.position3 = position3;
exports.position4 = position4;
exports.src = src;
exports.bgLayer = bgLayer;
exports.bgSize2 = bgSize2;
exports.hsl = hsl;
exports.hsla = hsla;
exports.rgb = rgb;
exports.rgba = rgba;
exports.hexColor = hexColor;
exports.url = url;
exports.image = image;
exports.linearColorStop2 = linearColorStop2;
exports.linearColorStop3 = linearColorStop3;
exports.linearGradient = linearGradient;
exports.linearGradient2 = linearGradient2;
exports.linearGradient3 = linearGradient3;
exports.linearGradient4 = linearGradient4;
exports.repeatingLinearGradient = repeatingLinearGradient;
exports.repeatingLinearGradient2 = repeatingLinearGradient2;
exports.repeatingLinearGradient3 = repeatingLinearGradient3;
exports.repeatingLinearGradient4 = repeatingLinearGradient4;
exports.radialGradient = radialGradient;
exports.radialGradient2 = radialGradient2;
exports.radialGradient3 = radialGradient3;
exports.radialGradient4 = radialGradient4;
exports.repeatingRadialGradient = repeatingRadialGradient;
exports.repeatingRadialGradient2 = repeatingRadialGradient2;
exports.repeatingRadialGradient3 = repeatingRadialGradient3;
exports.repeatingRadialGradient4 = repeatingRadialGradient4;
exports.conicGradient = conicGradient;
exports.conicGradient2 = conicGradient2;
exports.conicGradient3 = conicGradient3;
exports.conicGradient4 = conicGradient4;
exports.repeatingConicGradient = repeatingConicGradient;
exports.repeatingConicGradient2 = repeatingConicGradient2;
exports.repeatingConicGradient3 = repeatingConicGradient3;
exports.repeatingConicGradient4 = repeatingConicGradient4;
exports.font = font;
exports.rule = rule;
exports.regularAtRule = regularAtRule;
exports.nestedAtRule = nestedAtRule;
exports.fontFace = fontFace;
exports.$$FontFace = $$FontFace;
exports.pseudoClass = pseudoClass;
exports.hover = hover;
exports.background = background;
exports.background2 = background2;
exports.background3 = background3;
exports.background4 = background4;
exports.backgroundUnion = backgroundUnion;
exports.backgroundString = backgroundString;
exports.backgroundAttachment = backgroundAttachment;
exports.backgroundAttachment2 = backgroundAttachment2;
exports.backgroundAttachment3 = backgroundAttachment3;
exports.backgroundAttachment4 = backgroundAttachment4;
exports.backgroundAttachmentUnion = backgroundAttachmentUnion;
exports.backgroundAttachmentString = backgroundAttachmentString;
exports.backgroundColor = backgroundColor;
exports.backgroundColorUnion = backgroundColorUnion;
exports.backgroundColorString = backgroundColorString;
exports.backgroundImage = backgroundImage;
exports.backgroundImage2 = backgroundImage2;
exports.backgroundImage3 = backgroundImage3;
exports.backgroundImage4 = backgroundImage4;
exports.backgroundImageUnion = backgroundImageUnion;
exports.backgroundImageString = backgroundImageString;
exports.backgroundPosition = backgroundPosition;
exports.backgroundPosition2 = backgroundPosition2;
exports.backgroundPosition3 = backgroundPosition3;
exports.backgroundPosition4 = backgroundPosition4;
exports.backgroundPositionUnion = backgroundPositionUnion;
exports.backgroundPositionString = backgroundPositionString;
exports.backgroundStyle = backgroundStyle;
exports.backgroundStyle2 = backgroundStyle2;
exports.backgroundStyle3 = backgroundStyle3;
exports.backgroundStyle4 = backgroundStyle4;
exports.backgroundStyleUnion = backgroundStyleUnion;
exports.backgroundStyleString = backgroundStyleString;
exports.border = border;
exports.borderUnion = borderUnion;
exports.borderString = borderString;
exports.borderTop = borderTop;
exports.borderTopUnion = borderTopUnion;
exports.borderTopString = borderTopString;
exports.borderRight = borderRight;
exports.borderRightUnion = borderRightUnion;
exports.borderRightString = borderRightString;
exports.borderBottom = borderBottom;
exports.borderBottomUnion = borderBottomUnion;
exports.borderBottomString = borderBottomString;
exports.borderLeft = borderLeft;
exports.borderLeftUnion = borderLeftUnion;
exports.borderLeftString = borderLeftString;
exports.borderTopColor = borderTopColor;
exports.borderTopColorUnion = borderTopColorUnion;
exports.borderTopColorString = borderTopColorString;
exports.borderRightColor = borderRightColor;
exports.borderRightColorUnion = borderRightColorUnion;
exports.borderRightColorString = borderRightColorString;
exports.borderBottomColor = borderBottomColor;
exports.borderBottomColorUnion = borderBottomColorUnion;
exports.borderBottomColorString = borderBottomColorString;
exports.borderLeftColor = borderLeftColor;
exports.borderLeftColorUnion = borderLeftColorUnion;
exports.borderLeftColorString = borderLeftColorString;
exports.borderTopStyle = borderTopStyle;
exports.borderTopStyleUnion = borderTopStyleUnion;
exports.borderTopStyleString = borderTopStyleString;
exports.borderRightStyle = borderRightStyle;
exports.borderRightStyleUnion = borderRightStyleUnion;
exports.borderRightStyleString = borderRightStyleString;
exports.borderBottomStyle = borderBottomStyle;
exports.borderBottomStyleUnion = borderBottomStyleUnion;
exports.borderBottomStyleString = borderBottomStyleString;
exports.borderLeftStyle = borderLeftStyle;
exports.borderLeftStyleUnion = borderLeftStyleUnion;
exports.borderLeftStyleString = borderLeftStyleString;
exports.borderTopWidth = borderTopWidth;
exports.borderTopWidthUnion = borderTopWidthUnion;
exports.borderTopWidthString = borderTopWidthString;
exports.borderRightWidth = borderRightWidth;
exports.borderRightWidthUnion = borderRightWidthUnion;
exports.borderRightWidthString = borderRightWidthString;
exports.borderBottomWidth = borderBottomWidth;
exports.borderBottomWidthUnion = borderBottomWidthUnion;
exports.borderBottomWidthString = borderBottomWidthString;
exports.borderLeftWidth = borderLeftWidth;
exports.borderLeftWidthUnion = borderLeftWidthUnion;
exports.borderLeftWidthString = borderLeftWidthString;
exports.borderColor = borderColor;
exports.borderColor2 = borderColor2;
exports.borderColor3 = borderColor3;
exports.borderColor4 = borderColor4;
exports.borderColorUnion = borderColorUnion;
exports.borderColorString = borderColorString;
exports.borderStyle = borderStyle;
exports.borderStyle2 = borderStyle2;
exports.borderStyle3 = borderStyle3;
exports.borderStyle4 = borderStyle4;
exports.borderStyleUnion = borderStyleUnion;
exports.borderStyleString = borderStyleString;
exports.borderWidth = borderWidth;
exports.borderWidth2 = borderWidth2;
exports.borderWidth3 = borderWidth3;
exports.borderWidth4 = borderWidth4;
exports.borderWidthUnion = borderWidthUnion;
exports.borderWidthString = borderWidthString;
exports.clear = clear;
exports.clearUnion = clearUnion;
exports.clearString = clearString;
exports.color = color;
exports.colorUnion = colorUnion;
exports.colorString = colorString;
exports.cursor = cursor;
exports.cursor1 = cursor1;
exports.cursor2 = cursor2;
exports.cursor3 = cursor3;
exports.cursor4 = cursor4;
exports.cursorUnion = cursorUnion;
exports.cursorString = cursorString;
exports.fontFamily = fontFamily;
exports.fontFamily2 = fontFamily2;
exports.fontFamily3 = fontFamily3;
exports.fontFamily4 = fontFamily4;
exports.fontFamilyUnion = fontFamilyUnion;
exports.fontFamilyString = fontFamilyString;
exports.fontWeight = fontWeight;
exports.fontWeightUnion = fontWeightUnion;
exports.fontWeightString = fontWeightString;
exports.fontWeightInteger = fontWeightInteger;
exports.margin = margin;
exports.margin2 = margin2;
exports.margin3 = margin3;
exports.margin4 = margin4;
exports.marginUnion = marginUnion;
exports.marginString = marginString;
exports.marginNumber = marginNumber;
exports.marginTop = marginTop;
exports.marginTopUnion = marginTopUnion;
exports.marginTopString = marginTopString;
exports.marginTopNumber = marginTopNumber;
exports.marginRight = marginRight;
exports.marginRightUnion = marginRightUnion;
exports.marginRightString = marginRightString;
exports.marginRightNumber = marginRightNumber;
exports.marginBottom = marginBottom;
exports.marginBottomUnion = marginBottomUnion;
exports.marginBottomString = marginBottomString;
exports.marginBottomNumber = marginBottomNumber;
exports.marginLeft = marginLeft;
exports.marginLeftUnion = marginLeftUnion;
exports.marginLeftString = marginLeftString;
exports.marginLeftNumber = marginLeftNumber;
exports.padding = padding;
exports.padding2 = padding2;
exports.padding3 = padding3;
exports.padding4 = padding4;
exports.paddingUnion = paddingUnion;
exports.paddingString = paddingString;
exports.paddingNumber = paddingNumber;
exports.paddingTop = paddingTop;
exports.paddingTopUnion = paddingTopUnion;
exports.paddingTopString = paddingTopString;
exports.paddingTopNumber = paddingTopNumber;
exports.paddingRight = paddingRight;
exports.paddingRightUnion = paddingRightUnion;
exports.paddingRightString = paddingRightString;
exports.paddingRightNumber = paddingRightNumber;
exports.paddingBottom = paddingBottom;
exports.paddingBottomUnion = paddingBottomUnion;
exports.paddingBottomString = paddingBottomString;
exports.paddingBottomNumber = paddingBottomNumber;
exports.paddingLeft = paddingLeft;
exports.paddingLeftUnion = paddingLeftUnion;
exports.paddingLeftString = paddingLeftString;
exports.paddingLeftNumber = paddingLeftNumber;
exports.declaration = declaration;
exports.backgroundFn = backgroundFn;
exports.backgroundAttachmentFn = backgroundAttachmentFn;
exports.backgroundColorFn = backgroundColorFn;
exports.backgroundImageFn = backgroundImageFn;
exports.backgroundPositionFn = backgroundPositionFn;
exports.backgroundStyleFn = backgroundStyleFn;
exports.borderFn = borderFn;
exports.borderTopFn = borderTopFn;
exports.borderRightFn = borderRightFn;
exports.borderBottomFn = borderBottomFn;
exports.borderLeftFn = borderLeftFn;
exports.borderTopColorFn = borderTopColorFn;
exports.borderRightColorFn = borderRightColorFn;
exports.borderBottomColorFn = borderBottomColorFn;
exports.borderLeftColorFn = borderLeftColorFn;
exports.borderTopStyleFn = borderTopStyleFn;
exports.borderRightStyleFn = borderRightStyleFn;
exports.borderBottomStyleFn = borderBottomStyleFn;
exports.borderLeftStyleFn = borderLeftStyleFn;
exports.borderTopWidthFn = borderTopWidthFn;
exports.borderRightWidthFn = borderRightWidthFn;
exports.borderBottomWidthFn = borderBottomWidthFn;
exports.borderLeftWidthFn = borderLeftWidthFn;
exports.borderColorFn = borderColorFn;
exports.borderStyleFn = borderStyleFn;
exports.borderWidthFn = borderWidthFn;
exports.clearFn = clearFn;
exports.colorFn = colorFn;
exports.cursorFn = cursorFn;
exports.fontFamilyFn = fontFamilyFn;
exports.fontWeightFn = fontWeightFn;
exports.marginFn = marginFn;
exports.marginTopFn = marginTopFn;
exports.marginRightFn = marginRightFn;
exports.marginBottomFn = marginBottomFn;
exports.marginLeftFn = marginLeftFn;
exports.paddingFn = paddingFn;
exports.paddingTopFn = paddingTopFn;
exports.paddingRightFn = paddingRightFn;
exports.paddingBottomFn = paddingBottomFn;
exports.paddingLeftFn = paddingLeftFn;
/* CssMui5-Ress Not a pure module */
