// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function important(v) {
  return {
          NAME: "Important",
          VAL: v
        };
}

exports.important = important;
/* No side effect */
