// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jss = require("jss").default;
var Curry = require("rescript/lib/js/curry.js");
var Jss$Ress = require("../bindings/Jss.js");
var JssPresetDefault = require("jss-preset-default").default;

Jss.setup(JssPresetDefault());

test("jss", (function () {
        var s = Curry._1(Jss$Ress.Css.styles, [Curry._2(Jss$Ress.Css.rule, "app", [
                    Curry._2(Jss$Ress.Css.rule, "& .wrapper", [
                          Curry._8(Jss$Ress.Css.background, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Curry._1(Jss$Ress.Css.url, "image.png")),
                          Curry._1(Jss$Ress.Css.color, Curry._3(Jss$Ress.Css.rgb, 255, 255, 255)),
                          Curry._1(Jss$Ress.Css.paddingTop, Curry._1(Jss$Ress.Css.px, 24)),
                          Curry._1(Jss$Ress.Css.paddingBottom, Curry._1(Jss$Ress.Css.px, 24)),
                          Curry._1(Jss$Ress.Css.paddingLeft, Curry._1(Jss$Ress.Css.px, 40)),
                          Curry._1(Jss$Ress.Css.paddingRight, Curry._1(Jss$Ress.Css.px, 40)),
                          Curry._1(Jss$Ress.Css.marginNumber, 24)
                        ]),
                    Curry._2(Jss$Ress.Css.rule, "& .button", [
                          Curry._1(Jss$Ress.Css.color, Curry._4(Jss$Ress.Css.hsla, 360, Curry._1(Jss$Ress.Css.pct, 100), Curry._1(Jss$Ress.Css.pct, 50), 0.5)),
                          Curry._1(Jss$Ress.Css.hover, [Curry._8(Jss$Ress.Css.background, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "blue")])
                        ]),
                    Curry._1(Jss$Ress.Css.hover, [Curry._1(Jss$Ress.Css.color, "blue")])
                  ])]);
        expect(Jss.createStyleSheet(s).toString()).toMatchSnapshot();
        
      }));

/*  Not a pure module */
