// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Mui5$Ress = require("../bindings/Mui5.js");
var Box = require("@mui/material/Box").default;
var ReactTestRenderer = require("react-test-renderer");

test("mui5", (function () {
        var tree = ReactTestRenderer.create(React.createElement(Box, {
                    sx: Curry._1(Mui5$Ress.Css.sx, [
                          Curry._1(Mui5$Ress.Css.color, "blue"),
                          Curry._1(Mui5$Ress.Css.margin, Curry._1(Mui5$Ress.Css.px, 24))
                        ])
                  })).toJSON();
        expect(tree).toMatchSnapshot();
        
      }));

/*  Not a pure module */
