// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssValueString$Ress = require("../value/CssValueString.js");

var value = CssValueString$Ress.lineWidth_global;

exports.value = value;
/* No side effect */
