// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssValueString$Ress = require("../CssValueString.js");

var value = CssValueString$Ress.lineWidth_global;

function value2(tb, lr) {
  return CssValueString$Ress.lineWidth(tb) + " " + CssValueString$Ress.lineWidth(lr);
}

function value3(top, lr, bottom) {
  return CssValueString$Ress.lineWidth(top) + " " + CssValueString$Ress.lineWidth(lr) + " " + CssValueString$Ress.lineWidth(bottom);
}

function value4(top, right, bottom, left) {
  return CssValueString$Ress.lineWidth(top) + " " + CssValueString$Ress.lineWidth(right) + " " + CssValueString$Ress.lineWidth(bottom) + " " + CssValueString$Ress.lineWidth(left);
}

exports.value = value;
exports.value2 = value2;
exports.value3 = value3;
exports.value4 = value4;
/* No side effect */
