// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssValueString$Ress = require("../CssValueString.js");

var value = CssValueString$Ress.padding_global;

function value2(tb, lr) {
  return CssValueString$Ress.padding(tb) + " " + CssValueString$Ress.padding(lr);
}

function value3(top, lr, bottom) {
  return CssValueString$Ress.padding(top) + " " + CssValueString$Ress.padding(lr) + " " + CssValueString$Ress.padding(bottom);
}

function value4(top, right, bottom, left) {
  return CssValueString$Ress.padding(top) + " " + CssValueString$Ress.padding(right) + " " + CssValueString$Ress.padding(bottom) + " " + CssValueString$Ress.padding(left);
}

exports.value = value;
exports.value2 = value2;
exports.value3 = value3;
exports.value4 = value4;
/* No side effect */
