// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function make(v) {
  var match = v.VAL;
  return [
          match[0],
          match[1]
        ];
}

function MakeHelper(D) {
  var rule = function (selector, declarations) {
    return {
            NAME: "Rule",
            VAL: [
              selector,
              Curry._1(D.declarationBlock, declarations)
            ]
          };
  };
  return {
          rule: rule
        };
}

exports.make = make;
exports.MakeHelper = MakeHelper;
/* No side effect */
