// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssPropertyValue$Ress = require("@bilalvis01/rescript-csstype/src/CssPropertyValue.js");

var border = CssPropertyValue$Ress.border;

var borderColor = CssPropertyValue$Ress.borderColor;

var borderColor2 = CssPropertyValue$Ress.borderColor2;

var borderColor3 = CssPropertyValue$Ress.borderColor3;

var borderColor4 = CssPropertyValue$Ress.borderColor4;

var borderTopColor = CssPropertyValue$Ress.borderTopColor;

var borderRightColor = CssPropertyValue$Ress.borderRightColor;

var borderBottomColor = CssPropertyValue$Ress.borderBottomColor;

var borderLeftColor = CssPropertyValue$Ress.borderLeftColor;

var borderStyle = CssPropertyValue$Ress.borderStyle;

var borderStyle2 = CssPropertyValue$Ress.borderStyle2;

var borderStyle3 = CssPropertyValue$Ress.borderStyle3;

var borderStyle4 = CssPropertyValue$Ress.borderStyle4;

var borderTopStyle = CssPropertyValue$Ress.borderTopStyle;

var borderRightStyle = CssPropertyValue$Ress.borderRightStyle;

var borderBottomStyle = CssPropertyValue$Ress.borderBottomStyle;

var borderLeftStyle = CssPropertyValue$Ress.borderLeftStyle;

var borderWidth = CssPropertyValue$Ress.borderWidth;

var borderWidth2 = CssPropertyValue$Ress.borderWidth2;

var borderWidth3 = CssPropertyValue$Ress.borderWidth3;

var borderWidth4 = CssPropertyValue$Ress.borderWidth4;

var borderTopWidth = CssPropertyValue$Ress.borderTopWidth;

var borderRightWidth = CssPropertyValue$Ress.borderRightWidth;

var borderBottomWidth = CssPropertyValue$Ress.borderBottomWidth;

var borderLeftWidth = CssPropertyValue$Ress.borderLeftWidth;

var background = CssPropertyValue$Ress.background;

var background2 = CssPropertyValue$Ress.background2;

var background3 = CssPropertyValue$Ress.background3;

var background4 = CssPropertyValue$Ress.background4;

var backgroundAttachment = CssPropertyValue$Ress.backgroundAttachment;

var backgroundAttachment2 = CssPropertyValue$Ress.backgroundAttachment2;

var backgroundAttachment3 = CssPropertyValue$Ress.backgroundAttachment3;

var backgroundAttachment4 = CssPropertyValue$Ress.backgroundAttachment4;

var backgroundColor = CssPropertyValue$Ress.backgroundColor;

var backgroundImage = CssPropertyValue$Ress.backgroundImage;

var backgroundImage2 = CssPropertyValue$Ress.backgroundImage2;

var backgroundImage3 = CssPropertyValue$Ress.backgroundImage3;

var backgroundImage4 = CssPropertyValue$Ress.backgroundImage4;

var backgroundPosition = CssPropertyValue$Ress.backgroundPosition;

var backgroundPosition2 = CssPropertyValue$Ress.backgroundPosition2;

var backgroundPosition3 = CssPropertyValue$Ress.backgroundPosition3;

var backgroundPosition4 = CssPropertyValue$Ress.backgroundPosition4;

var backgroundStyle = CssPropertyValue$Ress.backgroundStyle;

var backgroundStyle2 = CssPropertyValue$Ress.backgroundStyle2;

var backgroundStyle3 = CssPropertyValue$Ress.backgroundStyle3;

var backgroundStyle4 = CssPropertyValue$Ress.backgroundStyle4;

var margin = CssPropertyValue$Ress.margin;

var margin2 = CssPropertyValue$Ress.margin2;

var margin3 = CssPropertyValue$Ress.margin3;

var margin4 = CssPropertyValue$Ress.margin4;

var marginTop = CssPropertyValue$Ress.marginTop;

var marginRight = CssPropertyValue$Ress.marginRight;

var marginBottom = CssPropertyValue$Ress.marginBottom;

var marginLeft = CssPropertyValue$Ress.marginLeft;

var padding = CssPropertyValue$Ress.padding;

var padding2 = CssPropertyValue$Ress.padding2;

var padding3 = CssPropertyValue$Ress.padding3;

var padding4 = CssPropertyValue$Ress.padding4;

var paddingTop = CssPropertyValue$Ress.paddingTop;

var paddingRight = CssPropertyValue$Ress.paddingRight;

var paddingBottom = CssPropertyValue$Ress.paddingBottom;

var paddingLeft = CssPropertyValue$Ress.paddingLeft;

var clear = CssPropertyValue$Ress.clear;

var color = CssPropertyValue$Ress.color;

var cursor = CssPropertyValue$Ress.cursor;

var cursor1 = CssPropertyValue$Ress.cursor1;

var cursor2 = CssPropertyValue$Ress.cursor2;

var cursor3 = CssPropertyValue$Ress.cursor3;

var cursor4 = CssPropertyValue$Ress.cursor4;

exports.border = border;
exports.borderColor = borderColor;
exports.borderColor2 = borderColor2;
exports.borderColor3 = borderColor3;
exports.borderColor4 = borderColor4;
exports.borderTopColor = borderTopColor;
exports.borderRightColor = borderRightColor;
exports.borderBottomColor = borderBottomColor;
exports.borderLeftColor = borderLeftColor;
exports.borderStyle = borderStyle;
exports.borderStyle2 = borderStyle2;
exports.borderStyle3 = borderStyle3;
exports.borderStyle4 = borderStyle4;
exports.borderTopStyle = borderTopStyle;
exports.borderRightStyle = borderRightStyle;
exports.borderBottomStyle = borderBottomStyle;
exports.borderLeftStyle = borderLeftStyle;
exports.borderWidth = borderWidth;
exports.borderWidth2 = borderWidth2;
exports.borderWidth3 = borderWidth3;
exports.borderWidth4 = borderWidth4;
exports.borderTopWidth = borderTopWidth;
exports.borderRightWidth = borderRightWidth;
exports.borderBottomWidth = borderBottomWidth;
exports.borderLeftWidth = borderLeftWidth;
exports.background = background;
exports.background2 = background2;
exports.background3 = background3;
exports.background4 = background4;
exports.backgroundAttachment = backgroundAttachment;
exports.backgroundAttachment2 = backgroundAttachment2;
exports.backgroundAttachment3 = backgroundAttachment3;
exports.backgroundAttachment4 = backgroundAttachment4;
exports.backgroundColor = backgroundColor;
exports.backgroundImage = backgroundImage;
exports.backgroundImage2 = backgroundImage2;
exports.backgroundImage3 = backgroundImage3;
exports.backgroundImage4 = backgroundImage4;
exports.backgroundPosition = backgroundPosition;
exports.backgroundPosition2 = backgroundPosition2;
exports.backgroundPosition3 = backgroundPosition3;
exports.backgroundPosition4 = backgroundPosition4;
exports.backgroundStyle = backgroundStyle;
exports.backgroundStyle2 = backgroundStyle2;
exports.backgroundStyle3 = backgroundStyle3;
exports.backgroundStyle4 = backgroundStyle4;
exports.margin = margin;
exports.margin2 = margin2;
exports.margin3 = margin3;
exports.margin4 = margin4;
exports.marginTop = marginTop;
exports.marginRight = marginRight;
exports.marginBottom = marginBottom;
exports.marginLeft = marginLeft;
exports.padding = padding;
exports.padding2 = padding2;
exports.padding3 = padding3;
exports.padding4 = padding4;
exports.paddingTop = paddingTop;
exports.paddingRight = paddingRight;
exports.paddingBottom = paddingBottom;
exports.paddingLeft = paddingLeft;
exports.clear = clear;
exports.color = color;
exports.cursor = cursor;
exports.cursor1 = cursor1;
exports.cursor2 = cursor2;
exports.cursor3 = cursor3;
exports.cursor4 = cursor4;
/* No side effect */
