// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var StyleValue$Materialui = require("../src/StyleValue.js");
var StyleProperty$Materialui = require("../src/StyleProperty.js");

test("border", (function () {
        expect(StyleProperty$Materialui.border("solid")).toEqual(StyleProperty$Materialui.make("border", "solid"));
        expect(StyleProperty$Materialui.border(StyleValue$Materialui.border2("dashed", "red"))).toEqual(StyleProperty$Materialui.make("border", "dashed red"));
        expect(StyleProperty$Materialui.border(StyleValue$Materialui.border3("thick", "double", StyleValue$Materialui.rgbHex("32a1ce")))).toEqual(StyleProperty$Materialui.make("border", "thick double #32a1ce"));
        
      }));

test("borderString", (function () {
        expect(StyleProperty$Materialui.borderString("solid")).toEqual(StyleProperty$Materialui.make("border", "solid"));
        expect(StyleProperty$Materialui.borderString("dashed red")).toEqual(StyleProperty$Materialui.make("border", "dashed red"));
        expect(StyleProperty$Materialui.borderString("thick double #32a1ce")).toEqual(StyleProperty$Materialui.make("border", "thick double #32a1ce"));
        
      }));

test("border2", (function () {
        expect(StyleProperty$Materialui.border2("dashed", "red")).toEqual(StyleProperty$Materialui.make("border", "dashed red"));
        
      }));

test("borderString", (function () {
        expect(StyleProperty$Materialui.border3("thick", "double", StyleValue$Materialui.rgbHex("32a1ce"))).toEqual(StyleProperty$Materialui.make("border", "thick double #32a1ce"));
        
      }));

test("borderTop", (function () {
        expect(StyleProperty$Materialui.borderTop("solid")).toEqual(StyleProperty$Materialui.make("borderTop", "solid"));
        expect(StyleProperty$Materialui.borderTop(StyleValue$Materialui.border2("dashed", "red"))).toEqual(StyleProperty$Materialui.make("borderTop", "dashed red"));
        expect(StyleProperty$Materialui.borderTop(StyleValue$Materialui.border3("thick", "double", StyleValue$Materialui.rgbHex("32a1ce")))).toEqual(StyleProperty$Materialui.make("borderTop", "thick double #32a1ce"));
        
      }));

test("borderLeft", (function () {
        expect(StyleProperty$Materialui.borderLeft("solid")).toEqual(StyleProperty$Materialui.make("borderLeft", "solid"));
        expect(StyleProperty$Materialui.borderLeft(StyleValue$Materialui.border2("dashed", "red"))).toEqual(StyleProperty$Materialui.make("borderLeft", "dashed red"));
        expect(StyleProperty$Materialui.borderLeft(StyleValue$Materialui.border3("thick", "double", StyleValue$Materialui.rgbHex("32a1ce")))).toEqual(StyleProperty$Materialui.make("borderLeft", "thick double #32a1ce"));
        
      }));

test("borderRight", (function () {
        expect(StyleProperty$Materialui.borderRight("solid")).toEqual(StyleProperty$Materialui.make("borderRight", "solid"));
        expect(StyleProperty$Materialui.borderRight(StyleValue$Materialui.border2("dashed", "red"))).toEqual(StyleProperty$Materialui.make("borderRight", "dashed red"));
        expect(StyleProperty$Materialui.borderRight(StyleValue$Materialui.border3("thick", "double", StyleValue$Materialui.rgbHex("32a1ce")))).toEqual(StyleProperty$Materialui.make("borderRight", "thick double #32a1ce"));
        
      }));

test("borderBottom", (function () {
        expect(StyleProperty$Materialui.borderBottom("solid")).toEqual(StyleProperty$Materialui.make("borderBottom", "solid"));
        expect(StyleProperty$Materialui.borderBottom(StyleValue$Materialui.border2("dashed", "red"))).toEqual(StyleProperty$Materialui.make("borderBottom", "dashed red"));
        expect(StyleProperty$Materialui.borderBottom(StyleValue$Materialui.border3("thick", "double", StyleValue$Materialui.rgbHex("32a1ce")))).toEqual(StyleProperty$Materialui.make("borderBottom", "thick double #32a1ce"));
        
      }));

/*  Not a pure module */
