// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssValueString$Ress = require("../value/CssValueString.js");

function Make(Type) {
  var value = CssValueString$Ress.color_global;
  return {
          value: value
        };
}

exports.Make = Make;
/* No side effect */
