// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssString$Ress = require("../value/CssString.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");

var property = "backgroundImage";

var declaration = CssDeclaration$Ress.Helper.declaration;

var declarationFn = CssDeclarationFn$Ress.Helper.declarationFn;

var bgImage = CssString$Ress.Property.backgroundImage;

var bgImage2 = CssString$Ress.Property.backgroundImage2;

var bgImage3 = CssString$Ress.Property.backgroundImage3;

var bgImage4 = CssString$Ress.Property.backgroundImage4;

var value = Curry.__1(bgImage);

var value2 = Curry.__2(bgImage2);

var value3 = Curry.__3(bgImage3);

var value4 = Curry.__4(bgImage4);

function backgroundImage(v) {
  return Curry._2(declaration, property, value(v));
}

function backgroundImage2(v1, v2) {
  return Curry._2(declaration, property, value2(v1, v2));
}

function backgroundImage3(v1, v2, v3) {
  return Curry._2(declaration, property, value3(v1, v2, v3));
}

function backgroundImage4(v1, v2, v3, v4) {
  return Curry._2(declaration, property, value4(v1, v2, v3, v4));
}

function backgroundImageUnion(v) {
  return Curry._2(declaration, property, v);
}

function backgroundImageString(v) {
  return Curry._2(declaration, property, v);
}

var DeclarationHelper = {
  backgroundImage: backgroundImage,
  backgroundImage2: backgroundImage2,
  backgroundImage3: backgroundImage3,
  backgroundImage4: backgroundImage4,
  backgroundImageUnion: backgroundImageUnion,
  backgroundImageString: backgroundImageString
};

function backgroundImageFn(v) {
  return Curry._2(declarationFn, property, v);
}

var DeclarationFnHelper = {
  backgroundImageFn: backgroundImageFn
};

exports.value = value;
exports.value2 = value2;
exports.value3 = value3;
exports.value4 = value4;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* No side effect */
