// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");
var CssBorderSideColor$Ress = require("./CssBorderSideColor.js");

var property = "borderLeftColor";

var include = CssBorderSideColor$Ress.MakeValue({});

var value = include.value;

function borderLeftColor(v) {
  return CssDeclaration$Ress.Helper.declaration(property, Curry._1(value, v));
}

function borderLeftColorUnion(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

function borderLeftColorString(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

var DeclarationHelper = {
  borderLeftColor: borderLeftColor,
  borderLeftColorUnion: borderLeftColorUnion,
  borderLeftColorString: borderLeftColorString
};

function borderLeftColorFn(v) {
  return CssDeclarationFn$Ress.Helper.declarationFn(property, v);
}

var DeclarationFnHelper = {
  borderLeftColorFn: borderLeftColorFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
