// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");
var CssBorderSideColor$Ress = require("./CssBorderSideColor.js");

var property = "borderRightColor";

var include = CssBorderSideColor$Ress.MakeValue({});

var value = include.value;

function borderRightColor(v) {
  return CssDeclaration$Ress.Helper.declaration(property, Curry._1(value, v));
}

function borderRightColorUnion(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

function borderRightColorString(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

var DeclarationHelper = {
  borderRightColor: borderRightColor,
  borderRightColorUnion: borderRightColorUnion,
  borderRightColorString: borderRightColorString
};

function borderRightColorFn(v) {
  return CssDeclarationFn$Ress.Helper.declarationFn(property, v);
}

var DeclarationFnHelper = {
  borderRightColorFn: borderRightColorFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
