// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssString$Ress = require("../value/CssString.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");

var property = "backgroundColor";

var declaration = CssDeclaration$Ress.Helper.declaration;

var declarationFn = CssDeclarationFn$Ress.Helper.declarationFn;

var backgroundColor = CssString$Ress.Property.backgroundColor;

var value = Curry.__1(backgroundColor);

function backgroundColor$1(v) {
  return Curry._2(declaration, property, value(v));
}

function backgroundColorUnion(v) {
  return Curry._2(declaration, property, v);
}

function backgroundColorString(v) {
  return Curry._2(declaration, property, v);
}

var DeclarationHelper = {
  backgroundColor: backgroundColor$1,
  backgroundColorUnion: backgroundColorUnion,
  backgroundColorString: backgroundColorString
};

function backgroundColorFn(v) {
  return Curry._2(declarationFn, property, v);
}

var DeclarationFnHelper = {
  backgroundColorFn: backgroundColorFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* No side effect */
