// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssString$Ress = require("../value/CssString.js");

var color = CssString$Ress.Property.color;

function MakeValue(Type) {
  var value = Curry.__1(color);
  return {
          value: value
        };
}

exports.MakeValue = MakeValue;
/* No side effect */
