// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssBorder$Ress = require("./CssBorder.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");

var property = "borderBottom";

var declaration = CssDeclaration$Ress.Helper.declaration;

var declarationFn = CssDeclarationFn$Ress.Helper.declarationFn;

var include = CssBorder$Ress.MakeValue({});

var value = include.value;

function borderBottom(width, color, style) {
  return Curry._2(declaration, property, Curry._3(value, width, color, style));
}

function borderBottomUnion(v) {
  return Curry._2(declaration, property, v);
}

function borderBottomString(v) {
  return Curry._2(declaration, property, v);
}

var DeclarationHelper = {
  borderBottom: borderBottom,
  borderBottomUnion: borderBottomUnion,
  borderBottomString: borderBottomString
};

function borderBottomFn(v) {
  return Curry._2(declarationFn, property, v);
}

var DeclarationFnHelper = {
  borderBottomFn: borderBottomFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
