// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssBorderSideWidth$Ress = require("./CssBorderSideWidth.js");

var property = "borderTopWidth";

function Make(Type) {
  var include = CssBorderSideWidth$Ress.Make({});
  var value = include.value;
  var borderTopWidth = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              Curry._1(value, v)
            ]
          };
  };
  var borderTopWidthUnion = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var borderTopWidthString = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var DeclarationHelper = {
    borderTopWidth: borderTopWidth,
    borderTopWidthUnion: borderTopWidthUnion,
    borderTopWidthString: borderTopWidthString
  };
  var borderTopWidthFn = function (v) {
    return {
            NAME: "DeclarationFn",
            VAL: [
              property,
              v
            ]
          };
  };
  var DeclarationFnHelper = {
    borderTopWidth: borderTopWidth,
    borderTopWidthUnion: borderTopWidthUnion,
    borderTopWidthString: borderTopWidthString,
    borderTopWidthFn: borderTopWidthFn
  };
  return {
          value: value,
          DeclarationHelper: DeclarationHelper,
          DeclarationFnHelper: DeclarationFnHelper
        };
}

exports.Make = Make;
/* No side effect */
