// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssBorderSideWidth$Ress = require("./CssBorderSideWidth.js");

var property = "borderTopWidth";

var include = CssBorderSideWidth$Ress.MakeValue({});

var value = include.value;

function borderTopWidth(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            Curry._1(value, v)
          ]
        };
}

function borderTopWidthUnion(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            v
          ]
        };
}

function borderTopWidthString(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            v
          ]
        };
}

var DeclarationHelper = {
  borderTopWidth: borderTopWidth,
  borderTopWidthUnion: borderTopWidthUnion,
  borderTopWidthString: borderTopWidthString
};

function borderTopWidthFn(v) {
  return {
          NAME: "DeclarationFn",
          VAL: [
            property,
            v
          ]
        };
}

var DeclarationFnHelper = {
  borderTopWidth: borderTopWidth,
  borderTopWidthUnion: borderTopWidthUnion,
  borderTopWidthString: borderTopWidthString,
  borderTopWidthFn: borderTopWidthFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
