// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssBorderSideColor$Ress = require("./CssBorderSideColor.js");

var property = "borderLeftColor";

var include = CssBorderSideColor$Ress.MakeValue({});

var value = include.value;

function borderLeftColor(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            Curry._1(value, v)
          ]
        };
}

function borderLeftColorUnion(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            v
          ]
        };
}

function borderLeftColorString(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            v
          ]
        };
}

var DeclarationHelper = {
  borderLeftColor: borderLeftColor,
  borderLeftColorUnion: borderLeftColorUnion,
  borderLeftColorString: borderLeftColorString
};

function borderLeftColorFn(v) {
  return {
          NAME: "DeclarationFn",
          VAL: [
            property,
            v
          ]
        };
}

var DeclarationFnHelper = {
  borderLeftColor: borderLeftColor,
  borderLeftColorUnion: borderLeftColorUnion,
  borderLeftColorString: borderLeftColorString,
  borderLeftColorFn: borderLeftColorFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
