// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssBorderSideColor$Ress = require("./CssBorderSideColor.js");

var property = "borderTopColor";

function Make(Type) {
  var include = CssBorderSideColor$Ress.Make({});
  var value = include.value;
  var borderTopColor = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              Curry._1(value, v)
            ]
          };
  };
  var borderTopColorUnion = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var borderTopColorString = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var DeclarationHelper = {
    borderTopColor: borderTopColor,
    borderTopColorUnion: borderTopColorUnion,
    borderTopColorString: borderTopColorString
  };
  var borderTopColorFn = function (v) {
    return {
            NAME: "DeclarationFn",
            VAL: [
              property,
              v
            ]
          };
  };
  var DeclarationFnHelper = {
    borderTopColor: borderTopColor,
    borderTopColorUnion: borderTopColorUnion,
    borderTopColorString: borderTopColorString,
    borderTopColorFn: borderTopColorFn
  };
  return {
          value: value,
          DeclarationHelper: DeclarationHelper,
          DeclarationFnHelper: DeclarationFnHelper
        };
}

exports.Make = Make;
/* No side effect */
