// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssBorderSideStyle$Ress = require("./CssBorderSideStyle.js");

var property = "borderBottomStyle";

function Make(Type) {
  var include = CssBorderSideStyle$Ress.Make({});
  var value = include.value;
  var borderBottomStyle = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              Curry._1(value, v)
            ]
          };
  };
  var borderBottomStyleUnion = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var borderBottomStyleString = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var DeclarationHelper = {
    borderBottomStyle: borderBottomStyle,
    borderBottomStyleUnion: borderBottomStyleUnion,
    borderBottomStyleString: borderBottomStyleString
  };
  var borderBottomStyleFn = function (v) {
    return {
            NAME: "DeclarationFn",
            VAL: [
              property,
              v
            ]
          };
  };
  var DeclarationFnHelper = {
    borderBottomStyle: borderBottomStyle,
    borderBottomStyleUnion: borderBottomStyleUnion,
    borderBottomStyleString: borderBottomStyleString,
    borderBottomStyleFn: borderBottomStyleFn
  };
  return {
          value: value,
          DeclarationHelper: DeclarationHelper,
          DeclarationFnHelper: DeclarationFnHelper
        };
}

exports.Make = Make;
/* No side effect */
