// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssBorder$Ress = require("./CssBorder.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");

var property = "borderTop";

var include = CssBorder$Ress.MakeValue({});

var value = include.value;

function borderTop(width, color, style) {
  return CssDeclaration$Ress.Helper.declaration(property, Curry._3(value, width, color, style));
}

function borderTopUnion(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

function borderTopString(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

var DeclarationHelper = {
  borderTop: borderTop,
  borderTopUnion: borderTopUnion,
  borderTopString: borderTopString
};

function borderTopFn(v) {
  return CssDeclarationFn$Ress.Helper.declarationFn(property, v);
}

var DeclarationFnHelper = {
  borderTopFn: borderTopFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
