// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssValueString$Ress = require("../value/CssValueString.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");

var property = "borderWidth";

var value = CssValueString$Ress.lineWidth_global;

function value2(tb, lr) {
  return CssValueString$Ress.lineWidth(tb) + " " + CssValueString$Ress.lineWidth(lr);
}

function value3(top, lr, bottom) {
  return CssValueString$Ress.lineWidth(top) + " " + CssValueString$Ress.lineWidth(lr) + " " + CssValueString$Ress.lineWidth(bottom);
}

function value4(top, right, bottom, left) {
  return CssValueString$Ress.lineWidth(top) + " " + CssValueString$Ress.lineWidth(right) + " " + CssValueString$Ress.lineWidth(bottom) + " " + CssValueString$Ress.lineWidth(left);
}

function borderWidth(v) {
  return CssDeclaration$Ress.Helper.declaration(property, CssValueString$Ress.lineWidth_global(v));
}

function borderWidth2(tb, lr) {
  return CssDeclaration$Ress.Helper.declaration(property, value2(tb, lr));
}

function borderWidth3(top, lr, bottom) {
  return CssDeclaration$Ress.Helper.declaration(property, value3(top, lr, bottom));
}

function borderWidth4(top, right, bottom, left) {
  return CssDeclaration$Ress.Helper.declaration(property, value4(top, right, bottom, left));
}

function borderWidthUnion(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

function borderWidthString(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

var DeclarationHelper = {
  borderWidth: borderWidth,
  borderWidth2: borderWidth2,
  borderWidth3: borderWidth3,
  borderWidth4: borderWidth4,
  borderWidthUnion: borderWidthUnion,
  borderWidthString: borderWidthString
};

function borderWidthFn(v) {
  return CssDeclarationFn$Ress.Helper.declarationFn(property, v);
}

var DeclarationFnHelper = {
  borderWidth: borderWidth,
  borderWidth2: borderWidth2,
  borderWidth3: borderWidth3,
  borderWidth4: borderWidth4,
  borderWidthUnion: borderWidthUnion,
  borderWidthString: borderWidthString,
  borderWidthFn: borderWidthFn
};

exports.value = value;
exports.value2 = value2;
exports.value3 = value3;
exports.value4 = value4;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* No side effect */
