// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssPropertyValueString$Ress = require("../value/CssPropertyValueString.js");

function MakeValue(Type) {
  var value = CssPropertyValueString$Ress.borderStyle;
  return {
          value: value
        };
}

exports.MakeValue = MakeValue;
/* No side effect */
