// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssBorder$Ress = require("./CssBorder.js");

var property = "borderRight";

var include = CssBorder$Ress.MakeValue({});

var value = include.value;

function borderRight(width, color, style) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            Curry._3(value, width, color, style)
          ]
        };
}

function borderRightUnion(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            v
          ]
        };
}

function borderRightString(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            v
          ]
        };
}

var DeclarationHelper = {
  borderRight: borderRight,
  borderRightUnion: borderRightUnion,
  borderRightString: borderRightString
};

function borderRightFn(v) {
  return {
          NAME: "DeclarationFn",
          VAL: [
            property,
            v
          ]
        };
}

var DeclarationFnHelper = {
  borderRight: borderRight,
  borderRightUnion: borderRightUnion,
  borderRightString: borderRightString,
  borderRightFn: borderRightFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
