// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssValueString$Ress = require("../value/CssValueString.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");

var property = "cursor";

var value = CssValueString$Ress.cursorKeyword_global;

function value1(i, k) {
  return CssValueString$Ress.cursorImage(i) + ", " + CssValueString$Ress.cursorKeyword(k);
}

function value2(i1, i2, k) {
  return CssValueString$Ress.cursorImage(i1) + ", " + CssValueString$Ress.cursorImage(i2) + ", " + CssValueString$Ress.cursorKeyword(k);
}

function value3(i1, i2, i3, k) {
  return CssValueString$Ress.cursorImage(i1) + ", " + CssValueString$Ress.cursorImage(i2) + ", " + CssValueString$Ress.cursorImage(i3) + ", " + CssValueString$Ress.cursorKeyword(k);
}

function value4(i1, i2, i3, i4, k) {
  return CssValueString$Ress.cursorImage(i1) + ", " + CssValueString$Ress.cursorImage(i2) + ", " + CssValueString$Ress.cursorImage(i3) + ", " + CssValueString$Ress.cursorImage(i4) + ", " + CssValueString$Ress.cursorKeyword(k);
}

function cursor(v) {
  return CssDeclaration$Ress.Helper.declaration(property, CssValueString$Ress.cursorKeyword_global(v));
}

function cursor1(i, k) {
  return CssDeclaration$Ress.Helper.declaration(property, value1(i, k));
}

function cursor2(i1, i2, k) {
  return CssDeclaration$Ress.Helper.declaration(property, value2(i1, i2, k));
}

function cursor3(i1, i2, i3, k) {
  return CssDeclaration$Ress.Helper.declaration(property, value3(i1, i2, i3, k));
}

function cursor4(i1, i2, i3, i4, k) {
  return CssDeclaration$Ress.Helper.declaration(property, value4(i1, i2, i3, i4, k));
}

function cursorUnion(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

function cursorString(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

var DeclarationHelper = {
  cursor: cursor,
  cursor1: cursor1,
  cursor2: cursor2,
  cursor3: cursor3,
  cursor4: cursor4,
  cursorUnion: cursorUnion,
  cursorString: cursorString
};

function cursorFn(v) {
  return CssDeclarationFn$Ress.Helper.declarationFn(property, v);
}

var DeclarationFnHelper = {
  cursor: cursor,
  cursor1: cursor1,
  cursor2: cursor2,
  cursor3: cursor3,
  cursor4: cursor4,
  cursorUnion: cursorUnion,
  cursorString: cursorString,
  cursorFn: cursorFn
};

exports.value = value;
exports.value1 = value1;
exports.value2 = value2;
exports.value3 = value3;
exports.value4 = value4;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* No side effect */
