// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssMarginSide$Ress = require("./CssMarginSide.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");

var property = "marginLeft";

var include = CssMarginSide$Ress.MakeValue({});

var value = include.value;

function marginLeft(v) {
  return CssDeclaration$Ress.Helper.declaration(property, Curry._1(value, v));
}

function marginLeftUnion(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

function marginLeftString(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

function marginLeftNumber(v) {
  return CssDeclaration$Ress.Helper.declaration(property, v);
}

var DeclarationHelper = {
  marginLeft: marginLeft,
  marginLeftUnion: marginLeftUnion,
  marginLeftString: marginLeftString,
  marginLeftNumber: marginLeftNumber
};

function marginLeftFn(v) {
  return CssDeclarationFn$Ress.Helper.declarationFn(property, v);
}

var DeclarationFnHelper = {
  marginLeftFn: marginLeftFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
