// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssMarginSide$Ress = require("./CssMarginSide.js");

var property = "marginBottom";

var include = CssMarginSide$Ress.MakeValue({});

var value = include.value;

function marginBottom(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            Curry._1(value, v)
          ]
        };
}

function marginBottomUnion(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            v
          ]
        };
}

function marginBottomString(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            v
          ]
        };
}

function marginBottomNumber(v) {
  return {
          NAME: "Declaration",
          VAL: [
            property,
            v
          ]
        };
}

var DeclarationHelper = {
  marginBottom: marginBottom,
  marginBottomUnion: marginBottomUnion,
  marginBottomString: marginBottomString,
  marginBottomNumber: marginBottomNumber
};

function marginBottomFn(v) {
  return {
          NAME: "DeclarationFn",
          VAL: [
            property,
            v
          ]
        };
}

var DeclarationFnHelper = {
  marginBottom: marginBottom,
  marginBottomUnion: marginBottomUnion,
  marginBottomString: marginBottomString,
  marginBottomNumber: marginBottomNumber,
  marginBottomFn: marginBottomFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
