// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssMarginSide$Ress = require("./CssMarginSide.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");

var property = "marginTop";

var declaration = CssDeclaration$Ress.Helper.declaration;

var declarationFn = CssDeclarationFn$Ress.Helper.declarationFn;

var include = CssMarginSide$Ress.MakeValue({});

var value = include.value;

function marginTop(v) {
  return Curry._2(declaration, property, Curry._1(value, v));
}

function marginTopUnion(v) {
  return Curry._2(declaration, property, v);
}

function marginTopString(v) {
  return Curry._2(declaration, property, v);
}

function marginTopNumber(v) {
  return Curry._2(declaration, property, v);
}

var DeclarationHelper = {
  marginTop: marginTop,
  marginTopUnion: marginTopUnion,
  marginTopString: marginTopString,
  marginTopNumber: marginTopNumber
};

function marginTopFn(v) {
  return Curry._2(declarationFn, property, v);
}

var DeclarationFnHelper = {
  marginTopFn: marginTopFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
