// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssPaddingSide$Ress = require("./CssPaddingSide.js");

var property = "paddingTop";

function Make(Type) {
  var include = CssPaddingSide$Ress.Make({});
  var value = include.value;
  var paddingTop = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              Curry._1(value, v)
            ]
          };
  };
  var paddingTopUnion = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var paddingTopString = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var paddingTopNumber = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var DeclarationHelper = {
    paddingTop: paddingTop,
    paddingTopUnion: paddingTopUnion,
    paddingTopString: paddingTopString,
    paddingTopNumber: paddingTopNumber
  };
  var paddingTopFn = function (v) {
    return {
            NAME: "DeclarationFn",
            VAL: [
              property,
              v
            ]
          };
  };
  var DeclarationFnHelper = {
    paddingTop: paddingTop,
    paddingTopUnion: paddingTopUnion,
    paddingTopString: paddingTopString,
    paddingTopNumber: paddingTopNumber,
    paddingTopFn: paddingTopFn
  };
  return {
          value: value,
          DeclarationHelper: DeclarationHelper,
          DeclarationFnHelper: DeclarationFnHelper
        };
}

exports.Make = Make;
/* No side effect */
