// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssValueString$Ress = require("../value/CssValueString.js");

var property = "padding";

function Make(Type) {
  var value = CssValueString$Ress.padding_global;
  var value2 = function (tb, lr) {
    return CssValueString$Ress.padding(tb) + " " + CssValueString$Ress.padding(lr);
  };
  var value3 = function (top, lr, bottom) {
    return CssValueString$Ress.padding(top) + " " + CssValueString$Ress.padding(lr) + " " + CssValueString$Ress.padding(bottom);
  };
  var value4 = function (top, right, bottom, left) {
    return CssValueString$Ress.padding(top) + " " + CssValueString$Ress.padding(right) + " " + CssValueString$Ress.padding(bottom) + " " + CssValueString$Ress.padding(left);
  };
  var padding = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              CssValueString$Ress.padding_global(v)
            ]
          };
  };
  var padding2 = function (tb, lr) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              value2(tb, lr)
            ]
          };
  };
  var padding3 = function (top, lr, bottom) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              value3(top, lr, bottom)
            ]
          };
  };
  var padding4 = function (top, right, bottom, left) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              value4(top, right, bottom, left)
            ]
          };
  };
  var paddingUnion = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var paddingString = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var paddingNumber = function (v) {
    return {
            NAME: "Declaration",
            VAL: [
              property,
              v
            ]
          };
  };
  var DeclarationHelper = {
    padding: padding,
    padding2: padding2,
    padding3: padding3,
    padding4: padding4,
    paddingUnion: paddingUnion,
    paddingString: paddingString,
    paddingNumber: paddingNumber
  };
  var paddingFn = function (v) {
    return {
            NAME: "DeclarationFn",
            VAL: [
              property,
              v
            ]
          };
  };
  var DeclarationFnHelper = {
    padding: padding,
    padding2: padding2,
    padding3: padding3,
    padding4: padding4,
    paddingUnion: paddingUnion,
    paddingString: paddingString,
    paddingNumber: paddingNumber,
    paddingFn: paddingFn
  };
  return {
          value: value,
          value2: value2,
          value3: value3,
          value4: value4,
          DeclarationHelper: DeclarationHelper,
          DeclarationFnHelper: DeclarationFnHelper
        };
}

exports.Make = Make;
/* No side effect */
