// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssPaddingSide$Ress = require("./CssPaddingSide.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");

var property = "paddingTop";

var declaration = CssDeclaration$Ress.Helper.declaration;

var declarationFn = CssDeclarationFn$Ress.Helper.declarationFn;

var include = CssPaddingSide$Ress.MakeValue({});

var value = include.value;

function paddingTop(v) {
  return Curry._2(declaration, property, Curry._1(value, v));
}

function paddingTopUnion(v) {
  return Curry._2(declaration, property, v);
}

function paddingTopString(v) {
  return Curry._2(declaration, property, v);
}

function paddingTopNumber(v) {
  return Curry._2(declaration, property, v);
}

var DeclarationHelper = {
  paddingTop: paddingTop,
  paddingTopUnion: paddingTopUnion,
  paddingTopString: paddingTopString,
  paddingTopNumber: paddingTopNumber
};

function paddingTopFn(v) {
  return Curry._2(declarationFn, property, v);
}

var DeclarationFnHelper = {
  paddingTopFn: paddingTopFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
