// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssDeclaration$Ress = require("../declaration/CssDeclaration.js");
var CssPaddingSide$Ress = require("./CssPaddingSide.js");
var CssDeclarationFn$Ress = require("../declaration/CssDeclarationFn.js");

var property = "paddingBottom";

var declaration = CssDeclaration$Ress.Helper.declaration;

var declarationFn = CssDeclarationFn$Ress.Helper.declarationFn;

var include = CssPaddingSide$Ress.MakeValue({});

var value = include.value;

function paddingBottom(v) {
  return Curry._2(declaration, property, Curry._1(value, v));
}

function paddingBottomUnion(v) {
  return Curry._2(declaration, property, v);
}

function paddingBottomString(v) {
  return Curry._2(declaration, property, v);
}

function paddingBottomNumber(v) {
  return Curry._2(declaration, property, v);
}

var DeclarationHelper = {
  paddingBottom: paddingBottom,
  paddingBottomUnion: paddingBottomUnion,
  paddingBottomString: paddingBottomString,
  paddingBottomNumber: paddingBottomNumber
};

function paddingBottomFn(v) {
  return Curry._2(declarationFn, property, v);
}

var DeclarationFnHelper = {
  paddingBottomFn: paddingBottomFn
};

exports.value = value;
exports.DeclarationHelper = DeclarationHelper;
exports.DeclarationFnHelper = DeclarationFnHelper;
/* include Not a pure module */
