// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Value$Css = require("../src/Value.js");

test("border", (function () {
        expect(Value$Css.Border.make2("dashed", "red")).toBe("dashed red");
        expect(Value$Css.Border.make2("solid", Value$Css.Basic.rem(1.0))).toBe("solid 1rem");
        expect(Value$Css.Border.make3("thick", "double", Value$Css.Basic.rgbHex("32a1ce"))).toBe("thick double #32a1ce");
        expect(Value$Css.Border.make3(Value$Css.Basic.mm(4), "ridge", Value$Css.Basic.rgba(Value$Css.Basic.num(170), Value$Css.Basic.num(50), Value$Css.Basic.num(220), Value$Css.Basic.num(0.6)))).toBe("4mm ridge rgba(170, 50, 220, 0.6)");
        
      }));

/*  Not a pure module */
