// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Value$Css = require("../src/Value.js");
var ValueToString$Css = require("../src/ValueToString.js");

test("number", (function () {
        expect(ValueToString$Css.num(1)).toBe("1");
        expect(ValueToString$Css.number(Value$Css.Basic.num(1))).toBe("1");
        
      }));

test("integer", (function () {
        expect(ValueToString$Css.intg(1)).toBe("1");
        expect(ValueToString$Css.integer(Value$Css.Basic.$$int(1))).toBe("1");
        
      }));

test("percentage", (function () {
        expect(ValueToString$Css.pct(1)).toBe("1%");
        expect(ValueToString$Css.percentage(Value$Css.Basic.pct(1))).toBe("1%");
        
      }));

test("length", (function () {
        expect(ValueToString$Css.ch(1)).toBe("1ch");
        expect(ValueToString$Css.em(1)).toBe("1em");
        expect(ValueToString$Css.ex(1)).toBe("1ex");
        expect(ValueToString$Css.rem(1)).toBe("1rem");
        expect(ValueToString$Css.vh(1)).toBe("1vh");
        expect(ValueToString$Css.vw(1)).toBe("1vw");
        expect(ValueToString$Css.vmin(1)).toBe("1vmin");
        expect(ValueToString$Css.vmax(1)).toBe("1vmax");
        expect(ValueToString$Css.px(1)).toBe("1px");
        expect(ValueToString$Css.cm(1)).toBe("1cm");
        expect(ValueToString$Css.mm(1)).toBe("1mm");
        expect(ValueToString$Css.inch(1)).toBe("1in");
        expect(ValueToString$Css.pc(1)).toBe("1pc");
        expect(ValueToString$Css.pt(1)).toBe("1pt");
        expect(ValueToString$Css.length(Value$Css.Basic.mm(1))).toBe("1mm");
        expect(ValueToString$Css.length(Value$Css.Basic.cm(1))).toBe("1cm");
        
      }));

test("angle", (function () {
        expect(ValueToString$Css.deg(1)).toBe("1deg");
        expect(ValueToString$Css.grad(1)).toBe("1grad");
        expect(ValueToString$Css.rad(1)).toBe("1rad");
        expect(ValueToString$Css.turn(1)).toBe("1turn");
        expect(ValueToString$Css.angle(Value$Css.Basic.deg(1))).toBe("1deg");
        expect(ValueToString$Css.angle(Value$Css.Basic.grad(1))).toBe("1grad");
        
      }));

test("color", (function () {
        expect(ValueToString$Css.hue(Value$Css.Basic.deg(1))).toBe("1deg");
        expect(ValueToString$Css.hue(Value$Css.Basic.num(1))).toBe("1");
        expect(ValueToString$Css.alpha(Value$Css.Basic.pct(1))).toBe("1%");
        expect(ValueToString$Css.alpha(Value$Css.Basic.num(1))).toBe("1");
        expect(ValueToString$Css.rgbValue(Value$Css.Basic.pct(1))).toBe("1%");
        expect(ValueToString$Css.rgbValue(Value$Css.Basic.num(1))).toBe("1");
        expect(ValueToString$Css.hsl(Value$Css.Basic.num(1), Value$Css.Basic.pct(10), Value$Css.Basic.pct(10))).toBe("hsl(1, 10%, 10%)");
        expect(ValueToString$Css.hsla(Value$Css.Basic.num(1), Value$Css.Basic.pct(10), Value$Css.Basic.pct(10), Value$Css.Basic.num(1))).toBe("hsla(1, 10%, 10%, 1)");
        expect(ValueToString$Css.rgb(Value$Css.Basic.num(1), Value$Css.Basic.num(1), Value$Css.Basic.pct(10))).toBe("rgb(1, 1, 10%)");
        expect(ValueToString$Css.rgba(Value$Css.Basic.num(1), Value$Css.Basic.num(1), Value$Css.Basic.pct(10), Value$Css.Basic.num(10))).toBe("rgba(1, 1, 10%, 10)");
        expect(ValueToString$Css.rgbHex("000000")).toBe("#000000");
        expect(ValueToString$Css.color(Value$Css.Basic.rgbHex("000000"))).toBe("#000000");
        expect(ValueToString$Css.color(Value$Css.Basic.rgb(Value$Css.Basic.num(1), Value$Css.Basic.num(1.8), Value$Css.Basic.pct(10)))).toBe("rgb(1, 1.8, 10%)");
        
      }));

test("lineWidth", (function () {
        expect(ValueToString$Css.lineWidth("thick")).toBe("thick");
        expect(ValueToString$Css.lineWidth(Value$Css.Basic.mm(10))).toBe("10mm");
        
      }));

test("borderColor", (function () {
        expect(ValueToString$Css.borderColor("revert")).toBe("revert");
        expect(ValueToString$Css.borderColor(Value$Css.Basic.hsl(Value$Css.Basic.num(1), Value$Css.Basic.pct(10), Value$Css.Basic.pct(10)))).toBe("hsl(1, 10%, 10%)");
        
      }));

/*  Not a pure module */
