// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssBackground$Ress = require("../../src/property/CssBackground.js");
var CssValueHelper$Ress = require("../../src/value/CssValueHelper.js");
var CssBackgroundColor$Ress = require("../../src/property/CssBackgroundColor.js");
var CssBackgroundImage$Ress = require("../../src/property/CssBackgroundImage.js");
var CssBackgroundStyle$Ress = require("../../src/property/CssBackgroundStyle.js");
var CssBackgroundPosition$Ress = require("../../src/property/CssBackgroundPosition.js");
var CssBackgroundAttachment$Ress = require("../../src/property/CssBackgroundAttachment.js");

test("background", (function () {
        expect(CssBackground$Ress.value(undefined, undefined, undefined, undefined, undefined, undefined, undefined, "initial")).toBe("initial");
        expect(CssBackground$Ress.value("red", undefined, undefined, undefined, undefined, undefined, undefined, "initial")).toBe("initial");
        expect(CssBackground$Ress.value(undefined, undefined, undefined, undefined, undefined, undefined, undefined, "red")).toBe("red");
        expect(CssBackground$Ress.value(undefined, undefined, undefined, undefined, undefined, undefined, undefined, CssValueHelper$Ress.rgb(255, 255, 255))).toBe("rgb(255, 255, 255)");
        expect(CssBackground$Ress.value(undefined, undefined, undefined, "repeatY", undefined, undefined, undefined, CssValueHelper$Ress.url("test.jpg"))).toBe("url(\"test.jpg\") repeat-y");
        expect(CssBackground$Ress.value2(CssValueHelper$Ress.linearGradient2(CssValueHelper$Ress.deg(217), CssValueHelper$Ress.rgba(255, 0, 0, 0.8), CssValueHelper$Ress.linearColorStop2(CssValueHelper$Ress.rgba(255, 0, 0, 0), CssValueHelper$Ress.pct(70.71))), CssValueHelper$Ress.linearGradient2(CssValueHelper$Ress.deg(127), CssValueHelper$Ress.rgba(0, 255, 0, 0.8), CssValueHelper$Ress.linearColorStop2(CssValueHelper$Ress.rgba(0, 255, 0, 0), CssValueHelper$Ress.pct(70.71))))).toBe("linear-gradient(217deg, rgba(255, 0, 0, 0.8), rgba(255, 0, 0, 0) 70.71%), linear-gradient(127deg, rgba(0, 255, 0, 0.8), rgba(0, 255, 0, 0) 70.71%)");
        expect(CssBackground$Ress.value3(CssValueHelper$Ress.linearGradient2(CssValueHelper$Ress.deg(217), CssValueHelper$Ress.rgba(255, 0, 0, 0.8), CssValueHelper$Ress.linearColorStop2(CssValueHelper$Ress.rgba(255, 0, 0, 0), CssValueHelper$Ress.pct(70.71))), CssValueHelper$Ress.linearGradient2(CssValueHelper$Ress.deg(127), CssValueHelper$Ress.rgba(0, 255, 0, 0.8), CssValueHelper$Ress.linearColorStop2(CssValueHelper$Ress.rgba(0, 255, 0, 0), CssValueHelper$Ress.pct(70.71))), CssValueHelper$Ress.linearGradient2(CssValueHelper$Ress.deg(217), CssValueHelper$Ress.rgba(255, 0, 0, 0.8), CssValueHelper$Ress.linearColorStop2(CssValueHelper$Ress.rgba(255, 0, 0, 0), CssValueHelper$Ress.pct(70.71))))).toBe("linear-gradient(217deg, rgba(255, 0, 0, 0.8), rgba(255, 0, 0, 0) 70.71%), linear-gradient(127deg, rgba(0, 255, 0, 0.8), rgba(0, 255, 0, 0) 70.71%), linear-gradient(217deg, rgba(255, 0, 0, 0.8), rgba(255, 0, 0, 0) 70.71%)");
        expect(CssBackground$Ress.value4(CssValueHelper$Ress.linearGradient2(CssValueHelper$Ress.deg(217), CssValueHelper$Ress.rgba(255, 0, 0, 0.8), CssValueHelper$Ress.linearColorStop2(CssValueHelper$Ress.rgba(255, 0, 0, 0), CssValueHelper$Ress.pct(70.71))), CssValueHelper$Ress.linearGradient2(CssValueHelper$Ress.deg(127), CssValueHelper$Ress.rgba(0, 255, 0, 0.8), CssValueHelper$Ress.linearColorStop2(CssValueHelper$Ress.rgba(0, 255, 0, 0), CssValueHelper$Ress.pct(70.71))), CssValueHelper$Ress.linearGradient2(CssValueHelper$Ress.deg(217), CssValueHelper$Ress.rgba(255, 0, 0, 0.8), CssValueHelper$Ress.linearColorStop2(CssValueHelper$Ress.rgba(255, 0, 0, 0), CssValueHelper$Ress.pct(70.71))), CssValueHelper$Ress.linearGradient2(CssValueHelper$Ress.deg(127), CssValueHelper$Ress.rgba(0, 255, 0, 0.8), CssValueHelper$Ress.linearColorStop2(CssValueHelper$Ress.rgba(0, 255, 0, 0), CssValueHelper$Ress.pct(70.71))))).toBe("linear-gradient(217deg, rgba(255, 0, 0, 0.8), rgba(255, 0, 0, 0) 70.71%), linear-gradient(127deg, rgba(0, 255, 0, 0.8), rgba(0, 255, 0, 0) 70.71%), linear-gradient(217deg, rgba(255, 0, 0, 0.8), rgba(255, 0, 0, 0) 70.71%), linear-gradient(127deg, rgba(0, 255, 0, 0.8), rgba(0, 255, 0, 0) 70.71%)");
        expect(CssBackground$Ress.value4(CssValueHelper$Ress.bgLayer(undefined, undefined, undefined, "repeat", undefined, undefined, undefined, CssValueHelper$Ress.url("myimage.png")), CssValueHelper$Ress.bgLayer(undefined, undefined, undefined, "repeat", undefined, undefined, undefined, CssValueHelper$Ress.url("myimage.png")), CssValueHelper$Ress.bgLayer(undefined, undefined, undefined, "repeat", undefined, undefined, undefined, CssValueHelper$Ress.url("myimage.png")), CssValueHelper$Ress.bgLayer(undefined, undefined, undefined, "repeat", undefined, undefined, undefined, CssValueHelper$Ress.url("myimage.png")))).toBe("url(\"myimage.png\") repeat, url(\"myimage.png\") repeat, url(\"myimage.png\") repeat, url(\"myimage.png\") repeat");
        
      }));

test("backgroundAttachment", (function () {
        expect(CssBackgroundAttachment$Ress.value("scroll")).toBe("scroll");
        expect(CssBackgroundAttachment$Ress.value2("scroll", "fixed")).toBe("scroll, fixed");
        expect(CssBackgroundAttachment$Ress.value3("scroll", "fixed", "fixed")).toBe("scroll, fixed, fixed");
        expect(CssBackgroundAttachment$Ress.value4("scroll", "fixed", "fixed", "local")).toBe("scroll, fixed, fixed, local");
        
      }));

test("backgroundColor", (function () {
        expect(CssBackgroundColor$Ress.value(CssValueHelper$Ress.rgb(200, 200, 200))).toBe("rgb(200, 200, 200)");
        
      }));

test("backgroundImage", (function () {
        expect(CssBackgroundImage$Ress.value(CssValueHelper$Ress.url("image.png"))).toBe("url(\"image.png\")");
        expect(CssBackgroundImage$Ress.value2(CssValueHelper$Ress.url("image.png"), CssValueHelper$Ress.image(undefined, undefined, CssValueHelper$Ress.url("myimage.jpg")))).toBe("url(\"image.png\"), image(url(\"myimage.jpg\"))");
        expect(CssBackgroundImage$Ress.value3(CssValueHelper$Ress.url("image.png"), CssValueHelper$Ress.image(undefined, undefined, CssValueHelper$Ress.url("myimage.jpg")), CssValueHelper$Ress.linearGradient(undefined, "red"))).toBe("url(\"image.png\"), image(url(\"myimage.jpg\")), linear-gradient(red)");
        expect(CssBackgroundImage$Ress.value4(CssValueHelper$Ress.url("image.png"), CssValueHelper$Ress.image(undefined, undefined, CssValueHelper$Ress.url("myimage.jpg")), CssValueHelper$Ress.linearGradient(undefined, "red"), CssValueHelper$Ress.radialGradient(undefined, undefined, undefined, "blue"))).toBe("url(\"image.png\"), image(url(\"myimage.jpg\")), linear-gradient(red), radial-gradient(blue)");
        
      }));

test("backgroundPosition", (function () {
        expect(CssBackgroundPosition$Ress.value(CssValueHelper$Ress.px(10))).toBe("10px");
        expect(CssBackgroundPosition$Ress.value2(CssValueHelper$Ress.px(10), CssValueHelper$Ress.position2("center", "bottom"))).toBe("10px, center bottom");
        expect(CssBackgroundPosition$Ress.value3(CssValueHelper$Ress.px(10), CssValueHelper$Ress.position2("center", "bottom"), "center")).toBe("10px, center bottom, center");
        expect(CssBackgroundPosition$Ress.value4(CssValueHelper$Ress.px(10), CssValueHelper$Ress.position2("center", "bottom"), CssValueHelper$Ress.pct(10), CssValueHelper$Ress.position4("left", CssValueHelper$Ress.px(10), "top", CssValueHelper$Ress.pct(10)))).toBe("10px, center bottom, 10%, left 10px top 10%");
        
      }));

test("backgroundStyle", (function () {
        expect(CssBackgroundStyle$Ress.value("repeatX")).toBe("repeat-x");
        expect(CssBackgroundStyle$Ress.value2("repeatX", "repeat__repeat")).toBe("repeat-x, repeat repeat");
        expect(CssBackgroundStyle$Ress.value3("repeatX", "repeat__repeat", "noRepeat")).toBe("repeat-x, repeat repeat, no-repeat");
        expect(CssBackgroundStyle$Ress.value4("repeatX", "repeat__repeat", "noRepeat", "space")).toBe("repeat-x, repeat repeat, no-repeat, space");
        
      }));

var Background;

var BackgroundAttachment;

var BackgroundColor;

var BackgroundImage;

var BackgroundPosition;

var BackgroundStyle;

exports.Background = Background;
exports.BackgroundAttachment = BackgroundAttachment;
exports.BackgroundColor = BackgroundColor;
exports.BackgroundImage = BackgroundImage;
exports.BackgroundPosition = BackgroundPosition;
exports.BackgroundStyle = BackgroundStyle;
/*  Not a pure module */
