// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssFontFamily$Ress = require("../../src/property/CssFontFamily.js");

test("FontFamily", (function () {
        expect(CssFontFamily$Ress.value("initial")).toBe("initial");
        expect(CssFontFamily$Ress.value("sansSerif")).toBe("sans-serif");
        expect(CssFontFamily$Ress.value({
                    NAME: "Family",
                    VAL: "Gill Sans Extrabold"
                  })).toBe("\"Gill Sans Extrabold\"");
        expect(CssFontFamily$Ress.value2({
                    NAME: "Family",
                    VAL: "Gill Sans Extrabold"
                  }, "sansSerif")).toBe("\"Gill Sans Extrabold\", sans-serif");
        expect(CssFontFamily$Ress.value3({
                    NAME: "Family",
                    VAL: "Roboto"
                  }, {
                    NAME: "Family",
                    VAL: "Helvetica"
                  }, "sansSerif")).toBe("\"Roboto\", \"Helvetica\", sans-serif");
        expect(CssFontFamily$Ress.value4({
                    NAME: "Family",
                    VAL: "Roboto"
                  }, {
                    NAME: "Family",
                    VAL: "Helvetica"
                  }, {
                    NAME: "Family",
                    VAL: "Arial"
                  }, "sansSerif")).toBe("\"Roboto\", \"Helvetica\", \"Arial\", sans-serif");
        
      }));

var FontFamily;

exports.FontFamily = FontFamily;
/*  Not a pure module */
