// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var CssMargin$Ress = require("../../src/property/CssMargin.js");
var CssMarginSide$Ress = require("../../src/property/CssMarginSide.js");
var CssValueHelper$Ress = require("../../src/value/CssValueHelper.js");

var include = CssMarginSide$Ress.MakeValue({});

var value = include.value;

var MarginSide = {
  value: value
};

test("margin", (function () {
        expect(CssMargin$Ress.value(CssValueHelper$Ress.px(24))).toBe("24px");
        expect(CssMargin$Ress.value("initial")).toBe("initial");
        expect(CssMargin$Ress.value2(CssValueHelper$Ress.rem(2), CssValueHelper$Ress.rem(4))).toBe("2rem 4rem");
        expect(CssMargin$Ress.value3(CssValueHelper$Ress.px(10), CssValueHelper$Ress.px(24), CssValueHelper$Ress.px(40))).toBe("10px 24px 40px");
        expect(CssMargin$Ress.value4(CssValueHelper$Ress.px(20), CssValueHelper$Ress.px(40), CssValueHelper$Ress.px(20), CssValueHelper$Ress.px(40))).toBe("20px 40px 20px 40px");
        expect(Curry._1(value, CssValueHelper$Ress.px(24))).toBe("24px");
        expect(Curry._1(value, "initial")).toBe("initial");
        
      }));

var Margin;

exports.Margin = Margin;
exports.MarginSide = MarginSide;
/* include Not a pure module */
